### ISSUE TITLE
Review/ sign-off Google page in both E and F

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#101]
** Transferred from StatCanPublication repo ** 

We will need a way to review and approve the full app page, as it shows on the Google Play store before the app goes live to the public.

For reference:

![image](https://user-images.githubusercontent.com/89025880/144672634-1a9a65cc-834e-4ce7-987e-90078e95f081.png)

**Comment by Pharste** [comment]
https://github.com/StatCan/StatCanPublication/issues/146

**Comment by ForumG-SC** [comment]
Access provided

**Comment by ForumG-SC** [comment]
@payeisa Can we close this ticket?

**Comment by Pharste** [comment]
Hi @ForumG-SC , can you please add the screenshots of the Google Product page here? We will do a final review, and then can close the ticket. Thanks!

**Comment by ForumG-SC** [comment]
@ForumG-SC Hi Stephanie, yesterday I sent you invite on new email id to add to the Google store, which will allow you to view Main store listing section , for you to review the posting. Please let me know if you are having trouble accessing it. However , here are the screenshots:

![image](https://user-images.githubusercontent.com/84411852/151004210-bc2c5a9b-cebb-4011-81e4-8f2c4c32b83c.png)
![image](https://user-images.githubusercontent.com/84411852/151004314-fd838f3d-baa1-4f10-96cc-4e1c55838832.png)
![image](https://user-images.githubusercontent.com/84411852/151004381-656ea9b4-a724-4316-bd22-14ff5607f7cd.png)
![image](https://user-images.githubusercontent.com/84411852/151004417-0e77978b-4015-4c5d-b3dd-7d99e6a2987f.png)

I need to update the new screenshots asap.

**Comment by ForumG-SC** [comment]
@Pharste 
![image](https://user-images.githubusercontent.com/84411852/151005475-ee45257b-35c7-4c09-b80a-46c61354195c.png)
Once you accept the invite, you should be able to view/edit the store listing. If having any trouble accessing the page, please let me know.

**Comment by ForumG-SC** [comment]
Screenshots has been updated in the store.
