### ISSUE TITLE
Review/ sign-off Apple page in both E and F

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#102]
** Transferred from StatCanPublication repo : https://github.com/StatCan/StatCanPublication/issues/147 **

We will need a way to review and approve the full app page, as it shows on the Google Play store before the app goes live to the public.

For reference:
![image](https://user-images.githubusercontent.com/89025880/144672851-88b2a5ce-aabc-4361-a870-2d0f760cecdd.png)

**Comment by ForumG-SC** [comment]
Updated English and french(waiting for french promo text)

**Comment by ForumG-SC** [comment]
@Pharste Can we close this ticket??

**Comment by Pharste** [comment]
Hi @ForumG-SC , can you please add the updated screenshots of the Apple product page here? We will do a final review, and then can close the ticket. Thanks!

**Comment by ForumG-SC** [comment]
![image](https://user-images.githubusercontent.com/84411852/151016437-6267d1f5-ca49-455f-9dd6-117f915a44d0.png)
![image](https://user-images.githubusercontent.com/84411852/151016522-e4f2192e-e5d9-4339-af8f-34dc3715ad12.png)
![image](https://user-images.githubusercontent.com/84411852/151016715-065f58e4-e0e2-4f03-93fd-2fd01e02aa24.png)
![image](https://user-images.githubusercontent.com/84411852/151016751-daf9aec6-9949-4308-a240-da27ed468cea.png)
![image](https://user-images.githubusercontent.com/84411852/151016788-b48bea9d-9d92-42f6-93f1-7b3b5684796a.png)
![image](https://user-images.githubusercontent.com/84411852/151016916-92c842ce-d843-4524-a949-a241de18bbe3.png)


@Pharste Could you please verify the information here, and please let me know if you want me to modify anything as tomorrow we will be doing final submission to the stores. I am waiting for new screenshots apart from that all the information have been added.

**Comment by Pharste** [comment]
@ForumG-SC Can you please remove the promotional text, and update the keywords in English, as well as the support URL? It looks like the wellbeing app info is here...

**Comment by ForumG-SC** [comment]
@Pharste I shared wrong screenshot, my apologies. Here is the correct screenshot:
![image](https://user-images.githubusercontent.com/84411852/151037535-2334dfdc-be2e-40c6-9bec-e3d88270b011.png)

**Comment by Pharste** [comment]
Thank you @ForumG-SC 
It all looks good, just one thing-- the '?' should be removed from the French support URL. :)

**Comment by ForumG-SC** [comment]
> Thank you @ForumG-SC
> It all looks good, just one thing-- the '?' should be removed from the French support URL. :)

Fixed,
![image](https://user-images.githubusercontent.com/84411852/151040817-f90d22be-5595-4136-a127-592d63be1d41.png)

**Comment by Pharste** [comment]
Thank you! Also just realizing the Welcome image will have to be updated in both languages, with 'StatsCAN'

**Comment by ForumG-SC** [comment]
> Thank you! Also just realizing the Welcome image will have to be updated in both languages, with 'StatsCAN'

Welcome image?

**Comment by Pharste** [comment]
> > Thank you! Also just realizing the Welcome image will have to be updated in both languages, with 'StatsCAN'
> 
> Welcome image?

Sorry, the welcome screen image. The one above still says 'Welcome to StatCan'.

**Comment by ForumG-SC** [comment]
> > > Thank you! Also just realizing the Welcome image will have to be updated in both languages, with 'StatsCAN'
> > 
> > 
> > Welcome image?
> 
> Sorry, the welcome screen image. The one above still says 'Welcome to StatCan'.

The screenshots are yet to be updated, I am waiting to receive it.

**Comment by ForumG-SC** [comment]
Screenshots has been updated in the store.
