### ISSUE TITLE
Review/ sign-off Developer page in E and F

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#103]
** Transferred from StatCan Publication repo : https://github.com/StatCan/StatCanPublication/issues/149 **

We will need to review and update the current Statistics Canada developer pages (published with Vitali-T). Once the content has been updated, we will need to approve and submit to the Apple/Google stores before the app's launch on Jan 31.

Google Play Developer page info: https://support.google.com/googleplay/android-developer/answer/9873827?hl=en#zippy=

Current StatCan Google Developer page: https://play.google.com/store/apps/dev?id=4804805194854452523
Current StatCan Apple Developer page: https://apps.apple.com/ca/developer/statistics-canada/id1496401126

**Comment by ForumG-SC** [comment]
@Pharste Access provided

**Comment by ForumG-SC** [comment]
@Pharste Can we close this ticket ?

**Comment by Pharste** [comment]
@ForumG-SC Hi, the new content for the developer page has been signed off and is available here: 
https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=20118112 
I will also send to you by email. Please confirm when the page has been updated, and then we can close the ticket.

**Comment by ForumG-SC** [comment]
New details have been updated, waiting for header image with correct dimensions.

**Comment by ForumG-SC** [comment]
Developer page has been updated:
![image](https://user-images.githubusercontent.com/84411852/150835488-77718ee0-7327-4b14-b535-935e007f1843.png)
![image](https://user-images.githubusercontent.com/84411852/150835519-46bbe2ae-d068-4b7e-87d1-94f12279a9cd.png)

**Comment by Pharste** [comment]
Hi Forum, 

A couple of minor tweaks:

**Comment by ForumG-SC** [comment]
@Pharste Hi Stephanie , I am confused because the screenshot that I shared it is already 'Statistique Canada' , there is no 's'.

The promo text is already Bilingual , we are displaying English and French both, we cannot combine them due to limited words but we can still see them both when respective language option is selected.

**Comment by Pharste** [comment]
@ForumG-SC sorry, I should have clarified, the screenshots look great, but the Developer page link is displaying the s, and English only: https://play.google.com/store/apps/dev?id=4804805194854452523 

Unless this takes time to publish?

**Comment by ForumG-SC** [comment]
> @ForumG-SC sorry, I should have clarified, the screenshots look great, but the Developer page link is displaying the s, and English only: https://play.google.com/store/apps/dev?id=4804805194854452523
> 
> Unless this takes time to publish?

If you see the above screenshot , there is pop-up stating that the name is under review, it will take some time to update. Rest assured all the content has been updated as per the doc you provided.

**Comment by ForumG-SC** [comment]
![image](https://user-images.githubusercontent.com/84411852/150867587-c60dc6dc-742d-4084-aa2c-ace844ea1cef.png)

**Comment by Pharste** [comment]
Thank you Forum. Sorry about that!!

**Comment by ForumG-SC** [comment]
> Thank you Forum. Sorry about that!!

It's all good.  :)
