### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#104]
From the Search screen - enter a search keyword (i.e. economy)
Search
Select the first result (to navigate to that article)
Then click on the Search menu item.
The screen will display the "No results found" message. 
It should display the last search performed instead.

**Comment by Jiandong-Guo** [comment]
Fixed and Checked in and will be ready to test when server is back on

**Comment by payeisa** [comment]
It seems to have been fixed in English, but not in French. For example.
From French interface, go to "Rechercher"
Enter keyword (i.e. voyage)
Search
Select the first article to navigate to the level 2
Click on "Rechercher" to return to search screen
There are no search results, only recent searches.

![image](https://user-images.githubusercontent.com/89025704/146975530-9767dcb1-b861-4d8d-84fd-de4c9629fc30.png)

**Comment by Jiandong-Guo** [comment]
Fixed and please test it on next release

**Comment by payeisa** [comment]
Validated.
