### ISSUE TITLE
Date and time format on Search results screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#105]
From the search screen - after a search has been performed and results returned.
The date and time format should be the same as the one used in article level 2.

![image](https://user-images.githubusercontent.com/89025704/145026178-731f5e6c-1b24-4271-85ff-2893ec6b7bba.png)

**Comment by ForumG-SC** [comment]
It is resolved, assigning it back to you for validations.

**Comment by payeisa** [comment]
Validated.
