### ISSUE TITLE
Article level 2: Display of ORPS article images

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#107]
The app is not displaying the images properly, in level 2.  The app does not resize the image properly.

For example, the article "A beautiful sunny fall", published December 3, 2021, was recreated exactly as it was published for StatsCAN Plus.  This is the link to the StatsCAN Plus article, on the StatCan website: https://www.statcan.gc.ca/o1/en/plus/191-beautiful-sunny-fall

This seems to be the case for all StatsCAN Plus articles that have been loaded. 

Other examples:
Canada's most charitable metropolitan areas
Prices are rising, but by how much?

**Comment by zhuelle** [comment]
This is related to https://github.com/StatCan/StatcanPublicationUAT/issues/94 
@payeisa would you please check the comments in #94 to see if we need this bug ticket?

**Comment by payeisa** [comment]
@zhuelle 94 and 107 are in fact two separate issues.

**Comment by payeisa** [comment]
Hi, we will need to take some time to review requirements for images and get back to you. I will schedule a meeting with Rajat to discuss. Thanks, Isabelle

**Comment by Jiandong-Guo** [comment]
fixed, please test it in next release

**Comment by payeisa** [comment]
Validated.
