### ISSUE TITLE
Display: auto-rotate

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#11]
Is auto-rotate an option for the StatCan app (portrait and landscape)? It doesn't seem to work on my devices.

Samsung  Galaxy S9, Android version 10
Samsung Galaxy Tab S6 Lite Android version 11

Thanks,
Isabelle

**Comment by ForumG-SC** [comment]
Fixed

**Comment by AJBouzidi** [comment]
This is still to be reviewed because the landscape app will create a lot of unknown issues for the display. this need to be treated case by case.
