### ISSUE TITLE
UX Publications Level 2 Screen: Share & contact us buttons

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#111]
At the bottom of the screen, Share this publications and contact us layout has been changed from links to button by adding icons.

Is this the actual design if the buttons? They seem different the rest of the design.

@ Rajat: not sure if I should be assigning tickets to you? (but this one is UX related :))

**Comment by ForumG-SC** [comment]
@payeisa The UX of pubs level 2 screen is yet to be implemented according to the prototype, next week UX will be improved and this issue will be resolved.

**Comment by ForumG-SC** [comment]
@payeisa Please validate if the bottom button styling looks okay.

**Comment by ForumG-SC** [comment]
@payeisa Please validate if the bottom button styling looks okay in the current dev version.

**Comment by payeisa** [comment]
@ForumG-SC The design looks ok (assuming @Rajat-Sen agrees).
Also, I'm not sure if the functionality was ready to be tested (if not, I can submit another ticket), but when I click on the "Share this publication" button, I navigate to the "Share this app" screen.

**Comment by ForumG-SC** [comment]
> 

Investigating the button's functionality issue, the fix will be applied in the next release.

**Comment by payeisa** [comment]
Would it be possible for the "Share this publication" button at the bottom of the Publications level 2 screen to look like the other buttons used in the app? For example, the "Select subjects" button on the "For you - Following" screen, or the "Go to publications" button on the "For you - saved screen".

@ForumG-SC I will create a separate ticket for the functionality of the button.

**Comment by Rajat-Sen** [comment]
Closing this ticket as it was related to the previous version of the app.
