### ISSUE TITLE
Screen headers - discrepancies

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#112]
The screen headers seem to be different from one screen to another.
StatsCAN Publications (look good)
Search - font seems bigger than StatsCAN Publications
For you - centered (but the other ones are not)
Settings - font is bigger

**Comment by ForumG-SC** [comment]
@payeisa Fonts for the Search Screen header will be changed like StatsCAN Publications.
For you - Which other ones should be centered?
Settings Screen - Major UX updates have been done which will be seen in Friday's release which resolves the header issue.

**Comment by ForumG-SC** [comment]
@payeisa  For you - Which other ones should be centered?

**Comment by payeisa** [comment]
@ForumG-SC I think the heading for the "For you" screen should be consistent with the other ones (i.e. Publications, Search, Settings are not centered.)

**Comment by ForumG-SC** [comment]
@payeisa Does this works ?

![image](https://user-images.githubusercontent.com/84411852/145440450-cb47a201-658f-49d8-8401-bef9f5758244.png)

**Comment by payeisa** [comment]
@ForumG-SC  Yes, I think this works, and it's consistent with the rest of the screens.

**Comment by payeisa** [comment]
The "For you" heading is cutting off:

![image](https://user-images.githubusercontent.com/89025704/145997483-d5dedb22-da09-481a-a8fe-771ec8d0e8b5.png)

**Comment by ForumG-SC** [comment]
> The "For you" heading is cutting off:
> 
> ![image](https://user-images.githubusercontent.com/89025704/145997483-d5dedb22-da09-481a-a8fe-771ec8d0e8b5.png)

Is the screenshot from 5.8 inch screen size Samsung Galaxy ?

**Comment by ForumG-SC** [comment]
> > The "For you" heading is cutting off:
> > ![image](https://user-images.githubusercontent.com/89025704/145997483-d5dedb22-da09-481a-a8fe-771ec8d0e8b5.png)
> 
> @payeisa  Is the screenshot from 5.8 inch screen size Samsung Galaxy ?

**Comment by payeisa** [comment]
@ForumG-SC Yes it's a 5.8" screen (Android Samsung Galaxy S9)

**Comment by ForumG-SC** [comment]
Fixed.

**Comment by payeisa** [comment]
It's better, but the heading is still cutting off:
![image](https://user-images.githubusercontent.com/89025704/146978166-d09f752d-88cc-4c52-b596-b9f479429bf3.png)

**Comment by ForumG-SC** [comment]
> It's better, but the heading is still cutting off: ![image](https://user-images.githubusercontent.com/89025704/146978166-d09f752d-88cc-4c52-b596-b9f479429bf3.png)

I have been testing in 5.8 inches Pixel android phone emulator and it looks fine. I don't have Samsung emulator to test, looks like fix didn't worked properly, I will apply another fix for you to test in next release.

**Comment by payeisa** [comment]
@ForumG-SC Thanks! Can you please re-assign this ticket to me when it's ready for validation?

**Comment by ForumG-SC** [comment]
> @ForumG-SC Thanks! Can you please re-assign this ticket to me when it's ready for validation?

It is ready for validation in the next release.

**Comment by payeisa** [comment]
The options menu (three dots) should be displayed/align similar to the notification bell on the Publications screen. i.e. the menu/three dots should be moved over to the right.

![image](https://user-images.githubusercontent.com/89025704/147675307-eb457a17-bc8a-4b15-a8aa-b4ad7a8bd0f2.png)

The "Search" heading should also be spaced out like the "Publications" header. Right now it seems to be aligned to the top, so there's more white space compared with the "Publications" header.

![image](https://user-images.githubusercontent.com/89025704/147675522-ee0f4eb2-941b-46a2-987c-c690eb39a726.png)

**Comment by payeisa** [comment]
Validated.
