### ISSUE TITLE
Storing of search text & switching of interface language

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#113]
If I'm using the app in English, perform a search, and then decide I want to switch the language of the app to French, the keyword search I had entered in English is maintained, and I automatically get the "No results found" message - which is not always accurate.

For example, if I search for "Transport" in English - I get  5 results and if I search for "Transport" in French, I will get 6 results.

Perhaps a simple way would be to display the Search intro screen if the interface language is switched? 
Or if the keyword is kept, then an actual search should be performed.

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo 

This is a priority ticket as well. Just wanna make sure Publications and search screen are intact before you go! Thanks

**Comment by Jiandong-Guo** [comment]
Fixed and Checked in and will be ready to test when server is back on

**Comment by payeisa** [comment]
Validated.
