### ISSUE TITLE
Search results & filters by subject

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#114]
When filtering search results by subjects, the list of subjects provided should be displayed in alphabetical order.

![image](https://user-images.githubusercontent.com/89025704/145268392-17046198-cd6e-466a-992a-9ec121eebf01.png)

**Comment by Jiandong-Guo** [comment]
Fixed and Checked in and will be ready to test when server is back on

**Comment by payeisa** [comment]
Validated.
