### ISSUE TITLE
Search behaviour: back arrow

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#115]
If I search for "pig", I will get 1 result.
Click on the article to go to the level 2.
Then click on the back arrow to return to the Search screen.
I'm provided with the "No results found" screen.
I should be presented with the last search I performed, or if that can't be done, then I should be presented with the Intro screen.

**Comment by Jiandong-Guo** [comment]
Fixed and Checked in and will be ready to test when server is back on

**Comment by payeisa** [comment]
Validated.
