### ISSUE TITLE
Max search results (20)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#116]
Are we limiting the number of search results returned to 20? (i.e. if I search for "the" or "at", I only get 20 results).
Which is ok, but I think we should let users know about this, if that's the case

**Comment by Rajat-Sen** [comment]
This is not priority for now as when we launch the application, it is going to have limited number of articles.

**Comment by Rajat-Sen** [comment]
This should be one of the first issue after releasing the MVP.

**Comment by Jiandong-Guo** [comment]
Better do it in database side,  it makes no sense for front side to set the limit because it has already spent lot bandwidth to retrieve the data to front side

**Comment by AJBouzidi** [comment]
This is need to be revisited with the backend team.

**Comment by lamokar10** [comment]
Ok, I will talk to Kerry about this one.

**Comment by lamokar10** [comment]
@AJBouzidi
Ali, from my discussion with Kerry and looking at the documentation, there is ambiguity with the API used in the search?
In https://confluenceb.statcan.ca/display/SPMA/Feature+4.1+Search+text+and+retrieve+results, it mentions mobile-article-search-eng.json or mobile-article-search-fra.json but according to Kerry, it should be List Articles (https://sdr-daily-alpha.cloud.statcan.ca/api). Could that explain the limitation on our side?

**Comment by Jiandong-Guo** [comment]
@payeisa 
The API the search function using is:
    https://www.statcan.gc.ca/o1/en/api/plus/article?t=${criteria}
From the document, the api has the paging function already there by using page=#
My concern to be clarified is if I didn't pass the page parameter explicitly, does the api will use the default page=0 ?

**Comment by ForumG-SC** [comment]
@zhuelle  As per our discussion in the meeting, please find the attached screenshot of the label on the search screen below which can be modified to let the users know :
![s](https://user-images.githubusercontent.com/84411852/169060504-f43135ba-55c7-457c-815b-6a4f4a0f3fd8.jpg)

**Comment by Jiandong-Guo** [comment]
So we don't need to do anything

**Comment by zhuelle** [comment]
@payeisa We discussed this issue in our virtual Standup today. Basically, here is what I gather:

1. The api is returning all search results by paging. Each page has 20 results. 
2. The mobile app is currently displaying the 20 results in the first page
3. There is a message "20 results found" displayed in the search page (please see picture attached in the Forum's comment above)

Would you please confirm if you would like to change anything on the mobile side based on the information provided? Thanks!

**Comment by lamokar10** [comment]
@Jiandong-Guo, if we are limiting the results to 20 even if there are more then we have to let business know. And we have to update the requirements accordingly. And we would also need to inform the user that the results are limited to the first 20 and that other results are not available for display. So I think there are things to do.

This is my understanding of what Isabelle is asking. Are we limiting? If yes, then we need to inform the users of the limitation.

**Comment by payeisa** [comment]
@lamokar10 That's correct. If we are in fact limiting the search results, we should let the users know. I would recommend adding text on the Intro Search screen and on the Search screen, since, now that we are almost 4 months in, most searches will return 20 results because we now have a lot of content. So having "20 results found" is misleading. For example, the following keywords all return 20 results: Covid, health, population, police, train, car, children, market, food, price etc.

@weglmar FYI

**Comment by zhuelle** [comment]
@payeisa Thanks for your confirmation. To proceed the request, @lamokar10 will work with the business to finalize the change to the requirements, then the dev team can proceed the change once the requirements are done. Is it correct?

**Comment by payeisa** [comment]
@zhuelle That's correct!

**Comment by payeisa** [comment]
@zhuelle I will un-assign myself from this ticket since there is no action required from me, for now. I'm assuming Karine will be providing the specs to the dev team (once she has them), and then this ticket will be assigned back to me once it's ready for testing. Please let me know if that's not case, and if this should be handled differently. Thanks, Isabelle

**Comment by lamokar10** [comment]
@Pharste, has the message been approved and translated to indicate to the users that only 20 results can be shown?

**Comment by zhuelle** [comment]
A CR (https://jirab.statcan.ca/browse/ORPS-118) has been sent on the ORPS (backend) project and the request for changing the API is rejected by the Business Owner.

For short term, the decision is to add a message to the search results screen to let the users know that only 20 results were returned. The final messaging has not yet been provided, but will be available soon.

**Comment by Pharste** [comment]
Hi, 

Here is the final messaging. Please note that we would like to add text to the intro screen, as well as the search results screen.

Search intro screen -

EN: 
Find publications published in the StatsCAN app.
Note: A maximum of 20 publications will be shown. 

FR: 
Trouvez les publications diffusées dans l’application StatsCAN.
Note : Le nombre de publications affichées est limité à un maximum de 20.


Search results (to be displayed when 20 results are provided only) - 

EN: 
20 results found
Note: Search results are limited to a maximum of 20.

FR: 
20 résultats trouvés
Note : Les résultats de la recherche sont limités à un maximum de 20 publications.



Please let me know if there are any questions!
Thanks,
Stephanie

**Comment by weglmar** [comment]
**Search results (EN):**
Missing a period as per text above. 

![image](https://user-images.githubusercontent.com/98898969/182391970-b311052e-b941-4fd4-92f4-46aeddc5511b.png)

**Search results (FR):**
Does not reflect the message provided above. It should be: Les résultats de la recherche sont limités à un maximum de 20 publications.

![image](https://user-images.githubusercontent.com/98898969/182392184-39c1807a-9b22-4e41-93b0-3304ce1a22e6.png)

**Comment by weglmar** [comment]
Validated.
