### ISSUE TITLE
Pour vous - Éléments d'intérêts - subject spanning over two lines

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#117]
When the subject spans over two lines on the For you - Following screen (i.e. Services aux entreprises et aux consommateurs et culture),  the "Afficher tout" option gets cut-off and does not display properly.

![image](https://user-images.githubusercontent.com/89025704/145283756-5fcb2578-6f78-4836-a168-fd78d94e7b72.png)

**Comment by Rajat-Sen** [comment]
Wai/ting to confirm with the clients

**Comment by Rajat-Sen** [comment]
This ticket is for the sell all option getting cut off, when the subject spans over 2 lines.

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
