### ISSUE TITLE
Unfollow subject (alignment of text & display)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#118]
The alignment of the text to Unfollow a subject does not seem to be consistent. I would recommend left-aligning the text.

For you - (make sure you are following subjects) - See all - 3 ellipses - 
![image](https://user-images.githubusercontent.com/89025704/145285210-03bce294-52ec-4a0e-beaf-6a6722e96550.png)

![image](https://user-images.githubusercontent.com/89025704/145285285-952b5c27-f9e3-4711-8755-3e6a7e9538b4.png)

![image](https://user-images.githubusercontent.com/89025704/145285332-4eeb85f4-9ebc-4f83-9b49-b979c10d5951.png)

The text box should also be expanded to accommodate the longer subjects:

![image](https://user-images.githubusercontent.com/89025704/145285425-5eed5d10-675e-4020-8c25-e19f847ffb22.png)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
The alignment looks good, however, if the subject spans on two lines, there's isn't enough space. For example:

![image](https://user-images.githubusercontent.com/89025704/148703702-0ef33955-3b5e-4f08-bb92-7cb44c52b5d8.png)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
