### ISSUE TITLE
Language screen: size of buttons

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#12]
The buttons on the language screen should be the same size. Right now, the English button is smaller.

Thanks,
Isabelle

**Comment by ForumG-SC** [comment]
Fixed, the changes will be deployed in the upcoming release.

**Comment by payeisa** [comment]
Validated Sept 09, 2021.

**Comment by ForumG-SC** [comment]
@payeisa  French interface is updated and the changes will be reflected in the upcoming release to test.

**Comment by ForumG-SC** [comment]
done

**Comment by ForumG-SC** [comment]
@payeisa This issue has been resolved and requires validation, assigning it back to you.

**Comment by payeisa** [comment]
Need issue #35 to be fixed before validating this one.

**Comment by payeisa** [comment]
If my device language is set to French, should I not be presented with a French-leading language screen? Right now, I'm getting the English-leading language screen (even though I changed my device language to French. Note that I did delete my app's user profile, closed the app, and restarted my device after the change was made.

**Comment by ForumG-SC** [comment]
@payeisa Could you please revalidate this issue in the current dev version?

**Comment by payeisa** [comment]
Validated.
