### ISSUE TITLE
Hiding the contact us button

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#120]
Please hide the contact us button on level 2 as it is already there attached to the article itself. Additionally, it solves the Google problem of displaying contact information.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Hide this in the header or in the bottom of the screen ?

**Comment by Rajat-Sen** [comment]
Hide the on bottom of the screen as, contact information is already available at the end of every publication.
