### ISSUE TITLE
Settings/Text size Instruction text below text size slider

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#123]
It looks like the instruction text in French is spanning too wide. It's very close to the edge, and goes beyond the width of the white boxes.

![image](https://user-images.githubusercontent.com/89025704/146004670-ab51717c-49df-4496-9e87-798b17d7a9d7.png)

**Comment by ForumG-SC** [comment]
Fixed, changes will be reflected in the upcoming release. Assigning it back to you for the validation.

**Comment by payeisa** [comment]
Validated.
