### ISSUE TITLE
Home screen heading & large text

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#124]
When setting the text size to the largest setting possible (Settings/Text size), the alignment of the header on the Publications screen becomes off. i.e. it should be left-aligned.

![image](https://user-images.githubusercontent.com/89025704/146005002-3d0a60fd-7618-41a7-a96f-ba79595b79fa.png)

**Comment by ForumG-SC** [comment]
Fixed.

**Comment by payeisa** [comment]
Validated.
