### ISSUE TITLE
Settings/Manage notifications (typo)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#126]
"recieve" should be "receive"

![image](https://user-images.githubusercontent.com/89025704/146013933-7e10a8f4-69bb-4c12-be3f-182207e17328.png)

**Comment by ForumG-SC** [comment]
Done, the changes will be reflected in the upcoming release. Assigning it back to you for validation.

**Comment by payeisa** [comment]
Validated.
