### ISSUE TITLE
Update translation: "I want to be notified about..."

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#127]
![Notifications fr](https://user-images.githubusercontent.com/89025880/146022534-ad85766c-6866-4f70-87b3-0dc4fdd45bbe.png)

The French text for "I want to be notified about..."should be "Je veux recevoir des notifications sur..." and not "je veux etre averti de..."

**Comment by ForumG-SC** [comment]
Done, changes will be reflected in the upcoming release, assigning it back to you for validation.

**Comment by Pharste** [comment]
validated, thank you!
