### ISSUE TITLE
Settings/Social media

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#128]
The social media icons are not displaying properly:

![image](https://user-images.githubusercontent.com/89025704/146028637-6d650fff-539d-4133-9852-f09b532efe0f.png)

"Youtube" should be "YouTube" (with a capital "T")
LinkedIn should be '"Linkedin" (with a lowercase "i")

The links to the social media platforms should be the same as the ones used here:
https://www.statcan.gc.ca/o1/en/plus
https://www.statcan.gc.ca/o1/fr/plus

**Comment by ForumG-SC** [comment]
@payeisa Could you please provide me with the screen size used in the screenshot and the device model ?

**Comment by payeisa** [comment]
@ForumG-SC  It's a Samsung Galaxy S9 and the screen is 5.8 inches.

**Comment by ForumG-SC** [comment]
@payeisa Tested in 5.8 inches , couldn't replicate the issue. However, I will modify some things for the icons and you can test it in the next release to verify if the fix worked or not.
![image](https://user-images.githubusercontent.com/84411852/146078592-9b58a715-7a84-4757-ac23-22e527015f07.png)

**Comment by ForumG-SC** [comment]
@payeisa Please confirm the urls:

EN:
  "facebookLink": "https://www.facebook.com/StatisticsCanada/",
  "instaLink": "https://www.instagram.com/statcan_eng/",
  "linkedinLink": "https://ca.linkedin.com/company/statcan",
  "redditLink": "https://www.reddit.com/user/StatCanada/",
  "twitterLink": "https://twitter.com/statcan_eng",
  "youtubeLink":"https://www.youtube.com/statisticscanada"

FR:
"facebookLink": "https://www.facebook.com/statistiquecanada",
  "instaLink": "https://www.instagram.com/statcan_fra/",
  "linkedinLink": "https://ca.linkedin.com/company/statcan",
  "redditLink": "https://www.reddit.com/user/StatCanada/",
  "twitterLink": "https://twitter.com/statcan_fra",
  "youtubeLink": "https://www.youtube.com/user/StatistiqueCanada"

**Comment by payeisa** [comment]
@ForumG-SC The URLs above are accurate. Thanks, Isabelle

**Comment by ForumG-SC** [comment]
Done, changes will be reflected in the new version, assigning it back to you for the validations.

**Comment by payeisa** [comment]
Validated the links, and the typos have been fixed, however, the display is still off:

![image](https://user-images.githubusercontent.com/89025704/146983290-83715eaa-e612-450a-9446-3c80238d0c49.png)

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Validated.
