### ISSUE TITLE
Settings/More information/Privacy notice

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#129]
The header and footer for the Privacy notice should be removed (same as article level 2).

Avis de confidentialité should link to the French page:  https://www.statcan.gc.ca/fr/reference/privee
(right now it's linking to the English page)

**Comment by Rajat-Sen** [comment]
Additionally, when clicked on any link on the Privacy notice screen, there are no controls to go back or forward which is creating confusion as the only place the user can go is back to settings screen.

Using web-view in Privacy notice is fine. However, if the user clicks on a link it should open up in-app browser like article level-3.

**Comment by ForumG-SC** [comment]
> Additionally, when clicked on any link on the Privacy notice screen, there are no controls to go back or forward which is creating confusion as the only place the user can go is back to settings screen.
> 
> Using web-view in Privacy notice is fine. However, if the user clicks on a link it should open up in-app browser like article level-3.

if we are stripping off header and footer there will be no way for the user to navigate to any other screen and the whole purpose to display Privacy policy notice screen is for user to read the privacy policy of our app and not to navigate like Publications as it is not article screen. Therefore, there are no navigations button in the bottom.

**Comment by Rajat-Sen** [comment]
I think the deletion header and footer is meant for the StatCan website which gets displayed, the same way it is done on Contact us screen; not for the app itself.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo There is two issues in this ticket: 

1.  **_"Avis de confidentialité should link to the French page: https://www.statcan.gc.ca/fr/reference/privee"_**  (this is done already)
2. The header and footer for the Privacy notice should be removed same as contact us.

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by Jiandong-Guo** [comment]
Please test it. It should ne done long time ago

**Comment by payeisa** [comment]
Validated with no issues.
