### ISSUE TITLE
Settings/Terms of Use

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#130]
The Terms of use menu item and heading should be "Terms of Use" (with a capital "U")

**Comment by ForumG-SC** [comment]
Done ,Assigning it back to you for validation.

**Comment by Rajat-Sen** [comment]
The Terms of Use is used consistently through out the whole description, and have grammatical errors which is causing  Voiceover issues (Accessibility testing). 

Is this the final version or sample text? 

Based on that I can provide feedback accordingly!

**Comment by payeisa** [comment]
@Rajat-Sen The final Terms of Use have not been delivered yet. They are currently in final approvals, and will be going to translation next. We will have the final text in early January.

**Comment by payeisa** [comment]
Validated.
