### ISSUE TITLE
Settings/Help & FAQs

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#131]
When clicking the "Copy email address" option in the Email section, I would expect a pop up message to let me know the item has been copied (i.e. copied to clipboard). 

![image](https://user-images.githubusercontent.com/89025704/146050364-c321005a-a66a-46c1-aa11-d631cc7f9917.png)

**Comment by ForumG-SC** [comment]
@payeisa Could you please provide me with the translations ? 

![image](https://user-images.githubusercontent.com/84411852/146057648-e2440f71-7f37-48b0-a6d9-43820cb984a8.png)

**Comment by payeisa** [comment]
@ForumG-SC Here are the labels:
English: Item copied to the clipboard.
French: Élément copié sur le presse-papier.

I just want to make sure that, that is in fact the expected behaviour? i.e. does the Infostats email address get copied to the clipboard?

**Comment by ForumG-SC** [comment]
@payeisa 
https://user-images.githubusercontent.com/84411852/146077308-80f6d5c6-e16e-406f-a962-7b658bb79a91.mp4

**Comment by ForumG-SC** [comment]
https://user-images.githubusercontent.com/84411852/146079276-b209be5f-c05d-4d9e-ab88-abc65a514c14.mp4

**Comment by ForumG-SC** [comment]
Assigning it back to you to test this in the next release and validate it.

**Comment by payeisa** [comment]
Is there a way we can make this a temporary display (i.e. similar to when the user clicks the heart icon on an article?
That way there is no action required from the user.

**Comment by Rajat-Sen** [comment]
We can use Toast to display the message temporarily, in that way there won't be any action required from the user. Also, please set the time to 3.5 seconds.

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
I validated the functionality, however, the display is not set to 3.5 seconds (it's more like 10 seconds). Can we please adjust that?

**Comment by ForumG-SC** [comment]
> I validated the functionality, however, the display is not set to 3.5 seconds (it's more like 10 seconds). Can we please adjust that?

Fixed

**Comment by payeisa** [comment]
Validated.
