### ISSUE TITLE
Settings/Help & FAQs/FAQs

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#132]
The icon for FAQS is cut-off

![image](https://user-images.githubusercontent.com/89025704/146050706-7e8d0683-522a-4383-9ff9-f2e0fcaa5ed9.png)

**Comment by ForumG-SC** [comment]
@payeisa Could you please provide me with more details like : What is the screen size of the phone that you are testing ? IOS or android? Mobile model name ?

**Comment by payeisa** [comment]
@ForumG-SC  It's an Android, Samsung Galaxy S9, version 10

**Comment by ForumG-SC** [comment]
@payeisa Fixed, assigning it back to you for validation.

**Comment by payeisa** [comment]
It's better, but it's still outside the white text box:
![image](https://user-images.githubusercontent.com/89025704/146984711-86730bc5-07a9-4dca-aa9b-45778922b16c.png)

**Comment by ForumG-SC** [comment]
> It's better, but it's still outside the white text box:
> ![image](https://user-images.githubusercontent.com/89025704/146984711-86730bc5-07a9-4dca-aa9b-45778922b16c.png)

I think the fix doesn't get applied to the Samsung's device, it worked on 5.8 inches android screen on Google Pixel device but not samsung . I will apply alternative fix for this issue for you to test in the next release.

**Comment by payeisa** [comment]
Validated.
