### ISSUE TITLE
Margin for screens

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#135]
For the Article level -2, Terms of use, privacy policy, onboarding screens or anywhere there is text by itself, there needs to be a margin of 16Px on each side. i.e. Left and right.

**Comment by ForumG-SC** [comment]
@Rajat-Sen In the prototype cancel button looks different. Do you want me to change the cancel button's look like prototype ?

Currently , this is how it looks:
![image](https://user-images.githubusercontent.com/84411852/146434735-4ca4b704-d678-4a67-b9d0-09baa9996a0f.png)


Prototype screenshot:
![image](https://user-images.githubusercontent.com/84411852/146434800-77d4c04a-1709-493e-a2cf-e460afcb9e15.png)

**Comment by ForumG-SC** [comment]
Done
