### ISSUE TITLE
Settings - Preferences - Manage notifications - toggle

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#136]
The "In-app notifications" and the "Subjects of interest" should be connected/dependent on one another.

For example:
If the user slides the "In-app notifications" toggle to "On", then the "Subjects of interest" toggle should automatically also be set to "On".

If the user slides the "In-app notifications" toggle to "Off", then the "Subjects of interest" toggle should automatically also be set to "Off".

If the user slides the "Subjects of interest" toggle to "On", then the "In-app notifications" toggle should automatically also be set to "On".

If the user slides the "Subjects of interest" toggle to "Off", then the "In-app notifications" toggle should automatically also be set to "Off".

**Comment by ForumG-SC** [comment]
Related to https://github.com/StatCan/StatCanPublication/issues/175, Mark all read button not working and fix toggle

**Comment by Jiandong-Guo** [comment]
Fixed, please test in next release.
But just wonder those two flags mean one thing, why using 2 flags ?

**Comment by Rajat-Sen** [comment]
It is related to when we are going to update the app in the future!

**Comment by payeisa** [comment]
Validated.
