### ISSUE TITLE
Button sizes

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#138]
The button sizes are different on Welcome screen and Terms of use. Please match it to the prototype for consistency. Also, the headers have a lot of padding from the top instead of aligning such as Terms of User screen.

**Comment by ForumG-SC** [comment]
@Rajat-Sen In the prototype cancel button looks different. Do you want me to change the cancel button's look like prototype ?

Currently , this is how it looks:
![image](https://user-images.githubusercontent.com/84411852/146434735-4ca4b704-d678-4a67-b9d0-09baa9996a0f.png)


Prototype screenshot:
![image](https://user-images.githubusercontent.com/84411852/146434800-77d4c04a-1709-493e-a2cf-e460afcb9e15.png)

**Comment by Rajat-Sen** [comment]
@ForumG-SC Yes, please make it similar to the prototype.

**Comment by ForumG-SC** [comment]
Done
