### ISSUE TITLE
Disabling the slider from the Tab Bar

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#139]
The slider on the bottom of the Tab Bar, when the user selects the Publications screen or any other screen needs to be removed as it will create confusion for the iOS users and it's not the best place to out the slider. Let's remove it for now. Also, it's being cut off from the edges of the screen.

Moreover, when the user goes to a new screen, the transition should not look like a slider. Instead, we are loading a whole new screen.

**Comment by Jiandong-Guo** [comment]
Fixed, Please test in next release

**Comment by payeisa** [comment]
Assigning to Rajat for validation.

**Comment by Rajat-Sen** [comment]
Validated
