### ISSUE TITLE
App screenshots

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#140]
As discussed Dec 16, we will need updated screenshots in both French and English, to deliver to creative communications and produce the enhanced screens for the app store pages. 

These are the required screens: 

**Google:** 
- Welcome screen
- Home screen
- For you (following intro screen)
- For you (saved intro screen)
- Search (with results)
- Notifications

Screen sizes:
Phone: PNG or Jpeg 16:9 or 9:16 aspect ratio, each side between 320px and 3840 px, up to 8mb
7 inch Tablet screenshots:                      
PNG or Jpeg 16:9 or 9:16 aspect ratio, each side between 320px and 3840 px, up to 8mb

**Apple:**
- Welcome screen
- Home screen
- For you (Following intro screen)
- Notifications

Screen sizes: 
iPhone 6.5 inch: 1242*2688 or 2688*1242
iPhone 5.5 inch: 1242*2208 or 2208*1242
iPad pro (3rd Gen) 12.9 inch: 2048*2732 or 2732*2048
iPad pro (2nd gen) 12.9 inch: 2048*2732 or 2732*2048

PNG or Jpeg 16:9 or 9:16 aspect ratio, each side between 320px and 3840 px, up to 8mb
7 inch Tablet screenshots:                      
PNG or Jpeg 16:9 or 9:16 aspect ratio, each side between 320px and 3840 px, up to 8mb

**Comment by Rajat-Sen** [comment]
Hi Forum, would you be able to provide the final screenshots required by the comms department from the simulator/emulator after server us up and running and the app is looking closer to the expectations? Thanks!

**Comment by ForumG-SC** [comment]
@Pharste Until when do you need the screenshots because we are still working on the UX , it is not entirely completed.

**Comment by Pharste** [comment]
Hi Forum,

Sooner than later would be better. If there are major changes coming to the UX, we can hold off. But, if there are only minor changes to be made, we are ok to go forward with the screens as they are.

**Comment by ForumG-SC** [comment]
> Hi Forum,
> 
> Sooner than later would be better. If there are major changes coming to the UX, we can hold off. But, if there are only minor changes to be made, we are ok to go forward with the screens as they are.

UX for the Notifications Screen is not ready , it was suppose to be implemented this week but there has been major blocker which is Web Servers are still down. And also the the Publications Screen you require Level 1 screenshot or level 2 and 3 as well?

**Comment by Pharste** [comment]
For the notifications screen, and any other screens affected by the web services, we are ok to wait. For the article page,we will only need level 1.

**Comment by payeisa** [comment]
@Pharste Are the enhanced screens ready to go?

**Comment by ForumG-SC** [comment]
> @Pharste Are the enhanced screens ready to go?

I have updated the the latest screenshots in the google store which is under review right now. I am waiting to receive the latest screenshots for the apple store. Thanks.
