### ISSUE TITLE
Pop-ups: Cancel and confirm button (Validation)

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#141]
If we are using Pop-ups for all major issues.

Please make sure the user has the options either Cancel or Confirm. 

If the user taps confirm, then there should be a Toast message validating, the action has been completed. For instance, On the Publications screen level-2, when the user taps the heart icon, a toast message is shown and the empty heart icon changes to filled heart icon.
It is also a part of accessibility bug.

**Comment by zhuelle** [comment]
Related to App crashing.
