### ISSUE TITLE
Pop-ups and their translation in French

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#148]
Hi Steph,

As discussed, I am assigning this ticket to you for the user friendly Pop-ups and their translation in French. For reference, I am attaching the conversation.

1.	Network Errors: Oops! The internet connection appears to be offline. Please try again. CTA(Retry).
2.	Delete user profile: Suggestion. All your saved preferences will be reset and the information will be deleted.  Also, right now I think the only option we have is okay. There should be a cancel button as well just in case, the user clicks by accident. (Cannot test as the app is crashing on me.)
3.	Server down: Something is broken, it’s not you! It’s us. Please check back later. Although, there was a separate screen designed for this. We are going to use a Pop-up for the MVP

Thanks

**Comment by ForumG-SC** [comment]
@Rajat-Sen Delete user profile button will be removed before the final deployment, this button was implemented for testing purpose only.

**Comment by Pharste** [comment]
Hi, here are the pop up messages:

English: https://gcdocs.gc.ca/statcan/llisapi.dll/properties/19766135 
French: https://gcdocs.gc.ca/statcan/llisapi.dll/properties/19920916 

@Rajat-Sen We've included options for the different screens. Please advise which messages you prefer for the screens from a UX perspective. 

Regarding the delete user profile button, will we still have this option in the future to test the app before releasing new versions?

**Comment by Rajat-Sen** [comment]
Yes, we will have the option to test out the app before releasing.

**Comment by ForumG-SC** [comment]
@Pharste Please keep in mind that once the app goes into the production, we cannot have delete user profile button while doing deployment because if we do than it will show this button to all the users as the app is live in the stores.

**Comment by Rajat-Sen** [comment]
Since the Delete user profile button will be removed, let's focus only on Network errors and Server down. Also, for any other technical difficulties (just in case).

**In English**
1. Network error : Hmm… We can’t detect an Internet connection. Please check your network settings and try again.
2. Server down : Couldn’t load the (Screen-name) screen. It’s not you! It’s us. Please check back later.
3. Technical difficulties : Well, this is unexpected! We’re working to fix the problem. 

**In French**
1. Network error : Hmm… Nous ne sommes pas en mesure de détecter une connexion Internet. Veuillez vérifier vos paramètres et essayer de nouveau.
2. Server down : Nous rencontrons actuellement des difficultés techniques et n’arrivons pas à charger l’écran (Screen-name). Veuillez essayer de nouveau plus tard.
3. Technical difficulties : Eh bien, cela est inattendu! Nous travaillons à résoudre le problème.

**Comment by payeisa** [comment]
@zhuelle Can you please confirm which part of this ticket is Post MVP?

**Comment by zhuelle** [comment]
@payeisa The function has been provided and we will provide screen shots after MVP.

**Comment by payeisa** [comment]
@zhuelle So for this ticket, IT is validating that the proper text will be displayed in English and French?

**Comment by zhuelle** [comment]
@payeisa This is very good point. I think you can test Network Error fairly easily. For server down and technical difficulties, it might be a bit tricky to test. I will discuss the team to see there is a way to test them.

**Comment by payeisa** [comment]
@zhuelle I believe that's why screenshots were going to be provided to us for validation (so we don't need to actually trigger the messages).

**Comment by zhuelle** [comment]
@payeisa I discussed with the team. @Jiandong-Guo  will provide the screen shots in simulator later this week (earliest Wednesday) for you to validate as the developer is busy to complete bug tickets today to prepare for tomorrow's deployment.

**Comment by payeisa** [comment]
@zhuelle That sounds good! :)

**Comment by Jiandong-Guo** [comment]
![Screenshot_1643288645](https://user-images.githubusercontent.com/58485300/151367899-d17494db-a4c1-4c80-9ad9-3be90d945cb7.png)
![Screenshot_1643288660](https://user-images.githubusercontent.com/58485300/151367915-d93ae5bb-697a-4068-8fe6-58d76245cf25.png)
![Screenshot_1643288797](https://user-images.githubusercontent.com/58485300/151367921-21b80e22-272c-4455-99a8-f6e466fe2764.png)
![Screenshot_1643288816](https://user-images.githubusercontent.com/58485300/151367924-808a0ebd-5d2c-47f3-bf6e-d9d6e1b66292.png)

**Comment by payeisa** [comment]
@Jiandong-Guo Are these ready for review? If so, could you please assign this ticket to me? Thanks, Isabelle

**Comment by payeisa** [comment]
Validated.
