### ISSUE TITLE
Incorrect Search screen flow using accessibility controls

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#155]
With accessibility features on, the logic of the flow is not right and is creating confusion for the users.

Incorrect flow: Sort by date>Filter by subject>Newest to oldest etc.
Correct flow: Sort by date> Newest to oldest> Oldest to newest> etc.

**Comment by ForumG-SC** [comment]
@Rajat-Sen I am not sure if this was tested properly. When you have the VoiceOver on the navigation is not automatic , it is manual process. 

After clicking on sort button if you click on Filter by subject than it will work in that flow. However, after clicking on sort button , if you double click than you access the the dropdown menu options such as newest to oldest etc.

**Comment by Rajat-Sen** [comment]
When clicked on sorting and swiped from left to right, the focus should go to the drop-down items instead of filter by subject. 
Note:  You are referring to selecting an item manually and then clicking it.

**Comment by ForumG-SC** [comment]
Fixed in https://github.com/StatCan/StatcanPublicationUAT/issues/170
