### ISSUE TITLE
Recent searches not functional in French

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#157]
I'm trying to execute a search from the recent searched results, in French, but it keeps returning the "No results found" message. For example, if I search for "Train" (by manually typing it as a keyword), I will obtain 14 results. However, if i select "Train from the list of "Recherches récentes", I get no results.

By entering the keyword "Train"
![image](https://user-images.githubusercontent.com/89025704/146980996-18187967-6a11-4dbd-8947-0c57973c31b4.png)

By using "Train" from the list of "Recherches récentes":

![image](https://user-images.githubusercontent.com/89025704/146981076-e40ad838-1f35-492c-a823-fafe0cc8087d.png)

This is only an issues in French, not in English.

**Comment by Jiandong-Guo** [comment]
fixed, please test in next release

**Comment by payeisa** [comment]
Validated.
