### ISSUE TITLE
For you screen & large text

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#158]
When setting the text size to the largest possible, the display of the "For you" screen is off (in both English and French).
![image](https://user-images.githubusercontent.com/89025704/146982191-9d4bd5a3-a67f-47be-adf0-9451017c9e8b.png)

![image](https://user-images.githubusercontent.com/89025704/146982337-22f470b9-f35a-4dbf-b68b-2611f231ccac.png)

**Comment by ForumG-SC** [comment]
Done

**Comment by ForumG-SC** [comment]
Manage Subject Button Text fixed.
Heading Text Fixed.
Intro Text Fixed.
On the Saved items screen before the intro text it was displaying gray bar - fixed. 

@payeisa Please test in next release.

**Comment by payeisa** [comment]
I noticed the following issues, when setting the text to the largest setting:

For you (heading)
The "For you" screen heading seems to be smaller than the rest. 
![image](https://user-images.githubusercontent.com/89025704/148704611-ec22bb47-ab16-41ee-b3bf-0b5abd62727c.png)

For you (Following and Saved)
The text size for the "Following" and the "Saved" tabs did not increase.

Search screen
When on the Search screen, and you enter text in the search box, the instructions text overlaps in the search box:
![image](https://user-images.githubusercontent.com/89025704/148706329-e6d11576-963c-4319-a64f-99ecea73f69f.png)

Search Screen (French)
When you enter search text, the "Annuler" button doesn't fit on one line:
![image](https://user-images.githubusercontent.com/89025704/148706616-14e1998b-6f22-4dc1-b3b0-5b1956193f7e.png)


Publications level 2 screen - options menu
The "Share this publication" alignment is off:
![image](https://user-images.githubusercontent.com/89025704/148706510-bb3d26f7-d318-4878-96e5-96dd06899b95.png)

**Comment by Rajat-Sen** [comment]
Linked to #202

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Search screen (English) - largest text setting
If searching for a string of text that expands on two lines, and does not return any results, there is no space between the "Recent searches" entry and the "No results found" text.

![image](https://user-images.githubusercontent.com/89025704/150700860-700e6cec-1cfc-40e8-9ac2-a0ec103ac7fc.png)

Publications level 2 screen, in French, options menu - largest text setting
The "Partager cette publication" alignment is off:

![image](https://user-images.githubusercontent.com/89025704/150701034-16e37728-27c8-4a4d-8d21-eac61006c6c0.png)

**Comment by ForumG-SC** [comment]
@payeisa To fit it in one line because it is 3 words in French , I would have to decrease the text size and it would look like this when text size is max:

![image](https://user-images.githubusercontent.com/84411852/150828876-702f9cdc-c7e7-4afe-b943-0e4b18a1e23f.png)

**Comment by ForumG-SC** [comment]
I would have to decrease the text size for French to fix alignment issues:
This is how it would look when text size is in middle:
![image](https://user-images.githubusercontent.com/84411852/150829520-2cf178e2-8e61-4f95-ae36-5029b7ba9d9b.png)
When text size is maxed out:
![image](https://user-images.githubusercontent.com/84411852/150829591-2dc758e0-d3bb-459c-8601-30c0121bdf2d.png)

**Comment by ForumG-SC** [comment]
Space has been added between recent searches and no results found:
![image](https://user-images.githubusercontent.com/84411852/150830914-5b598d34-29ff-4acf-b668-273ab39b585b.png)

**Comment by payeisa** [comment]
Validated.
