### ISSUE TITLE
Publications icon - label

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#16]
On my phone (Samsung Galaxy S9), the label for the Publications button (in the bar at the bottom)  cuts off (not enough space).
This in not an issue on my tablet (Samsung Galaxy Tab S6 Lite).

![image](https://user-images.githubusercontent.com/89025704/131253164-943f072f-325e-4c89-9a0c-c2401a6242af.png)

**Comment by ForumG-SC** [comment]
Fixed, changes will be applied in the upcoming deployment.

**Comment by payeisa** [comment]
The button should be "Publications" (with an "s").

**Comment by ForumG-SC** [comment]
@payeisa The bug has been fixed, the changes will be deployed in the upcoming release. Requires validation, assigning it back to you.

**Comment by payeisa** [comment]
Validated Sept 25, 2021.

**Comment by payeisa** [comment]
The label for "Publications" on my tablet is still Publication" (missing an "s").
![image](https://user-images.githubusercontent.com/89025704/134887627-388fb274-8a84-48ba-b674-721bf4fd83e2.png)

**Comment by ForumG-SC** [comment]
@payeisa Try to delete the app in your tablet and reinstall it.

**Comment by payeisa** [comment]
Was able to validate after deleting and re-installing the app.
