### ISSUE TITLE
Update notifications screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#162]
Notifications - up to 25 and enhance the message to specify that it's notifications for subjects they are following.

**Comment by payeisa** [comment]
Hi, I will re-assign this one back to me because it's not ready to be assigned yet.

**Comment by payeisa** [comment]
You have no notifications! 
Note: You will receive notifications for subjects you are following and only the latest 25 notifications will be displayed on this screen.

**Comment by Pharste** [comment]
Hi, 
Here is the french translation: 

Vous n’avez pas de notifications. 
Note : Vous recevrez des notifications relatives aux sujets que vous suivez. Seules les 25 dernières notifications seront affichées à cet écran.

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
