### ISSUE TITLE
Recommendation from Consultations: Make the publication subject more evident

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#163]
Can we make the subject of publications more evident by enlarging, or darkening the text of the subject in italics? 
![subjects](https://user-images.githubusercontent.com/89025880/147275058-1e2b5cf2-3604-4e02-824f-cb6d003bea19.jpg)

**Comment by ForumG-SC** [comment]
@Pharste Yes we can enlarge them, do you want to make subject bold like the other text?

**Comment by Pharste** [comment]
@Rajat-Sen do you have a recommendation for how we should implement this?

**Comment by Rajat-Sen** [comment]
Yes, there are three ways we improve this:
1. Changing font style from italics to regular
2. Darkening the colour
3. Increasing font size

I will make the changes in the prototype and will setup a meeting to go over the recommendations from usability testing.

**Comment by Rajat-Sen** [comment]
https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/43a64204-945d-4bf4-a0b0-eedc100c4de0/

**Comment by ForumG-SC** [comment]
@Pharste Done , assigning it back to you for validation in the next release.

**Comment by Pharste** [comment]
Thank you. Validated.
