### ISSUE TITLE
Recommendation from consultations: Lengthen the amount of time that the message displays on the screen when an article is liked.

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#164]
Can we lengthen the time the "Added to saved items on For you" message is displayed for
![added to saved items](https://user-images.githubusercontent.com/89025880/147275571-4ad85dfe-dfca-4492-95da-fc17b269a022.png)
?

**Comment by ForumG-SC** [comment]
@Pharste Yes it is possible to lengthen the time, currently we have set 2 seconds of time, please let me know if you want to replace 2 seconds by ... ??

**Comment by Pharste** [comment]
@Rajat-Sen Do you have a recommended time for this message? I think doubling the time would be sufficient, but if you have another suggestion, please provide input.

**Comment by Rajat-Sen** [comment]
The default timing for a short toast message is 2 seconds and the maximum is 3.5 seconds. Let's go with maximum of 3.5 seconds.

**Comment by ForumG-SC** [comment]
Done

**Comment by Pharste** [comment]
Validated, thank you
