### ISSUE TITLE
Recommendation from consultations: replace radio buttons with checkboxes for "Filter by subject(s)" menu

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#165]
The checkboxes on the "Filter by subject(s)" menu appear to be radio buttons and should be replaced with checkboxes (but rounded edges).

**Comment by Rajat-Sen** [comment]
I will update the design in the prototype for reference and will paste the link here.

**Comment by Rajat-Sen** [comment]
https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/43a64204-945d-4bf4-a0b0-eedc100c4de0/

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please provide the assets (option checked png file)

**Comment by ForumG-SC** [comment]
@Pharste Done , assigning it back to you for validation in the next release.

**Comment by Pharste** [comment]
Validated
