### ISSUE TITLE
For you - Manage subjects (three dots)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#166]
Would it be possible to enhance the design of the "Manage subjects" button/menu item that gets displayed when the user selects the three dots - Manage subjects. Right now, it looks like a simple label that gets displayed below the "Saved" tab.

![image](https://user-images.githubusercontent.com/89025704/147290247-90a8020f-4ad4-41a8-8738-9dfd3009142a.png)

**Comment by Rajat-Sen** [comment]
Yes, I will update the design as per usability testing as well!

**Comment by Rajat-Sen** [comment]
This is the link for the new prototype as per usability recommendations. Please refer to the placing of the menu item.

https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
