### ISSUE TITLE
Remove 'return' button from notifications menu?

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#167]
I noticed there's a return button appearing in the menu on the notifications screen: 
![Notifications menu](https://user-images.githubusercontent.com/89025880/147290355-64bc62ae-b7be-4a09-a664-b963d0077024.png)

Was this added for accessibility, or can it be removed?

**Comment by ForumG-SC** [comment]
@Pharste UX implementation of the notification screen is still not done, the option will be removed when ux is completed for this screen.

**Comment by Pharste** [comment]
@ForumG-SC Ok, thank you!
