### ISSUE TITLE
Earlier today section on Publications screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#168]

**Comment by payeisa** [comment]
We have never seen the "Earlier today" section on the Publications screen. We only ever see the "Latest content" and "Date". Can we please investigate why that is?

**Comment by Jiandong-Guo** [comment]
It only shows in the current day afternoon and after there is a new released in this afternoon and current time is after the release time.
Please test again and let me the result

**Comment by payeisa** [comment]
Unable to validate due to API issue.

**Comment by payeisa** [comment]
Requirements to be reviewed after launch.

**Comment by goodyke** [comment]
@payeisa please publish an article in production after 12pm today so that we can verify if this bug still exists now that the caching seems to be resolved.  It would help if you let us know the time and the article id once booked.

**Comment by payeisa** [comment]
@goodyke The article "Off to hit the...slopes" will be published at 2:00 p.m. today.

**Comment by goodyke** [comment]
Thanks Isabelle! :-)

**Comment by goodyke** [comment]
I verified in the mobile application at 2:15pm today and the "Off to hit the... slopes' article is showing up under the 'Latest' grouping as expected.
However, all the articles that were posted earlier this morning remain under the 'Latest' grouping as well when a separate grouping should be shown for these with the label 'Earlier today'.

**Comment by Jiandong-Guo** [comment]
Please test the "Early today" in next release, also click "Grouping test" button in setting screen to test the algorithm.

**Comment by payeisa** [comment]
Validated that the "Latest" and "earlier today" sections were updated at 2:00 p.m. when a StatsCAN Plus article was published at 2:00p.m. I will be able to close this ticket after validating the behaviour tomorrow morning, when new content is published.

**Comment by payeisa** [comment]
Validated.
