### ISSUE TITLE
Text size ratio (tablet vs phone)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#17]
The text size ratio seems to be inconsistent when viewed on my tablet (Samsung Galaxy S6 Lite). For example, the size of the buttons in the menu at the bottom (Publications, Search, For You and Settings), seems big when compared to the text on the screen.

**When viewed on tablet (the text size for the buttons is much bigger than the text within the article)
![image](https://user-images.githubusercontent.com/89025704/131253572-615d12c9-eb1d-41a8-b81c-f5c421bd5d28.png)

When viewed on phone (the text size for the buttons seems to be consistent with the text size of the article)
![image](https://user-images.githubusercontent.com/89025704/131253560-d2aafe00-4149-4ac0-98f6-5eef00fb1ced.png)

Same applies to the text on the Settings screen.

**Comment by ForumG-SC** [comment]
Fixed, changes will be applied in the upcoming deployment.

**Comment by payeisa** [comment]
Validated Sept 22, 2021.
