### ISSUE TITLE
Functionality for Publications Level 2 Screen: Share this publication

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#170]
The functionality of the "Share this publication" button/menu item should be based on the requirements of Feature 3.3:
https://confluence.statcan.ca/display/SPMA/Feature+3.3+Share+article

**Comment by Jiandong-Guo** [comment]
Currently, when clicking the "Share this publication", it will trigger the social media pop-up which is listed in Feature 3.3.
What is the exact requirement to fix ?

**Comment by Rajat-Sen** [comment]
Hi Jiandong, when the user clicks on Share this publication, the user is presented with certain options and they should work like in the Photos attached to the confluence page.
1. For email (The message in the body and the links should be in separate lines)
     The subject should be: "Interesting publication from StatsCan / Publication intéressante de StatsCan"
     Body: "Check it out / Jetez-y un coup d'oeil"
     Also, it should have the link for Google and iOS store pages of the app.

2. For any social media (The message in the body and the links should be in separate lines)
     The message should have text "Interesting publication from StatsCan / Publication intéressante de StatsCan"
     And the link for the article.

3. For messages (The message in the body and the links should be in separate lines)
     The message should have text "Interesting publication from StatsCan / Publication intéressante de StatsCan"
     And the link for the article.
    
Please let me know if you have any concerns or you can check out the confluence page. Thanks!

https://confluence.statcan.ca/display/SPMA/Feature+3.3+Share+article

**Comment by Jiandong-Guo** [comment]
I think it's done by Forum long time ago

**Comment by Rajat-Sen** [comment]
Yes, but it is not working as it should be.

**Comment by Jiandong-Guo** [comment]
see #212,#232

**Comment by goodyke** [comment]
@Rajat-Sen should this bug be fixed with the next deployment (as a result of Jiandong completing #212 and #232)? If so then I can close this ticket as done and we can test after the next deployment.

**Comment by Rajat-Sen** [comment]
@goodyke Please move this ticket, to done as they were linked.
