### ISSUE TITLE
Settings - Help & FAQs

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#171]
English & French:
The email address for Infostats should be changed from "STATCAN.infostats-infostats.STATCAN@canada.ca" to "infostats@statcan.gc.ca"

English:
The heading "Help & FAQs" shoul dbe changed to "Help & FAQ"
In the Support section, "FAQs" should be changed to "FAQ"

![image](https://user-images.githubusercontent.com/89025704/147677022-bdb1464a-f45d-424f-a020-0e9be88d7211.png)

French:
The heading "Email" should be changed to "Courriel"
"Envoyer un e-mail" should be changed to "Envoyer un courriel"
"Copier l'adresse courriel" should be changed to "Copied l'adresse de courriel"
In the "Soutien" section, "FAQs" should be changed to "FAQ"

![image](https://user-images.githubusercontent.com/89025704/147677007-1c217a20-2d35-4013-87d7-f80621e45d93.png)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Apologies - I made a typo:
French: "Copier l'adresse courriel" should be changed to "Copier l'adresse de courriel" ("Copied" should be changed to "Copier")

In English, in the "Telephone" section, can we remove the brackets from the words (Toll free) and (International) and format them like this instead:

Toll-free: 1-800-263-1136
International: 1-514-283-8300

In French, in the "Téléphone" section, can we remove the brackets from the words (sans frais) and (international) and format them like this instead:

Sans frais : 1-800-263-1136
International : 1-514-283-8300

In English, in the Regular business hours section, can we change the formatting to:
Monday to Friday from 8:30 a.m. to 4:30 p.m. (except holidays)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
All looks good, except for this one:

In French, in the "Téléphone" section:

Sans frais : 1-800-263-1136
International : 1-514-283-8300

There should be a space before and after the semi-colons:

![image](https://user-images.githubusercontent.com/89025704/149685646-071c7c70-f8bf-41c7-9dfe-173bb86d678f.png)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Settings - Help and FAQ
If I select the " Send email" option, the email address that gets automatically populated in the "To" field of the email should be "infostats@statcan.gc.ca"

**Comment by ForumG-SC** [comment]
> infostats@statcan.gc.ca

Fixed

**Comment by payeisa** [comment]
Validated.
