### ISSUE TITLE
If the server is down, all the screens will display an image of 404 and retry button.

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#172]
How can business test/validate this feature?

**Comment by Rajat-Sen** [comment]
As per conversation with Forum, it would be best that the devs can provide screenshots for the 404 screens.

**Comment by Rajat-Sen** [comment]
Can we close this ticket as the dev team can provide screenshots incase the servers are down?

**Comment by payeisa** [comment]
Yes - we can validate with screenshots, no problem.
