### ISSUE TITLE
English content not refreshing in app (Publications screen)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#173]
The English Publications screen is not displaying the latest content. These are the Dec 23 articles:
![image](https://user-images.githubusercontent.com/89025704/147748162-a770062b-4324-4f20-8b7b-857ac39213b4.png)

However, French is displaying the latest (Dec 24 articles):
![image](https://user-images.githubusercontent.com/89025704/147748207-5c364958-df91-4dd5-aede-be8cd0b79dbf.png)

I'm able to search/access the Dec 24 articles in English by searching for them, they are simply not showing up on the Publ;ications screen and the refresh function isn't working.

**Comment by ForumG-SC** [comment]
@payeisa This seems to be issue on the alpha server side, we would have to wait for Dave to be back to look into this.

**Comment by payeisa** [comment]
Update: I republished the "Cookie for all this weekend", "Telework is changing the way we use transit" and the "Episode 2: Unravelling: Impacts of COVID-19 on Canadian families" because the images were blurry. The issue has been resolved on the Search screen (images look good), but they are still blurry on the Publications screen.

**Comment by ForumG-SC** [comment]
@payeisa It is working on Search screen because the api is using different request compared to the publications screen. There seems to be issue on the backend with a particular request that is getting send from the publications screen resulting in not refreshing the content.

**Comment by Rajat-Sen** [comment]
Also, the app is acting weird. When the user opens up the app for the very first time, the user can scroll through the publications easily without selecting any article. However, if the user selects an article, the publications screen would not scroll down beyond a particular date. 

Additionally, when scrolling if the user selects and article and goes back to the publications scree. It would not remember the scroll position and have to start scrolling again from the top.

**Comment by ForumG-SC** [comment]
Temporary parameter to add in the Pubs screen to disable blue image : https://sdr-daily-alpha.cloud.statcan.ca/o1/en/api/plus/article?published_after=2021-11-09&page=0&cache=asdjlasdjkad

**Comment by ForumG-SC** [comment]
@payeisa Temporary fix has been applied , doing another deployment. You can validate and close the ticket.

**Comment by payeisa** [comment]
Validated.
