### ISSUE TITLE
English content in French interface: For you screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#174]
English content is being displayed in the French interface (Pour vous - Éléments enregistrés - Labour Force Survey):
![image](https://user-images.githubusercontent.com/89025704/147749262-57df3138-4543-4d31-b16a-c4b8119bada3.png)

I can confirm that the article is in fact loaded in both English and French in ORPS:
![image](https://user-images.githubusercontent.com/89025704/147749313-1bf59d99-a47c-45ab-bae1-43c891da9d17.png)

If I search for that same article (Enquête sur la population active), it's displayed in French in the search results.
It is also displayed in French on the Publications screen.

**Comment by ForumG-SC** [comment]
Fixed, ready to test in next release.

**Comment by payeisa** [comment]
The Labour Force Survey article displays properly, however, now the "Wholesale trade : Early indicator, November 2021" article is displaying in English, on the French "Pour vous / Éléments sauvegardés" screen.

![image](https://user-images.githubusercontent.com/89025704/148707233-bfc22512-d8a1-4aaa-8878-168c5c3d0da4.png)

**Comment by Jiandong-Guo** [comment]
![Screenshot_1642085519](https://user-images.githubusercontent.com/58485300/149352936-bdd1559b-8a20-4e33-a8f3-f3e3d62bf119.png)
I saw that is in French, please test it in next release and let me know the result

**Comment by payeisa** [comment]
Validated.
