### ISSUE TITLE
New title required for level 2 of publications screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#176]
This ticket will be to brainstorm ideas until a heading is decided on to distinguish the home page publications screen from level 2 publications. @Rajat-Sen @payeisa

**Comment by Pharste** [comment]
To consider for level 2: Publications view

**Comment by payeisa** [comment]
Other options:
a) According to Google, we are not displaying the source of the data/publisher and/or our website address. Could we simply display "Statistics Canada (www.statcan.gc.ca) as the heading? (this idea was inspired by BBC - who also displays their website address). In frnch it would be "Statistique Canada (www.statcan.gc.ca)".

b) Leave the heading blank (I'm not sure if we "have" to have a heading? i.e. Ottawa Citizen, theScore, The Washington Post, Breaking News and CNN don't have one when you navigate to the article view).

**Comment by Rajat-Sen** [comment]
The title for the screen has been finalized "Publications view". Will update the translation in French later on.

**Comment by Pharste** [comment]
Since 'publications view' is too long in French, the new title for level 2 should be 'Publication'.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please confirm the title ,according to my understanding from the comments, I will be updating title as follow:
EN - Publication View
FR - Publication 
is that correct?

**Comment by Rajat-Sen** [comment]
@ForumG-SC, In English and French, it should be "Publication".

**Comment by ForumG-SC** [comment]
Done

**Comment by Pharste** [comment]
validated
