### ISSUE TITLE
Canada wordmark in white Color

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#179]
In dark mode, on the settings screen at the bottom the Canada wordmark needs to be in white colour and in light mode, it should stay in black colour.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please provide with white color Canada Wordmark for the dark mode , thanks.

**Comment by Rajat-Sen** [comment]
Hi Forum, please find the image attached. Thanks!
![Canada_wordmark_White](https://user-images.githubusercontent.com/38566088/148283203-d69b2caa-045b-49dd-be3a-1acb2bab6cf8.png)

**Comment by ForumG-SC** [comment]
Done
