### ISSUE TITLE
Settings - Language

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#18]
***I'm not sure if this screen was ready for testing, or not but based on prototype design***

The screen title should be centered.

The options labels should be:

When in English:
English
Français

When in French:
Français
English

Once an option is selected, it should be marked as a checkmark in a bubble.
There should also be a note, below the language options "Changing the language may restart the app".
Screen should have a blue background.

**Comment by ForumG-SC** [comment]
@payeisa Please revalidate , thanks.

**Comment by payeisa** [comment]
Validated.
