### ISSUE TITLE
System settings not matching with app

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#181]
Upon testing, the app does switch to dark mode with the system. I think it has been set to a particular time. This can also be tested by turning the dark mode ON of the device at all times. 

Also, if the user selects the dark mode only within the app. It does not change the colour of status bar.

**Comment by Rajat-Sen** [comment]
Linked to #210

**Comment by goodyke** [comment]
@Jiandong-Guo we will get back to you by the end of the day with the client decision about the dark mode tickets.

**Comment by zhuelle** [comment]
@Jiandong-Guo please do not work on this ticket this weekend.
@payeisa, Rajat, Kerry and I discussed this ticket. This is a complex issue and requires time to fix it properly. In the nutshell, the app is not synchronizing the mode change with the device system setting in the run time. Given the time constraints, we recommend to leave this issue outside of MVP release but put it as a priority bug fix after MVP.

**Comment by zhuelle** [comment]
@AJBouzidi , as discussed in the virtual stand-up, this ticket requires dev team's research, please provide your comments if required and  assign it to a developer. Thanks!

**Comment by zhuelle** [comment]
We discussed in the virtual Standup meeting and current the app is doing:

- After first time installing the app, the app uses the system setting to determine the Dark/Light mode for the app
- After first time installation, the app uses the application setting to determine the Dark/Light mode for the app
- If the user is selected the Auto mode in the app, the app uses the system setting to determine the Dark/Light mode for the app

The app is behaving as designed. 

@Rajat-Sen assign back to you for your verification.

**Comment by Rajat-Sen** [comment]
@zhuelle, This ticket is not working as intended. I will reframe this again.

This ticket is divided into two categories:
1. Auto: When the app's colour theme is set to Auto. It should follow the OS settings. For instance, when my device is in light mode and I open the app, it should open the app in Light mode. And, when I change the OS colour mode to dark, it should instantly change the app to dark mode. Rather than closing the app and opening it back again.

2. Light/Dark mode: When in the app itself, is selected in Light/ Dark mode. It should override the system settings respectively. 

Thanks!

**Comment by zhuelle** [comment]
@payeisa and @weglmar 
We discussed this ticket during our IT daily stand-up. The developer is researching to find a solution to resolve the following issue:
When the app is set up as Auto in the Color Theme setting, if the user changes the OS Color Theme setting from Light to Dark, the app does not change to the Dark mode immediately if the app is open or during run-time. The app is going to pick up the Color Theme change (in the case, the Dark mode) when the user launches the app the next time.  
The developer has estimated the effort level as Large. I would like to inform you about this ticket to align the business value and expectation of the ticket. Please let me know if you have any questions.

**Comment by Jiandong-Guo** [comment]
@ForumG-SC ,When I run master it shows
![image](https://user-images.githubusercontent.com/58485300/181781843-ecead09a-64c7-4a6d-96ef-ff03b401e35e.png)
Which version of expo-cli are you using ?

**Comment by ForumG-SC** [comment]
> @ForumG-SC ,When I run master it shows ![image](https://user-images.githubusercontent.com/58485300/181781843-ecead09a-64c7-4a6d-96ef-ff03b401e35e.png) Which version of expo-cli are you using ?

@Jiandong-Guo Hi Jiandong, In the pull request...I don't think you need to add yarn-error log file, it is not needed. The reason why after adding app.json it is not running because you have missing package, just run the command : expo install expo-build-properties , it will add the package and error will be resolved.
![image](https://user-images.githubusercontent.com/84411852/181780543-3b8732f8-b7fe-4757-bd57-ff58285535eb.png)

**Comment by Rajat-Sen** [comment]
Not working!

**Comment by zhuelle** [comment]
@Rajat-Sen this ticket has not been released yet as it didn't make to the last release :) 

BTW, on the Release board, if you see a ticket in "Require IT testing" category and assigned to you but the Version column is empty, this means the ticket has not been released yet. Once it is released, the developer who is doing the release will manually put a version number in the field.

**Comment by Rajat-Sen** [comment]
Validated!
