### ISSUE TITLE
Publications description link

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#189]
When using voiceover, 
If there is a link in the paragraph, it should highlight and read the whole paragraph as whole and after it reads a link it should say link and continue reading.

**Comment by Jiandong-Guo** [comment]
What we can do is enhancing the html, we have no control of the voice over on web page,
Try again to see if there is any improvement in next release

**Comment by Rajat-Sen** [comment]
For the time being, I am closing this ticket as it is better than before but, not perfect.
