### ISSUE TITLE
UX: Manage all notifications screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#19]
-	The plus button for number of notifications is cut off 
-	The formatting of the on/off slider buttons are off—they overlay with the text for each option.
-	When both in-app notifications/push notifications are turned off, I think the notification type options at the bottom of the screen should automatically switch off. This didn’t happen for me when testing. 

Publications Screen – level 1 notifications:
-	This functions well, but the full article does not show when clicked on from the notification. (Not sure if this is supposed to be fully functional at this point in development. 😊)

**Comment by ForumG-SC** [comment]
@Pharste  Publications Screen – level 1 notifications: This is not functional that is why it does not display full article content, only ux was implemented.   😊

**Comment by Pharste** [comment]
Ok, thanks for the clarification!
