### ISSUE TITLE
French translations updated

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#190]
There are some changes need to be done before Final release.
[Master list of terms.xlsx](https://github.com/StatCan/StatcanPublicationUAT/files/7824923/Master.list.of.terms.xlsx)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
@Pharste Can you please validate?

**Comment by Pharste** [comment]
Hi, 

I've reviewed the translations and have some notes: 

**Notifications screen menu:**
![Notifications menu FR](https://user-images.githubusercontent.com/89025880/149834448-410cb3b3-1ce8-49ee-8e59-335d8467cdd0.jpg)

- FR: Change 'Paramètre de notification' to 'Paramètres de notification'


**Publications menu:**
![Publications menu FR](https://user-images.githubusercontent.com/89025880/149955529-24b12c2f-43bb-444a-a4f5-bc17c1a43f27.jpg)


**Saved pop-up:**
- in English, change to
Remove publication
Would you like to remove this item?
Remove | Cancel

- In French, change to 
Supprimer la publication
Voulez-vous supprimer cet article?
Supprimer | Annuler




**Settings**
- Please update the 'Terms of use' title in the settings to 'Terms of Use' (English only)
- Please update "Communiquez avec nous" to "Contactez-nous" (Sorry, this was something brought up from the comparative review, but contactez-nous is consistent with the StatCan website.)
![Settings FR](https://user-images.githubusercontent.com/89025880/149955503-cc5e2f83-caa6-49db-b223-e18a4627bafe.jpg)

- please update "Élément copié sur le presse-papiers" to "Élément copié dans le presse-papiers"
- there should be a space before ':' with "Sans frais" and "international"
![copied to clip FR](https://user-images.githubusercontent.com/89025880/149959259-3efb9815-fd56-414a-bdf6-3bf57eb5f826.jpg)

**Comment by Pharste** [comment]
@ForumG-SC it should be changed in the settings and the level 2 drop down menu

**Comment by ForumG-SC** [comment]
Done

**Comment by Pharste** [comment]
validated
