### ISSUE TITLE
Unfollow functionality not working

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#192]
After clicking unfollow button on the see all screen in the for you tab the subject doesn't get unfollow.

**Comment by Jiandong-Guo** [comment]
No problem with the unfollowing function, potential issue is the api returns a list with items not belong to requested subject_id,
same issue with #195.

**Comment by Jiandong-Guo** [comment]
As discussed on the meeting, no change on mobile side, please waiting for the api change and then test again

**Comment by payeisa** [comment]
Assigning to Forum for validation.

**Comment by Jiandong-Guo** [comment]
In alpha, the new release is for alpha
