### ISSUE TITLE
Text prompt for "Unfollow"

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#196]
Can we please modify the text that gets displayed when I want to unfollow a subject? 

In English, can we please change from "Unfollow (insert subject name)" to "Unfollow the subject (insert subject name)"
In French, can we please change from "Ne plus suivre (insert subject name)" to "Ne plus suivre le sujet (insert subject name)".

This will avoid things like "Unfollow government" and "Unfollow Indigenous peoples".

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
