### ISSUE TITLE
Settings/Help & FAQ: Translation to validate 

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#197]
Hi Steph - I added a new term in the [Master list](https://gcdocs.gc.ca/statcan/llisapi.dll/properties/17829029?func=ll&objId=17829029&objAction=properties&nexturl=%2Fstatcan%2Fllisapi%2Edll%2Fproperties%2F17829029) (see line 112 in green). Can you please validate it with ES (comparative review)? It was not part of the list (since it's relatively new)

It's the toast message that gets displayed when the user goes to Settings / Support and feedback / Help and FAQ / Copy email address

**Comment by Pharste** [comment]
The file's been updated with the correct translation -- " Élément copié dans le presse-papiers"

**Comment by ForumG-SC** [comment]
> The file's been updated with the correct translation -- " Élément copié dans le presse-papiers"

Updated.

**Comment by Pharste** [comment]
validated
