### ISSUE TITLE
App opening in English after onboarding in French and setting device language to French

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#198]
I set my device's language to "French", I went through the onboarding in French.
Closed the app.
When I return, the app opens in English.

![image](https://user-images.githubusercontent.com/89025704/148708442-c3d51628-8969-4be5-b5dd-fb33d805a851.png)

**Comment by Jiandong-Guo** [comment]
Fixed, Please test in next release

**Comment by payeisa** [comment]
Validated.
