### ISSUE TITLE
Publications screen: Pull down to refresh

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#199]
We used to be able to pull down on the Publications screen to refresh the content, but that option no longer seems to be available. Has the option been removed?

@Pharste FYI

**Comment by Rajat-Sen** [comment]
I don't think, it has been implemented before. But, I will update you if it could be done before the final release.

**Comment by payeisa** [comment]
Thanks Rajat! Steph and I can confirm that we used to be able to pull down to refresh the home page :)

**Comment by payeisa** [comment]
Validated!
