### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#20]
There is a white border around the second level- display article content, and at the top of the screen in the first level- display list of articles.

**Comment by ForumG-SC** [comment]
@Pharste  Do you mean the header is white ?

**Comment by ForumG-SC** [comment]
Fixed, the changed will be deployed in the upcoming release.

**Comment by payeisa** [comment]
@Pharste Can you please validate, and close if the issue has been fixed?

**Comment by Pharste** [comment]
The issue has been fixed. Thanks!
