### ISSUE TITLE
Publications screen: max char for the subjects

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#200]
What's the character limitation for subjects on the Publications screen? Is there a way we can expand it to avoid truncation?

![image](https://user-images.githubusercontent.com/89025704/148708824-cf2b5b9a-da22-4835-92ee-52e100bcdfed.png)

**Comment by ForumG-SC** [comment]
Related to https://github.com/StatCan/StatcanPublicationUAT/issues/182

**Comment by Rajat-Sen** [comment]
Also, it is related to #163. I have updated the prototype and the font size has been increased for the subject.

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
