### ISSUE TITLE
Search screen bugs

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#203]
List of Search screen bugs.

1. When the user comes on search screen for the first time, the decoration image should be embedded and not clickable.
2. When the user clicks on Search bar, it should show cancel button at the same time to get out of focus from search functionality. (NA for MVP.)
3. The placeholder text for Search Bar, is missing "Search StatsCan publications".
4. When the user is typing and the input text increases than the width of search bar, it starts moving the clear icon and it goes beyond the viewport. Thus, the position of the clear icon should be fixed and the text from beginning could disappear. 
5. When the user searches for a keyword and click on filter by subject. (Please follow the prototype)
    a) On Android, it opens up a screen on top of everything which is okay but, nothing behind that should be clearly visible.
    b) on iOS, it opens up a screen on top of everything and if the subject list is too short it overlaps with the top navigation bar and it becomes hard to close.  

Please find the images attached for reference.

When using accessibility:
1. The should be no focus on search icon as it is for decoration purpose only inside search field.
2. When clicked on Sort it should say "Sort" identify as  "Dropdown. Expandable" > "Double tap to activate". And then, when swiped from left to right the focus should go to Newest to Oldest > Oldest to Newest > Filter by subject(s)

![IMG_5343](https://user-images.githubusercontent.com/38566088/148837408-fd7321f8-129a-42e9-9e14-166ff160ea5f.PNG)
![IMG_5344](https://user-images.githubusercontent.com/38566088/148837429-ac26cf6b-8f9c-4f1a-9c4c-5e9befbfd21c.PNG)
.

**Comment by Rajat-Sen** [comment]
Hi Jiandong, I updated the comment as the placeholder text is missing in the Search Bar itself.

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by Rajat-Sen** [comment]
Validated!
