### ISSUE TITLE
Terms & Conditions Language toggle

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#208]
When testing on iPad (pro, 12.9 inch), I found that toggling to French from the terms of use screen, and then clicking Annuler returns me to the English Welcome screen. I was able to replicate the issue several times on the iPad, but have not been able to recreate the issue on my iPhone.

**Comment by Rajat-Sen** [comment]
@Pharste I cannot replicate this issue on my iPad, with the software version, could you confirm the app version number on your iPad? Thanks!

**Comment by Pharste** [comment]
The software version is 14.6

**Comment by Rajat-Sen** [comment]
Hi Steph, are you able to still replicate this issue?

Also, could you try removing the app from your device and install again?

**Comment by Pharste** [comment]
Hi, 

I've tried to replicate the issue and it seems to be fixed. I've uninstalled the app and reinstalled. 
Thanks!
