### ISSUE TITLE
Subject overlapping title on Publications page (iPad 12.9 inch)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#209]
On the publications page, the subject is overlapping the publications title:
![ipad publications](https://user-images.githubusercontent.com/89025880/149046299-2746bcd1-20eb-4487-928d-4e675c8996c1.png)

**Comment by Rajat-Sen** [comment]
This issue is related to ticket #202.
I am attaching this image under that ticket.

**Comment by ForumG-SC** [comment]
@Pharste Fixed

**Comment by Pharste** [comment]
Validated
