### ISSUE TITLE
Third-level article content

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#21]
-	After closing the in-app browser, I was directed back to the terms and conditions screen. This didn’t always happen, but it happened a handful of times.  
-	After navigating to different pages with the in-app browser, the arrows at the bottom of the screen stopped working for me. Again, this didn't happen every time but glitched a handful of times.

**Comment by ForumG-SC** [comment]
@Pharste  Navigation has been fixed and the changes will be deployed in the upcoming release.

**Comment by ForumG-SC** [comment]
@Pharste  The Navigation buttons in the bottom .... If you click on back button( < ) when you land on that screen it won't work because you did not clicked anywhere in the browser to go back ..  To test the button correctly , when you land on the browser you have to click on some options to navigate forward after that you click on back button( < ) and forward buttons it will work.

**Comment by ForumG-SC** [comment]
@Pharste 
https://user-images.githubusercontent.com/84411852/132721769-94e527d3-a7f1-46c1-a4a4-4591e1376a1e.mp4

**Comment by Pharste** [comment]
To clarify- I tested the back buttons by navigating elsewhere in the browser (ahead 3 screens and then back). It was not always responsive

**Comment by ForumG-SC** [comment]
@Pharste To further investigate, will it be possible for you to share screen recording of the issue ?

**Comment by ForumG-SC** [comment]
https://user-images.githubusercontent.com/84411852/132725263-9419ab10-5d2c-407f-858e-971c1ab02bd2.mp4

I navigated 3 times ahead and than clicked on back , it worked ..  @Pharste

**Comment by ForumG-SC** [comment]
https://user-images.githubusercontent.com/84411852/132725712-eee65a29-2c2b-4eb2-9d65-1b8090dd2e8b.mp4

@Pharste  I tested in other link also navigated 3 times to front than clicked on back button , it worked

**Comment by Pharste** [comment]
After closing and reopening the app to test, I wasn't able to duplicate the issue. Thanks!

**Comment by ForumG-SC** [comment]
> After closing and reopening the app to test, I wasn't able to duplicate the issue. Thanks!

No Problem. 😊
