### ISSUE TITLE
Dark mode search bar appearing in light mode (iPad)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#210]
The search bar is showing in the dark theme (despite switching back and forth from mode, and exiting the app). This is only happening for me on the iPad. 
![dark search bar](https://user-images.githubusercontent.com/89025880/149047561-2b0ef0b8-b171-4ee7-b5cf-7ae49df9a549.png)

**Comment by Rajat-Sen** [comment]
@Pharste, I cannot replicate this issue on my iPad, could you confirm what's the software version for your iPad? 
You can find it under settings>General>About. Thanks!

**Comment by Pharste** [comment]
Software version is 14.6

**Comment by Pharste** [comment]
Hi @Rajat-Sen  This is still happening with the software update on my iPad, and after removing and reinstalling the app. Adeeba is also seeing the dark search bar on her iPhone 11, with iOS 15.1

**Comment by Rajat-Sen** [comment]
Got the problem,

It happens when the device is in Dark mode and the app is in Set in Light mode. Since, Search bar is a native element and that's why it appears in Dark mode.

**Comment by goodyke** [comment]
@Jiandong-Guo we will get back to you by the end of the day with the client decision about the dark mode tickets.

**Comment by zhuelle** [comment]
@Jiandong-Guo please do not work on this ticket this weekend. 
@payeisa,  Rajat, Kerry and I discussed this ticket. This is a complex issue and requires time to fix it properly. In the nutshell, the app is not synchronizing the mode change with the device system setting in the run time. Given the time constraints, we recommend to leave this issue outside of MVP release but put it as a priority bug fix after MVP.

**Comment by zhuelle** [comment]
@Jiandong-Guo , just let you know that we discussed this ticket with the clients and we found a solution for this one. @Rajat-Sen is going to select a color for the search bar so that it works for both Light and Dark mode. Once Rajat has the color, he will assign this ticket back to you so you can complete it during this weekend. Thanks!

**Comment by goodyke** [comment]
Sorry @Rajat-Sen I updated this ticket by mistake (I have fixed it now and updated #210 as discussed)

**Comment by ForumG-SC** [comment]
@Rajat-Sen  No need for the new color for search bar as I have fixed the issue.

@Pharste Assigning it back to you for validation.

**Comment by Pharste** [comment]
Validated, thank you!
