### ISSUE TITLE
Search screen: 404 message displayed when searching with recent search

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#211]
If I select a value from my recent searches, I'm presented with the 404 message.

![image](https://user-images.githubusercontent.com/89025704/149050159-f66ec411-44d2-4a46-85f4-30791e95a6a8.png)

**Comment by Rajat-Sen** [comment]
@payeisa Please confirm; this issue seems to exist only when the user has selected French language. I cannot replicate this issue in English language.

**Comment by payeisa** [comment]
@Rajat-Sen That's correct - I was in the French interface. Thanks, Isabelle

**Comment by Rajat-Sen** [comment]
I think this ticket is related to #157

**Comment by Jiandong-Guo** [comment]
fixed, please test in next release

**Comment by Rajat-Sen** [comment]
Validated!
