### ISSUE TITLE
Edit manage subjects text (En)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#213]
In English, there shouldn't be a space between the ':' and 'Select the subjects you wish to follow' from the Manage subjects screen
![Manage subjects](https://user-images.githubusercontent.com/89025880/149052650-ba439b6a-1290-4ccd-aff3-558d8a8b3cb4.jpg)
.

**Comment by ForumG-SC** [comment]
@Pharste Duplicate ticket, related to https://github.com/StatCan/StatcanPublicationUAT/issues/78
