### ISSUE TITLE
Notifications not marking as read

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#216]
When an individual notification is selected, it doesn't mark as read consistently, or takes time to remove the red dot. I noticed that after navigating back and forth it will clear after a few screen switches. 

The 'mark all as read' button isn't clearing the red dots from the publications list.

**Comment by Rajat-Sen** [comment]
Hi @Jiandong-Guo, this ticket is related to ticket number #175 on StatCanPublications repo. 

Please take a look into this and make sure it should be functioning properly as specified on the confluence page. Thanks!

**Comment by Jiandong-Guo** [comment]
fixed, please test in next release

**Comment by Pharste** [comment]
Hi, This seems to be working now, but I noticed that the no notifications screen seems to be lagging and showing up while publications are loading:

https://user-images.githubusercontent.com/89025880/150421809-1c02d3a8-244e-4aa7-a6e6-cbf01cc6ea91.mov

**Comment by Rajat-Sen** [comment]
I am closing this ticket for now, as it is working. I tested it by closing the app and going back and forth between different screens.
