### ISSUE TITLE
Search: Filter by Subjects 

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#218]
The Filter by subject(s) menu is displaying too high on the screen, and I'm unable to close the pop-up without hitting 'Apply'
![Filter by subjects list](https://user-images.githubusercontent.com/89025880/149260373-16454bc9-361a-435c-a0ac-48b423b47b5f.jpg)
.

**Comment by Pharste** [comment]
@Rajat-Sen The subjects list is displaying properly now, but the apply button is not showing. (light mode only). I noticed this today on my iPad and Adeeba noticed it with her Apple iPhone 11 (I'll confirm what software).

![No apply ipad](https://user-images.githubusercontent.com/89025880/149824907-603e2526-1a03-4ddf-a1bb-6d3e4dac2675.jpg)
![no apply iphone](https://user-images.githubusercontent.com/89025880/149824924-8b25a5a0-ab50-4df1-b5d4-79c19f671c5c.png)

**Comment by Pharste** [comment]
Hi @Rajat-Sen  I've validated that the subjects list is displaying properly on the screen, but the apply button is still not showing in light mode on iPad.

**Comment by Rajat-Sen** [comment]
@ForumG-SC, This is same as search screen input field bug, the colour needs to be changed when the system OS is in Dark mode and the app is switched to light mode.

**Comment by ForumG-SC** [comment]
Fixed

**Comment by Pharste** [comment]
Validated, thanks!
