### ISSUE TITLE
No results found image not disappearing from search screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#219]
After entering an invalid term and hitting cancel, then navigating away from the search page, and then back to the Search screen, the ‘No results found’ is still displaying for me.

Is this the expected behavior, or should this refresh to a blank screen
![5](https://user-images.githubusercontent.com/89025880/149263841-0c8b7958-2e18-44ab-9d66-2ab1bad64f0f.jpg)
?

**Comment by Jiandong-Guo** [comment]
Fixed please test it in next release

**Comment by Pharste** [comment]
Validated, thank you
