### ISSUE TITLE
Second-level article content

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#22]
-	When scrolling down to view more articles on this page, the ‘Earlier today’ text has no background, and appears over the images/text. I believe it should replace the ‘StatCan Publications’ header?
-	Share this publication and contact us support the bilingual functionality, but when share this article is selected in French, the pop-up title is still in English. This is happening even though my phone language set to French via the iPhone settings.

**Comment by ForumG-SC** [comment]
@Pharste  Share this publication and contact us button's text should change when to change language not the text in the pop up because the data is hard coded not real so we are not sharing anything there , in future the links will be shared not the title.

**Comment by ForumG-SC** [comment]
@Pharste There is dummy data on that screen , no  functionalities have been implemented yet for the section title's like earlier today, etc.
