### ISSUE TITLE
Publications level 2: menu options

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#221]
The menu options (Share this publication and Contact us) do not work on Android devices (Samsung Galaxy S9).

**Comment by Jiandong-Guo** [comment]
I think it's done by Forum long time ago

**Comment by Jiandong-Guo** [comment]
![Screenshot_1642107685](https://user-images.githubusercontent.com/58485300/149408633-9c9b071a-c8cc-47f9-9105-4680f416482c.png)

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
The Contact Us option now works on Android.

For the "Share this publication" function, if sharing by email:
The subject should be "Interesting publication from StatCan/Publication intéressante de StatCan" (***since in this case, we should be referring to Statistics Canada, and not the app)
The links to Apple and Google are missing from the email
The heading "StatsCAN" should be changed to "StatsCAN app" (Application StatsCAN in French)

If sharing by Snapchat/Messenger:
The subject is missing (but should be included), otherwise, the message looks odd.

**Comment by ForumG-SC** [comment]
@payeisa Fixed as follow:

EN_Screenshot_TextMsg_Email :    


![IMG-0353](https://user-images.githubusercontent.com/84411852/151068011-db82d4af-9c9f-4aa0-8415-0e5a53827f86.jpg)


![IMG-0354](https://user-images.githubusercontent.com/84411852/151068022-decf51ce-f70b-4917-aa29-cb62c340318c.jpg)


FR_Screenshot_TextMsg_Email :    

![IMG-0356](https://user-images.githubusercontent.com/84411852/151068078-e2eeb0b2-b9d8-4f0b-b380-2e30b7e913eb.jpg)

![IMG-0357](https://user-images.githubusercontent.com/84411852/151068090-33e00919-9c26-4413-9c82-80e421ee6ac1.jpg)

**Comment by payeisa** [comment]
Email looks good. 
For social media/text, the text should read:
EN: Interesting publication from StatCan. Check it out! / Publication intéressante de StatCan. Jetez-y un coup d'oeil!
FR: Publication intéressante de StatCan. Jetez-y un coup d'oeil! / Interesting publication from StatCan. Check it out!

**Comment by ForumG-SC** [comment]
> Email looks good.
> For social media/text, the text should read:
> EN: Interesting publication from StatCan. Check it out! / Publication intéressante de StatCan. Jetez-y un coup d'oeil!
> FR: Publication intéressante de StatCan. Jetez-y un coup d'oeil! / Interesting publication from StatCan. Check it out!

Changing this will also result in text being changed in the email as well, for example:
![IMG-0383](https://user-images.githubusercontent.com/84411852/151213360-9e511708-da27-4d3a-a39a-318245c0bc70.jpg)
![IMG-0386](https://user-images.githubusercontent.com/84411852/151213371-bdd6fa3a-71b0-45ca-a09f-f1ad1e9f516b.jpg)

**Comment by ForumG-SC** [comment]
> > Email looks good.
> > For social media/text, the text should read:
> > EN: Interesting publication from StatCan. Check it out! / Publication intéressante de StatCan. Jetez-y un coup d'oeil!
> > FR: Publication intéressante de StatCan. Jetez-y un coup d'oeil! / Interesting publication from StatCan. Check it out!
> 
> Changing this will also result in text being changed in the email as well, for example: ![IMG-0383](https://user-images.githubusercontent.com/84411852/151213360-9e511708-da27-4d3a-a39a-318245c0bc70.jpg) ![IMG-0386](https://user-images.githubusercontent.com/84411852/151213371-bdd6fa3a-71b0-45ca-a09f-f1ad1e9f516b.jpg)

@payeisa Please confirm if that's okay. Thanks.

**Comment by payeisa** [comment]
@ForumG-SC , it's not perfect, but a much better solution. Let's go ahead with the change. Thank you :)

**Comment by payeisa** [comment]
@ForumG-SC Is this ticket ready for validation?

**Comment by ForumG-SC** [comment]
> @ForumG-SC Is this ticket ready for validation?

Yes

**Comment by payeisa** [comment]
Sharing a publication looks good on Android, for email, text and social media. @weglmar Can you please test on iOS and assign back to me once done? Thanks, Isabelle

**Comment by weglmar** [comment]
![1](https://user-images.githubusercontent.com/98898969/153934941-e5b75e80-42e2-42c9-8c7d-e1134517b31a.jpg)
![2](https://user-images.githubusercontent.com/98898969/153934957-47f2102e-ca97-4218-91ef-5518e16af48d.jpg)

It looks good on my iPhone when sharing a text message, email, tweet or on FB Messenger. When I check Facebook and Pinterest, it doesn't display ideally. I'm not sure if Pinterest is very important but I think we may want to consider adding a message to the FB post? (I checked pinterest out of curiosity because it was listed in my default apps).

**Comment by payeisa** [comment]
Validated. @weglmar I added an item to the enhancement list to improve the messaging for the "Share this publication" feature.
