### ISSUE TITLE
Send email in Help & FAQs not working

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#225]
The subject is empty, please make sure it matching the confluence page. Thanks!

**Comment by Jiandong-Guo** [comment]
No information about subject and body are in confluence and UX

**Comment by Jiandong-Guo** [comment]
Please provide them in both English and French

**Comment by Rajat-Sen** [comment]
Hi Jiandong, when the user clicks on Send email button; the subject and the body should be empty. The only thing that needs to be changed is the old email address.

Please change the email to "infostats@statcan.gc.ca"

It should be matching with the email address above send email. Thanks!

**Comment by ForumG-SC** [comment]
@Rajat-Sen Hi Rajat, you can close this ticket as the email will be updated in the ticket https://github.com/StatCan/StatcanPublicationUAT/issues/171#issuecomment-1019594178

**Comment by Rajat-Sen** [comment]
Thanks!
