### ISSUE TITLE
Deliver FAQ URLs

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#228]
Can you please provide the E and F URLs to the FAQ page, once we get them from DISS?
(for the FAQ section in Settings/Support and feedback/Help and FAQ/Support)

**Comment by payeisa** [comment]
@Rajat-Sen The FAQ link (Settings/Support and feedback/Help and FAQ/Support/FAQ) will need to be updated to point to the web page we are finalizing.

**Comment by Rajat-Sen** [comment]
Update: the links haven't been approved yet! Most likely we will have it today or tomorrow.

**Comment by payeisa** [comment]
@Rajat-Sen What I was referring the the URLs for the Settings -Support and feedback - Help and FAQ - Support section. We now have the web page URLs for the FAQs. When the user selects the FAQ icon, they should navigate to the URLs provided below.

![image](https://user-images.githubusercontent.com/89025704/150870344-d4a57a4f-9463-490b-adaf-04d6735f13a6.png)

In English: 
![image](https://user-images.githubusercontent.com/89025704/150870131-a37d4353-5c5f-4eae-8129-8a90c6bcc9a4.png)

In French:
![image](https://user-images.githubusercontent.com/89025704/150870164-965e04ab-a027-4031-805c-6953ac96c820.png)

Note: the web pages are not live yet, but will be on Jan 31, 2022 at 9:00 a.m.

**Comment by Rajat-Sen** [comment]
@payeisa Thank you, we will replace the links now only and can test once the app goes live!

**Comment by Rajat-Sen** [comment]
English: www.statcan.gc.ca/en/sc/mobile-applications/statscan-faq

French: www.statcan.gc.ca/fr/rb/applications-mobiles/statscan-faq

**Comment by payeisa** [comment]
I received updated URLs from DISS yesterday. I'm not sure if it matters or not, but these are the final ones:

![image](https://user-images.githubusercontent.com/89025704/151210278-876012a7-6005-414e-9ca0-6211bd5ef0e8.png)

**Comment by ForumG-SC** [comment]
@payeisa Yesterday, the urls were changed and currently in v29 we have the following urls:    
"http://www.statcan.gc.ca/fr/rb/applications-mobiles/statscan-faq"
"http://www.statcan.gc.ca/en/sc/mobile-applications/statscan-faq"

**Comment by payeisa** [comment]
@ForumG-SC 
This is perfect then! I wasn't sure if they included the "s" in http:

Sorry about that - no changes required then.
