### ISSUE TITLE
For you/Saved/Go to publications

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#229]
If I click on the "Go to publications" button on the "For you/Saved" screen, I should be directed to the "top" of the Publications screen, and not where I left off the last time I was scrolling on the Publications screen.

For example, from the Publications screen, if I scroll down to December 21, 2021, and then go to the For you/Saved/Go to publications, I will go to the Dec 21 publications. I should be going to the top of the Publications screen instead.

**Comment by Rajat-Sen** [comment]
Hi Isabelle, this should be the intended functionality. We are going to add a pill later on this screen "Go to top". 

The other common scenario could be: If the user is scrolling down and selects an article on the publications screen > Go inside the publication screen (assuming the user read the article). When the user clicks on the back button on that screen, the user would need to scroll down again from the top. 

By adding a pill on this screen, will solve this problem. Thanks!

**Comment by AJBouzidi** [comment]
@Rajat-Sen @payeisa this is need to be redesigned (ux) before we start to work on.

**Comment by zhuelle** [comment]
@Rajat-Sen is this a ticket that Dilpreet can work on since you are busy with User Research?

**Comment by Rajat-Sen** [comment]
@zhuelle Yes, I think that will be the best scenario. Assigning this to Dilpreet!

**Comment by radwahm** [comment]
Documentation complete. Awaiting Business Sign-off.

**Comment by radwahm** [comment]
https://confluenceb.statcan.ca/display/SPMA/Feature+x.x+-+Back+to+Top

**Comment by weglmar** [comment]
User story signed off August 24th

**Comment by weglmar** [comment]
Tested, but back to top toast is displayed at all times. When the user scrolls down on the page, and then back up, the back to top toast should be displayed.

**Comment by giftydeep** [comment]
This has already been discussed in daily standup and was first implemented with the given scenario on the confluence.

**Comment by zhuelle** [comment]
@Rajat-Sen Have you got chance to review the prototype on the specification? Thanks!

**Comment by radwahm** [comment]
Here is the scenario from confluence:

Scenario: Displaying Back to Top Toast
Given Any user
And the user is viewing the publications page
**And the user scrolls down 
When the user scrolls back up**
Then the "Back to Top" toast is displayed

Please let me know if you have any questions as I am here to help.

**Comment by giftydeep** [comment]
Please test in the next release.

**Comment by zhuelle** [comment]
@weglmar This ticket was created by Isabelle and since she is away at the moment, I am assigning it to you for testing in the next release. Thanks!

**Comment by weglmar** [comment]
Functions as expected.
