### ISSUE TITLE
French language screen 

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#23]
The French language screen title should be "Langue / Language", instead of "langue" with a lowercase "l".

![image](https://user-images.githubusercontent.com/89025704/132746384-4097c07a-7375-44d7-94e2-e740c05ea940.png)

**Comment by ForumG-SC** [comment]
Fixed, changed will be deployed in the upcoming version.

**Comment by ForumG-SC** [comment]
@payeisa  Requires Validation , assigning it back to you.

**Comment by payeisa** [comment]
Need issue #35 to be be fixed before validating.

**Comment by payeisa** [comment]
Was able to validate after uninstalling/reinstalling the app. screen heading was fixed, but spacing is required between the two buttons. I believe this is documented elsewhere as well.
![image](https://user-images.githubusercontent.com/89025704/147118742-77c3f0a1-6898-458b-ae2a-2204b4dc54db.png)

**Comment by ForumG-SC** [comment]
> Was able to validate after uninstalling/reinstalling the app. screen heading was fixed, but spacing is required between the two buttons. I believe this is documented elsewhere as well. ![image](https://user-images.githubusercontent.com/89025704/147118742-77c3f0a1-6898-458b-ae2a-2204b4dc54db.png)


The Spacing was fixed yesterday in ticket https://github.com/StatCan/StatcanPublicationUAT/issues/35 , you will be able to see the changes in next release.

**Comment by ForumG-SC** [comment]
> > Was able to validate after uninstalling/reinstalling the app. screen heading was fixed, but spacing is required between the two buttons. I believe this is documented elsewhere as well. ![image](https://user-images.githubusercontent.com/89025704/147118742-77c3f0a1-6898-458b-ae2a-2204b4dc54db.png)
> 
> The Spacing was fixed yesterday in ticket #35(I commented UX was fixed in the ticket) , you will be able to see the changes in next release.

**Comment by payeisa** [comment]
Validated.
