### ISSUE TITLE
Notifications screen/menu options

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#230]
Can we please rename the following:
"Notification setting" to "Manage notifications"
"Paramètre de notification" to "Gérer les notifications"

![image](https://user-images.githubusercontent.com/89025704/149690557-9058852c-2805-42e2-b37d-34411b281ae1.png)

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
