### ISSUE TITLE
Notifications / mark all as read

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#231]
When marking all notifications as read, we are not presented with a pop up message.
See User story 4:
https://confluence.statcan.ca/display/SPMA/Feature+2.3+Receive%2C+view+and+manage+in-app+notifications

**Comment by Jiandong-Guo** [comment]
Fixed, Please test in next release

**Comment by Rajat-Sen** [comment]
Validated!
