### ISSUE TITLE
Sharing Publication by email

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#232]
The subject line appears for in EN and FR when sharing via gmail, but it does not appear when opening it in the Apple Mail app (see screenshot).

The email is also missing the StatsCan icon, and links to download the app per the requirements. 
![Apple mail sharing pub](https://user-images.githubusercontent.com/89025880/149703297-70e3c368-8baa-4592-9183-f251104478ce.jpg)
![Gmail app Pub sharing](https://user-images.githubusercontent.com/89025880/149703316-2f48b5fa-8fdb-42b6-be30-869c09c489e0.jpg)
![Draft email overlay](https://user-images.githubusercontent.com/89025880/149703347-83be7002-8135-4c53-8ea8-f31d9f96c74a.png)

**Comment by Jiandong-Guo** [comment]
fixed, screenshot from ipad:
![image](https://user-images.githubusercontent.com/58485300/149980194-a08ea11e-50f2-43c6-b2c0-f410b375f9ba.png)

Please test in next release

**Comment by Jiandong-Guo** [comment]
Icon is not feasible for current workflow, see#212

**Comment by Rajat-Sen** [comment]
Hi Steph, 

For the MVP, we are not going to have the icon while sharing the publication. 

We will improve it later on!

**Comment by Pharste** [comment]
Hi, I am seeing the updated text- thank you!
I noticed when switching to French and sharing, the 'check it out/Jetez-y un coup d'oeil' text doesn't change to French first: 
![Share publication FR](https://user-images.githubusercontent.com/89025880/150418205-d01ea24e-9fec-456b-a57f-3078de7559ab.jpg)

**Comment by goodyke** [comment]
@Pharste the original concern has been fixed and the display of the languages in order will be done in a future development.

**Comment by goodyke** [comment]
Hi @Pharste.  I am closing this ticket so that you can verify that the implementation reflects the original ask for this ticket (except we can not put an icon in the message).  The only concern remaining is the leading language and that was not in the requirements.. but a new GitHub ticket #247 has been created and tagged to 'Post MVP' so that we can look at it after MVP.

**Comment by payeisa** [comment]
The leading language is working on Android. For example, if I set my app language to French, and share a level 2 article, then the leading language of the bilingual email will be French (in both the subject and the body)
@Pharste FYI

**Comment by Pharste** [comment]
Validated the original issue has been fixed.

**Comment by Pharste** [comment]
Hi, I just noticed there is a space missing in the English part of the message, to be fixed please: 

("If not, you should...")
![Email sharing](https://user-images.githubusercontent.com/89025880/150849399-432bfc55-f9b0-4606-a9d2-7884c1016fae.jpg)

**Comment by Pharste** [comment]
Closing as this is addressed in issue #212
