### ISSUE TITLE
Logo cut off on Welcome screen (iPad 12.9")

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#234]
On my iPad, the logo is cut off at the top on the welcome screen, and the French text is missing a period. 
![French Welcome screen](https://user-images.githubusercontent.com/89025880/149806993-ae141662-bdbb-41ae-a511-7e90c15fe594.jpg)
![Logo cut off](https://user-images.githubusercontent.com/89025880/149807012-17b55759-8b52-477e-ac96-8dbc8734af76.jpg)

**Comment by ForumG-SC** [comment]
Fixed

**Comment by Pharste** [comment]
validated

**Comment by Jiandong-Guo** [comment]
I think it's related to #642
