### ISSUE TITLE
Things to change before final deployment

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#235]
Reset the app number to 1
 Delete user profile button from the settings screen
Delete Notification list button from the settings screen

**Comment by Jiandong-Guo** [comment]
What is the Reset the app number to 1 ?  do you mean the version number ?

**Comment by Rajat-Sen** [comment]
yes, it is the version number

**Comment by Jiandong-Guo** [comment]
What is the links on Share this app feature ?

**Comment by Jiandong-Guo** [comment]
What about the  prod api url ?
I can do those 2 now
Delete user profile button
Change the year to 2022 copyright.
please confirm if the version number changed, cannot change back

**Comment by Rajat-Sen** [comment]
Did you tested the app with PROD url?

**Comment by Jiandong-Guo** [comment]
Better leave after MVP,
if I delete the user profile button, It may affect the MVP people to demo

**Comment by Jiandong-Guo** [comment]
Yes, I am testing the prod url now, may have problem

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Hi Jiandong, please don't change app.json file. Just replace expo build with version number like how it was before because tomorrow in the deployment I will be changing version from 0.0.3 to 1.0.0 as it will be final version.

Copyright is already 2022 right now.

**Comment by Rajat-Sen** [comment]
Hi Jiandong,

For the version number, please change the expo build number to the version number.

Please remove the "Delete user profile" button and "Check notification list" button.

**Comment by Rajat-Sen** [comment]
Also, what problem we may have with Prod url?

**Comment by Jiandong-Guo** [comment]
2 test buttons were removed

**Comment by ForumG-SC** [comment]
> 2 test buttons were removed

I already removed Jiandong, did you pull changes?

**Comment by ForumG-SC** [comment]
Merge conflicts resolved.
