### ISSUE TITLE
Clickable area around the element

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#236]
Invisible area needs to be added around the following elements:

1. Welcome screen while switching the language
2. Terms of use screen, while switching the language
3. Back button on Level-2
4. Heart icon on the Saved segment

**Comment by zhuelle** [comment]
44 * 44 P

**Comment by Jiandong-Guo** [comment]
Fixed, test in next release

**Comment by Rajat-Sen** [comment]
Validated!
