### ISSUE TITLE
Space needed in date: Saved screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#238]
On the saved page, there is a space missing between the comma and year. 

i.e.: 
Jan 17,2022 to Jan 17, 2022
![space needed date saved](https://user-images.githubusercontent.com/89025880/149827437-97230a4d-bf07-406f-8be7-0af2dc35191b.jpg)

**Comment by ForumG-SC** [comment]
Done

**Comment by Pharste** [comment]
Validated, thank you
