### ISSUE TITLE
Articles in the saved items tab of the For You screen do not contain the same list of articles in English and French display

### ISSUE THREAD

**Issue by goodyke** [StatCan/StatcanPublicationUAT#240]
This is a bug that was reported during the first round of mobility testing in ticket [QLTY-141](https://jirab.statcan.ca/browse/QLTY-141).

**Problem:** The saved items shown on the For You screen are saved in separate lists (one for each language)

**Solution:** Ensure the saved items list stores the information in one list (that supports both languages so that the items are the same when the user switches the language used in the app).

**How to reproduce:**

1.  Save a publication
2. Verify the article highlight is showing in the Saved items tab of the For You screen
3. Change the language setting in the app to the other language
4. Verify the article highlight that was saved in the previous language is there (it is not there so this is the bug)

**Comment by Jiandong-Guo** [comment]
See ticket#92,  there are 2 separated saving list, one for english, one for french.  the reason is we save  the article info(such as title) in english or french based on the setting at saving point.

**Comment by Jiandong-Guo** [comment]
if really want to combine 2 lists into 1 list, the solution will be:  
1)combine  2 lists into 1 list, and just save id
2)When in saved Screen, always call API to get info in required language

**Comment by Jiandong-Guo** [comment]
fixed, please test in next release

**Comment by goodyke** [comment]
@Jiandong-Guo if you have updated the Saved items to only save the article id (and always refresh to display based on display language that the user has in the app) then this bug should be fixed.  In addition... this fix may result in GitHub #244

**Comment by Rajat-Sen** [comment]
Validated!

It is working but, takes some time to load the whole screen. Closing for now!
