### ISSUE TITLE
When user clicks 'See more' on For You screen in the Following tab then the max number displayed on specific screen is limited to 10 max

### ISSUE THREAD

**Issue by goodyke** [StatCan/StatcanPublicationUAT#241]
This is a bug that was reported during the first round of mobility testing in ticket [QLTY-162](https://jirab.statcan.ca/browse/QLTY-162).

**Problem:** The specific subject screen is only showing a maximum of the latest 10 articles for that subject (even when there are more than 10 that should be shown)

**Solution:** Ensure the specific subject screen shows all articles belonging to a subject (not sure if this requires lazy loading and another api call for the 'next' articles or not)

**How to reproduce:**

1. Go to For You screen and ensure you are Following the subject 'Government'
2. Click the 'See more' link for Government to go to the specific Government subject screen
3. Verify the number of articles shown (this is the bug as it will only show 10 articles even if there are more for that subject - an example is that article 269 on Alpha is not being displayed and should be)

**Comment by Jiandong-Guo** [comment]
scroll problem is fixed, Please test in next release.
But  there is no article(id=269) found in api returns.
There are total 2 pages,
10 articles on first page(399,374,356,326,319,315,303,302,296,283)
3 articles on second page(279,233,191). 
there is an article(id=296) in page one, is the a typo ? but it is in page 1.

**Comment by Rajat-Sen** [comment]
Validated!
