### ISSUE TITLE
Unfollow functionality not working

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#242]
Hi, 

The unfollow functionality is partially working. For instance, if the user goes to manage subjects on the For you screen and unchecks the subject that the user does not want to follow anymore, it works.

On the other hand, if the user goes to a particular subject, clicks on the three dots and unfollows subject from there, it does not work. I have tried closing the app and opening it again and the subject is still there on the Following screen. 

Please test with both ways, and then only close the ticket.

**Comment by Rajat-Sen** [comment]
Also, I did tested on the iPad and the screen was not loading at all. It was empty!

**Comment by goodyke** [comment]
@Rajat-Sen I tried testing removing the subject using both methods and both worked for me (including using the three dot menu to unfollow a subject from a specific subject screen).
I noticed a new version of the app was deployed yesterday... perhaps this is fixed?

**Comment by Rajat-Sen** [comment]
It is working but, not smoothly! Closing this ticket for now.
