### ISSUE TITLE
Bug when opening an article from the Saved segment of the For you screen

### ISSUE THREAD

**Issue by goodyke** [StatCan/StatcanPublicationUAT#244]
**This is a bug that was found through Mobility testing by taking the following steps (it can be reproduced):**
1. Launch app
2. Go to For you screen and ensure there are no saved items there (unsave if required)
3. Select 'go to publications'
4. Open any article and click the heart icon to save it
5. Close app and then relaunch
6. Test opening the saved article and it will open an empty Publications screen

It seems that opening an article to read from the Saved items list does not open that article (it opens the last article read on the Publications screen in the current session).  So the reason the above steps result in an empty article level 1 screen is because no article was opened in the session (before user tried opening the saved article).

Therefore, **_the actual bug is that opening a saved article does not work (the only reason someone would be able to open a saved article and have the correct one show is because it was the last article that the user opened on the publications screen_**).

**Comment by zhuelle** [comment]
@Rajat-Sen and @goodyke, please confirm if we should add "Before MVP" for this ticket ASAP. This way we can finalize all the bugs tickets so the two developers can complete them by this weekend. Thanks!

**Comment by goodyke** [comment]
@zhuelle  This GitHub ticket is based on a Jira ticket created by the mobility testing team.  This bug _should not exist_ when we deliver MVP.  However, I do not believe there is any work to be done by the dev team right now because @Jiandong-Guo fixed GitHub #240 during this sprint and that should result in this bug disappearing as well.  Therefore, we will not add this ticket to this sprint but we can leave the 'Before MVP' on the ticket so that we can test it again after this sprint is deployed.

**Comment by goodyke** [comment]
@zhuelle The fix made with #240 did not result in this bug going away.  I have added the 'Before MVP' label to this ticket as this bug should not exist for MVP.
**Details**
I tried marking many articles as saved (using version 28 which was deployed on Jan 23) and often when I choose to open one of the saved article highlights from the 'Following' segment of the 'For you' screen the application opens a different article - not the one I saved.

**Comment by Jiandong-Guo** [comment]
It's fixed, please test in next release

**Comment by goodyke** [comment]
Validated the fix with production using version 29 of the mobile app and there were still issues.  However, un-installing the application on my phone and onboarding again shows that this issue is now resolved... the issues remaining were do to articles that I had saved previously that were not opening properly before.  Closing this ticket.
