### ISSUE TITLE
Final Screenshots for the stores

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#245]
Please provide the final screenshots  whenever it is available so that I can upload it to the stores and make sure that apple and google are not rejecting the screenshots due to dimensions or any other issue.

**Comment by Rajat-Sen** [comment]
@Pharste, I had a chance to look at the size of the screenshots and they are not matching with the required sizes for the stores. 

Please mention it to Comms to make sure they are using the right sizes to upload it to store.

**Comment by Pharste** [comment]
Followed up with Comms by email today, and waiting on updated screens. I'll send via email and add a comment here when the final versions are available.

**Comment by ForumG-SC** [comment]
Screenshots has been updated in the store.
