### ISSUE TITLE
Order for writing the English and French text when sharing is not matching the language setting

### ISSUE THREAD

**Issue by goodyke** [StatCan/StatcanPublicationUAT#247]
@Pharste mentioned in #232 that the order of the text shown in the email is not aligning with the language setting that the user has in the app.  I looked at the requirements for Feature 3.3 Share article and it was not specified that the order of the automated text must match the language setting in the app.  If we want to have it match then we need to update the requirements.  This ticket has been created so we can look at the next steps after MVP (and #232 will be closed as the functionality is matching the requirements).

**Comment by payeisa** [comment]
The leading language is working on Android. For example, if I set my app language to French, and share a level 2 article, then the leading language of the bilingual email will be French.
@Pharste FYI

**Comment by Pharste** [comment]
Hi, I tested this again today and it seems to be working now. However, when sharing the app by text, because there is no subject line, the message just says "if not, you should download it..." I'll open a new ticket for this.
