### ISSUE TITLE
For you: Display of text size when switching language

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#249]
If I look at the "For you" screen in French, the size of the text is smaller than the one in English.

French:
![image](https://user-images.githubusercontent.com/89025704/150700273-4ed3c186-6340-4015-96f0-e6503539fab1.png)

English:
![image](https://user-images.githubusercontent.com/89025704/150700337-b091326d-54fa-4382-99ca-a8c916eb5888.png)

**As of Feb 11, 2022, this is no longer an issue:** There's also an issue with the language of the content displayed. If I switch the language, then content in the opposite language gets displayed on the For you screen. For example, I onboarded in English, started following two subjects, then switched language to French. When I returned to the "For you" screen, the content was still in English:

![image](https://user-images.githubusercontent.com/89025704/150700430-3840407e-e770-436f-8ea3-16d482f3d2e7.png)

@ForumG-SC @Jiandong-Guo @goodyke FYI

**Comment by weglmar** [comment]
Validated, content displays correctly on my end.

**Comment by payeisa** [comment]
I was also able to validate - the text displays in the appropriate language on the "For you" screen when I switch languages. 
@weglmar, I believe the headings of the "For you" screen are smaller in French due to the length of the text. @ForumG-SC Can you please confirm? If that's in fact the case, this ticket can be closed.

**Comment by ForumG-SC** [comment]
@payeisa Yes, that's correct. We can close this ticket.
