### ISSUE TITLE
Publications Screen Level 3 - Back and forward buttons

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#25]
When you first access a level 3 article, the Back and Forward arrows are dark, which is misleading. For example, from the Home screen, click the "Canadian international merchandise trade" article. Scroll down and click the "service" hyperlink.

A web browser will display the Daily article.

If I click on the Back or Forward arrow at the bottom, nothing happens. 

Can the arrows be a light grey, or a lighter color to indicate that no navigation can be done? The arrows should only be dark/active after the user clicks on another links, within the browser window.

**Comment by ForumG-SC** [comment]
When you land on the screen for the first time no navigation can be done , therefore the buttons are disabled and light grey color : 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/84411852/133497462-f27fbfdf-3a37-4174-8558-f451dc893476.png">

Once you start navigating in the WebView the buttons are active and color changes to dark grey : 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/84411852/133497550-82e22ab7-a790-49cf-8bea-99278ab424e5.png">


Fixed , changes will be deployed in the upcoming release.

**Comment by payeisa** [comment]
Validated Sept 22, 2021.
