### ISSUE TITLE
Colour in dark mode

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#250]
If the Colour theme is set to auto and the app launches in Dark mode, on the For you screen; the colours are not matching for the segmented options (Following and Saved). Please match it with Dark mode.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Fixed has been applied, however I cannot test in simulator as it doesn't gives me option to switch to dark mode. I cannot test on my personal device as it is not responding properly.

**Comment by Rajat-Sen** [comment]
@ForumG-SC, I will validate this in the new release!

**Comment by ForumG-SC** [comment]
> @ForumG-SC, I will validate this in the new release!

Came across the issue, fix didn't work. Investigating it.

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Hi Jiandong, I can see that you did some code changes on Favourite tab previously, could you please look into this issue, last time you set for global theme 2 and not 0

**Comment by Jiandong-Guo** [comment]
It's fixed, please test it in next release

**Comment by Rajat-Sen** [comment]
Validated!
