### ISSUE TITLE
Navigation problem For you Screen

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#251]
When the user goes to For you Screen after following a subject, click on See more and then select an article inside the screen. 

After clicking on Go back button, it should take the user to See more screen where I should see all the articles instead, it takes to the For you screen.

**Comment by Jiandong-Guo** [comment]
fixed, please test it in next release

**Comment by Rajat-Sen** [comment]
Validated!
