### ISSUE TITLE
Publications not listed properly under a following subject

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#252]
For tablet,

When the user goes to For you screen after following a subject, click on See more; the user cannot see the cars properly.
Please reference to the attached image.

**Comment by Rajat-Sen** [comment]
This issue is happening is also happening on Android tablets as well. Please reference to the attached image. Thanks!
![See_more_screen](https://user-images.githubusercontent.com/38566088/150848739-06d3beef-77d1-47d1-8c4a-498b86064db1.png)

**Comment by Jiandong-Guo** [comment]
Cautionally saying it's fixed, please test it in next release

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Hi Jiandong I tested this screen, on iPhone 11 Pro when setting the text size to max , image is not big to cover.

**Comment by Jiandong-Guo** [comment]
Tested on iphone 12 pro max, iphone 11 pro, ipad 9.7, ipad 12.9,android pixel 5, android tab Nexus 7

**Comment by Jiandong-Guo** [comment]
Tested the text size

**Comment by ForumG-SC** [comment]
> Tested the text size

Tested, it works now, thanks.

**Comment by goodyke** [comment]
Validated the fix with production using version 29 of the mobile app and this concern is not a problem with my iPhone... but leaving it to @Rajat-Sen to close as he may wish to do further validation (such as test the fix on other device types and versions).

**Comment by Rajat-Sen** [comment]
Validated!
