### ISSUE TITLE
Publication level 1: Alignment of images (tablet)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#256]
The image tiles on the Publications screen level 1 are not aligned on tablet. (Galaxy Tab S6 Lite) 

![image](https://user-images.githubusercontent.com/89025704/150840397-0c9e3343-e0f7-431c-a4bf-3f03999d0d9c.png)

**Comment by ForumG-SC** [comment]
@payeisa Fixed, please test in the new upcoming release. Thanks.

**Comment by payeisa** [comment]
Validated.
