### ISSUE TITLE
For you/Options/Tablet/Large text 

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#258]
When setting the text size to largest on my tablet, and then navigating to Pour Vous/Options/ the "Gérer les sujets" button does not adjust in French. It's very small and very hard to see. This issue applies in French only.

![image](https://user-images.githubusercontent.com/89025704/150845828-3eed6e00-bbf5-44ab-a94f-a500294bb178.png)

**Comment by Rajat-Sen** [comment]
@ForumG-SC, please add shadow to the button. Thanks!

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Validated. 
@Rajat-Sen Can you please validate at your end (re: shadow), and then close if fixed?

**Comment by payeisa** [comment]
@Rajat-Sen I believe this one can be closed after you validate.

**Comment by payeisa** [comment]
@Rajat-Sen Can this ticket be closed?

**Comment by Rajat-Sen** [comment]
Yes, it's been validated!
