### ISSUE TITLE
For you: content not loading in tablet when selecting "See more"

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#259]
On my tablet, if I select the "See more" option on the For you/Following screen, the content doesn't load:
This is issue happens in both English and French.
The issues does not happen on my phone.

![image](https://user-images.githubusercontent.com/89025704/150847605-792fa5ba-c4c6-4cb9-91fe-002cad2ac7c3.png)

**Comment by Rajat-Sen** [comment]
@payeisa, I am closing this ticket as we are already working on this issue and it linked to ticket #252. 

Additionally, I am attaching the your screenshot in that ticket.
