### ISSUE TITLE
Tablet & small text setting issue

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#260]
If I switch the text size setting from largest to smallest, all the screens adjust, except for the "For you/Following" screen, in both E and F.

Text is set to smallest:
![image](https://user-images.githubusercontent.com/89025704/150848939-941cbd20-e597-4dbb-97a2-b20311878a89.png)

But the "For you" screen does not adjust:
![image](https://user-images.githubusercontent.com/89025704/150849028-810eca36-bc9e-48a4-a9e1-97d80046e2ae.png)

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Validated.
