### ISSUE TITLE
Following screen bug

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#262]
When the user follows only a single subject in dark mode, the half of background screen colour remains white. Please make the background applicable to the whole screen.

Please reference to the attached image.
![IMG_5376](https://user-images.githubusercontent.com/38566088/150858979-b5f04575-e582-46f3-bc4a-4011a82e5d56.PNG)

**Comment by zhuelle** [comment]
@payeisa need prioritization.

**Comment by weglmar** [comment]
Validated
