### ISSUE TITLE
Search screen bug

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#263]
When the makes a search and select any article and tap on Heart icon.

Go back to search results and open any other article, the Heart icon will show as filled even if it is not clicked.

**Comment by Jiandong-Guo** [comment]
fixed, please test in next release

**Comment by Rajat-Sen** [comment]
Hi Jiandong, this ticket has not been fixed; please double check again. Thanks!

**Comment by Rajat-Sen** [comment]
Also, please let me know if you need any help understanding the ticket!

**Comment by Jiandong-Guo** [comment]
I know the problem but still struggling find how to fixed, the problem is the state not switch immediately

**Comment by Jiandong-Guo** [comment]
cautionally saying it's fixed, please test in next release

**Comment by Rajat-Sen** [comment]
Validated!
