### ISSUE TITLE
Notifications screen bug

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#264]
When the user starts following some subjects > Go to Notifications when you can see the red dot.

1. The user should not get any previous notifications.
2. When tapped on a notification, the user sees a glance of empty screen which shouldn't be there.
3. After reading a notification, the dot should completely disappear away. However, the user can see the light colour of the dot which shouldn't be there.

**Comment by AJBouzidi** [comment]
@Rajat-Sen could you add screenshot of this issue.
