### ISSUE TITLE
Search screen/ large text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#265]
The search results aren't adjusting with the large text (iPad and iPhone):
![iPhone large text search](https://user-images.githubusercontent.com/89025880/150878124-7436c75a-c469-4cae-9245-1bec9329dff6.jpg)
![Search results large text](https://user-images.githubusercontent.com/89025880/150878127-a9181194-7f64-4b4d-bfdd-36c888d9ac06.jpg)

**Comment by ForumG-SC** [comment]
@Pharste Investigating the issue. Thanks.

**Comment by Pharste** [comment]
@payeisa Is this happening on Android too?

**Comment by ForumG-SC** [comment]
@Pharste Do you want to remove italic subject name and date in this screen too ?

**Comment by ForumG-SC** [comment]
> @payeisa Is this happening on Android too?

yes

**Comment by Pharste** [comment]
> 

Yes, please. Thanks for catching that. 
This should also be consistent with the Publications page.

**Comment by ForumG-SC** [comment]
@Pharste If we want fonts to be adjusted from the settings than we cannot set fixed font size like how it is looking right now instead the size will be reduced the you land on the page for the first time as we are setting dynamic styling now , though the size will be small but can be enlarged from the settings.

**Comment by ForumG-SC** [comment]
This is how by default it will look when landing on this page for the first time : 
![image](https://user-images.githubusercontent.com/84411852/150881004-5c9bcc99-26ee-41f3-a86b-f9072fd0c2bf.png)

When increasing text size to the max , this is how it will look:
![image](https://user-images.githubusercontent.com/84411852/150881129-8f79f776-0b43-43b5-98d2-bb1b6f44cedc.png)


@Pharste

**Comment by ForumG-SC** [comment]
Fixed

**Comment by Pharste** [comment]
Validated, thank you!
