### ISSUE TITLE
iPad: saved screen not functioning properly

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#267]
I can't get saved articles to display on the screen when using iPad (it is working as expected on my phone
![Cant get saved articles- iPad](https://user-images.githubusercontent.com/89025880/151189630-9769f947-f8b5-41fe-9cee-a51fd3120cff.jpg)
)

**Comment by Rajat-Sen** [comment]
Hi Steph, Please uninstall the app and install again. I came across the same issue.

**Comment by Pharste** [comment]
Thanks @Rajat-Sen Uninstalling and installing fixes it!
