### ISSUE TITLE
Display of No search results & recent searches 

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#268]
We should consider enhancing the display of the "No search results" and the "Recent searches" to separate the two a bit better. Maybe add a line?

![image](https://user-images.githubusercontent.com/89025704/151190101-319b237a-9775-4034-a6f8-48cc89bc658d.png)

**Comment by payeisa** [comment]
@ForumG-SC It looks the same as what I reported in January. I would recommending assigning this ticket to Rajat for his design input. Thanks, Isabelle

**Comment by weglmar** [comment]
#472 Closing this ticket as new requirements for Search have been identified in 472. This will be resolved when 472 is developed.
