### ISSUE TITLE
Alignment of buttons on iPad

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#269]
The alignment of the on/off buttons for notifications are not centred: 
![Alignment of manage notifications button iPad](https://user-images.githubusercontent.com/89025880/151190573-2529bc77-6e17-4714-9d3f-4e24db084116.jpg)

The link out to new window button (?) is not centred on the social media page: 
 
![Alignment of link icon on SM screen iPad](https://user-images.githubusercontent.com/89025880/151190797-97a87dc5-3cb1-4d52-bd5f-f352b5fb9a4c.jpg)

**Comment by ForumG-SC** [comment]
@Pharste Working on fixing this issue right now.

**Comment by ForumG-SC** [comment]
@Pharste Fixed both the issues, in addition also fixed alignment issue of Bold switch on iPad.

**Comment by payeisa** [comment]
Is this ticket ready for validation?

**Comment by ForumG-SC** [comment]
> Is this ticket ready for validation?

Yes , it was ready for validation in the previous release that's why I assigned it back to Stephanie.

**Comment by Pharste** [comment]
validated
