### ISSUE TITLE
Functionality: Publications Screen Level 1 : Notifications Screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#27]
From the Home screen, click on the bell icon to view the notifications.
Click more.
Select "Mark all as read".
Red dots disappear from articles to indicate that the notifications have been read.
However,  when I click on the "Back" arrow to return to the Home screen, the bell icon still displays the red dot (when it shouldn't).

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by payeisa** [comment]
Will be able to test one issue with API is fixed.

**Comment by payeisa** [comment]
Validated.
