### ISSUE TITLE
Share app via LinkedIn - Only GooglePlay link displaying

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#271]
When sharing on LinkedIn, only the Google Play link is displayed -- 
![LinkedIn 2 png](https://user-images.githubusercontent.com/89025880/151199078-b6b97f17-8ffd-424f-8b8f-489ff8b0e84d.jpg)
<img width="414" alt="LinkedIn 1" src="https://user-images.githubusercontent.com/89025880/151199082-0ce22b78-cd21-47b7-9f0f-b05cf5ee9275.png">

**Comment by goodyke** [comment]
@Rajat-Sen I have verified this ticket and I am getting the same result as Stephanie described (using my iPhone and version 29 of the app).  The LinkedIn share that is created (that I obviously did not actually post) only contains the Google Play version when it should give links to download for both Android and iOS.  I have assigned this to you for prioritizing with the developers.

**Comment by Rajat-Sen** [comment]
Right now, you are seeing the link from Google because it is taking you to the Statistics Canada developer page. 

For iOS, the link should be working once we release the app to public.

**Comment by Rajat-Sen** [comment]
When sharing the app, on LinkedIn; it is not showing link for iOS. However, on regular messages or email, it is showing both the links.

**Comment by AJBouzidi** [comment]
https://github.com/react-native-share/react-native-share

**Comment by ForumG-SC** [comment]
> https://github.com/react-native-share/react-native-share

https://react-native-share.github.io/react-native-share/docs/share-single#static-values-for-social does not support LinkedIn.
