### ISSUE TITLE
Small text setting: For you screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#275]
A thorough review of display based on text size needs to be done to ensure the accuracy across all screens and functions.
For example, if I set the text size to smallest, the display on the For you/Saved screen is much smaller than then the other screens.
If I set the text size to smallest, the buttons on the For you/Following and For you/Saved don't adjust.

**Comment by payeisa** [comment]
@AJBouzidi I see that this ticket is part of the April 27 release, however, it's not assigned to me. Is it ready for validation? I'm also wondering if this issue is covered by Rajat's overall design improvement tickets that he submitted to ensure consistency. Thanks, Isabelle

**Comment by ForumG-SC** [comment]
@payeisa Please test the fix in the next release. However, The confirmation message on's text size the For you/Saved screen when unsaving a publication cannot be modified as we are using Alert and by default it displays the text in that size, we don't have control over to modify the alert's text size.

**Comment by payeisa** [comment]
Validated.
