### ISSUE TITLE
Changes to intro message on Search screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#276]
Can we please remove the following text from the intro message on the Search screen?
(since January 2022)
(depuis janvier 2022)

**since StatsCAN Plus content in the app goes as far back as November 2021**

The updated text would be:
Find publications published in the StatsCAN app.
Trouver des publications diffusées dans l'application StatsCAN.

Not a showstopper and not critical, but would be nice if we could fit it in.

@Pharste FYI

**Comment by ForumG-SC** [comment]
Done.

**Comment by payeisa** [comment]
Validated.
