### ISSUE TITLE
Images in article level 2

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#279]
We had removed the level 2 images, but they are being displayed with the latest deployment.
Refer to Jan 25 Robbie Burns article as an example

@Pharste FYI

**Comment by Pharste** [comment]
I took a look in ORPS, and it seems like the images were added to the Plus articles in the content block, as well as the home page image:

![International day of education](https://user-images.githubusercontent.com/89025880/151227407-0b8850a5-11a2-42f1-a4f4-9db78c0a364a.jpg),
![Robbie Burns](https://user-images.githubusercontent.com/89025880/151227404-ef9dd7b4-5730-470b-9056-6731281735c6.jpg)

**Comment by payeisa** [comment]
@Pharste That's correct. The Plus teams always has a Home page image, as well as an article image. However, on the app side, we were excluding the article image. I'll try to find the ticket.

**Comment by Pharste** [comment]
> @Pharste That's correct. The Plus teams always has a Home page image, as well as an article image. However, on the app side, we were excluding the article image. I'll try to find the ticket.

Oh, sorry! I didn't realize and thought it was only the home page image we were excluding.

**Comment by payeisa** [comment]
I found ticket 107 https://github.com/StatCan/StatcanPublicationUAT/issues/107 but it doesn't include the decision made.
@Rajat-Sen Could you please weigh in?

**Comment by Rajat-Sen** [comment]
@payeisa, we did removed the featured image and decided to only show images the included in the article.

**Comment by payeisa** [comment]
oh ok, sorry, my bad! I thought we were removing (all) images from level 2 due to loading. I will close this ticket!
