### ISSUE TITLE
Notifications - menu item (Notification settings)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#28]
When on the Notifications page, and you select the menu item, "Notification settings" should be "Manage notifications".

![image](https://user-images.githubusercontent.com/89025704/133944058-e0b8ecd2-fd77-4eeb-99c2-5b7602350cdc.png)

**Comment by ForumG-SC** [comment]
Resolved, the changes will be deployed in the upcoming release. Requires validation, assigning it back to you.

**Comment by payeisa** [comment]
Validated Sept 25, 2021.
