### ISSUE TITLE
Share publication - ipad

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#280]
I'm not sure if this is an app-related issue, or if this is standard with iPad, but when I click share publication, there is no 'x' to navigate away from the pop-up. (It does disappear when I click elsewhere on the screen though).
![Share publication ipad](https://user-images.githubusercontent.com/89025880/151222060-0607e237-8715-48b7-a566-7439fa3284df.jpg)

**Comment by Rajat-Sen** [comment]
Hi Steph, it is the UI for iPad. Thanks!

**Comment by Pharste** [comment]
> Hi Steph, it is the UI for iPad. Thanks!

Thanks for confirming! I'll close this ticket.
