### ISSUE TITLE
ORPS Content not published in app

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#282]
There were four daily articles published in ORPS this morning that did not publish in-app.

The articles are: 
Payroll employment, earnings and hours, and job vacancies
Monthly civil aviation statistics
Aircraft movement statistics: Major airports
Railway carloadings

**Comment by Pharste** [comment]
Although they aren't appearing on the Publications home page, I did receive notifications for them, and can search for them

**Comment by AJBouzidi** [comment]
@zhuelle do you have any update on this? this is should be closed because it's not app issue.

**Comment by zhuelle** [comment]
@AJBouzidi , sorry I was not aware of this ticket was waiting for me to action. Based on the previous comments, seems that there was a caching issue on the Drupal side and it should be validated by the client. We can close the ticket once it is tested.
