### ISSUE TITLE
Search mode > filter by subject > Decrease padding

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#286]
Filter by subject(s) option has excessive padding from top and bottom (Apply button). That should be decreased.

The close icon should be aligned with the checkboxes as well.

**Comment by zhuelle** [comment]
@payeisa need prioritization.

**Comment by Rajat-Sen** [comment]
Please check the prototype to see how it has been implemented!

Link: https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/16031f7c-3125-46ab-8fc2-0ccb76b2a590

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/175367322-0f8a6477-138d-4c8c-9dec-d0fdccf49abd.png)
Not sure what you want to change:
1)Do you want to leave a part of lower layer area on top (identified with red circle)?  
        If yes, we have to test, because the potential issue is that the screen reader will read "Filter by subject(s)", then read "Canada's oceans and ....", then read "Filter by subject......."
2)Do you want to reduce the height of popup title line (identified with green circle) ?

**Comment by Rajat-Sen** [comment]
You are only testing it on Android devices. Please test on iOS Devices and bigger screen sizes like we discussed in the morning meeting. An example of that would be #342. That ticket has been tested on different devices.

See the attached screenshot to see what I am seeing on my iPhone.

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/175373092-4867c883-6bfa-4129-87b2-5949501daa1b.jpeg)

**Comment by Jiandong-Guo** [comment]
OK, what need to change are the height of popup title and footer

**Comment by Jiandong-Guo** [comment]
iPhone 12:
![Simulator Screen Shot - iPhone 12 Pro - 2022-07-13 at 14 16 41](https://user-images.githubusercontent.com/58485300/178807261-745826e4-883d-4a1e-8ad4-e48fc357861a.png)

iPad:
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-07-13 at 14 18 04](https://user-images.githubusercontent.com/58485300/178807265-7ecf196f-81c0-4492-8f68-6eb937d0c92c.png)

**Comment by Rajat-Sen** [comment]
Validated!
