### ISSUE TITLE
Cards consistency on all screens.

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#288]
Cards on different screens have different sizes. They should be consistent with the Actual size and font size. Please refer to the prototype for the font size. 

Also, I have attached images for reference.

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/156433687-9fe4ccb2-5584-4f9a-9f23-f01eb8abcf4e.jpeg)
![image](https://user-images.githubusercontent.com/38566088/156433704-90518765-2e2d-4e51-8f08-30b30f16b50e.jpeg)
![image](https://user-images.githubusercontent.com/38566088/156433716-d93a236a-e53a-4bda-9411-0c141d97a7bf.jpeg)

**Comment by Jiandong-Guo** [comment]
Please do an internal test since Rajat is not here

**Comment by zhuelle** [comment]
Assign back to Rajat for testing.

**Comment by Rajat-Sen** [comment]
validated!
