### ISSUE TITLE
Publications Screen Level 2 (label)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#29]
"Share this publications" should be "Share this publication" (no "s") at publications.

Publications Screen Level 2 - Share this publication button implemented at the bottom of the screen (Airdrop, Message, Email etc share menu) https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/b14046cc-c18f-43fd-bda2-c4a291bb20d3 https://github.com/StatCan/StatCanPublication/issues/67

**Comment by ForumG-SC** [comment]
Resolved, requires validation , assigning it back to you.

**Comment by payeisa** [comment]
Validated Sept 25, 2021.
