### ISSUE TITLE
For you screen consistency

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#293]
There should be padding underneath the Following and Saved bar to represent navigation status.

**Comment by zhuelle** [comment]
@Rajat-Sen , please verify if this ticket is required as padding has been added.

**Comment by Rajat-Sen** [comment]
It's not fixed properly, please see the prototype to verify. Thanks!

https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/55cd66da-e424-4b99-90d2-451edc7fedc7

**Comment by zhuelle** [comment]
Has not been worked on. Require prioritization.

**Comment by payeisa** [comment]
Priority added.

**Comment by zhuelle** [comment]
@Rajat-Sen Please close this ticket if it is not required at current stage. Thanks!

**Comment by Rajat-Sen** [comment]
Closing this ticket as the For you screen is going to be transferred to Publications screen
