### ISSUE TITLE
Functionality of 'back' button on Android

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#297]
The universal back button on Android devices is not working to navigate in the app, and has been pointed out by a few users.

**Comment by goodyke** [comment]
Hi @Rajat-Sen,
I will remove myself as an assignee as I have no method to test an Android device.  Please look into this concern when you have time.  Thanks!

**Comment by Rajat-Sen** [comment]
The universal back button should be enabled at all times.

Once the user has completed the onboarding screen steps, the user should not be able to go back to the previous screens. 

While the user is completing the onboarding screens, the back button should be enabled.

**Comment by ForumG-SC** [comment]
@Pharste Hi Stephanie, we have only disabled back button on the android phones for the onboarding screen as user should not be able to repeat the onboarding process. After Onboarding process is completed, the back button is not disabled. Could you please provide further information like on which particular screen user were not able to use the back button ?

**Comment by Pharste** [comment]
Hi @ForumG-SC we have had two users email us with this issue-- it seems like it is happening on all screens for them, not just the back button. One user specified it didn't work when navigating to the article view, and back to the publications screen. They were using a Samsung Galaxy S8 (Software version unknown).

The other user was using Google Pixel 6, Android 12 (security update Jan 5th 2022)

**Comment by Rajat-Sen** [comment]
I tested this functionality again and the back button seems to be disabled on all screens. The OS version of android is 12

**Comment by Pharste** [comment]
@payeisa Can you please test on Android?

**Comment by ForumG-SC** [comment]
> @payeisa Can you please test on Android?

This ticket can be validated in the next testing release not in the current version of the app. Thanks.

**Comment by payeisa** [comment]
@Rajat-Sen Can you please include a screenshot of what the "expected" back button should be? I've never had issues with navigating back, from any screens, from my Android S9, so I'm not too sure if I can replicate the issue. Thanks, Isabelle

**Comment by Rajat-Sen** [comment]
@payeisa, I am using Google Pixel to test on Android devices. I cannot use the default back button on some screens which follows:

1. Publications: Going from Level-2 to Level-1.
2. Search: Tapping back button after Searching for results.
3. Following: After clicking on an article without going into a particular subject. I am not able to go back.
4. Following after tapping see more: Can't go back to following main screen using default back button.
5. Settings: After clicking on any list-item such as Language, Text size, colour theme etc. Cannot go back after using default back button.

For default back button, please refer to the attached screenshot.

Thanks,
Rajat

**Comment by Rajat-Sen** [comment]
![Screenshot_20220302-135938.png](https://user-images.githubusercontent.com/38566088/156429948-55dde55e-6b9f-494e-8b89-1f1155b218ce.png)

**Comment by payeisa** [comment]
@Rajat-Sen , For Galaxy S9 and S20, I have both, the default back button, as well as the back button at the top of the screen for all the screens, except for Search (where I only have the default back button at the bottom, an no back button at the top of the screen).

Publications: Going from Level-2 to Level-1:

![image](https://user-images.githubusercontent.com/89025704/156437990-8f4fee9f-26b3-4964-b2f2-bcb419806514.png)

Search: Tapping back button after Searching for results.

![image](https://user-images.githubusercontent.com/89025704/156438232-96739c65-8ab1-4aaf-8c4d-73ddfb2b030e.png)

Following: After clicking on an article without going into a particular subject:
![image](https://user-images.githubusercontent.com/89025704/156438356-4a180571-865a-4692-a30a-6d81bd4390e1.png)

Following after tapping see more:  I have both, the default back button, as well as the back button at the top of the screen:
![image](https://user-images.githubusercontent.com/89025704/156437640-c626eb71-5a2e-4a76-adc4-40357b1eb233.png)

Settings: After clicking on any list-item such as Language, Text size, colour theme etc. I have both, the default back button, as well as the back button at the top of the screen:
![image](https://user-images.githubusercontent.com/89025704/156437342-58b959ec-2aa3-42c1-8f11-de3732c88f5a.png)

**Comment by Rajat-Sen** [comment]
@payeisa, if you click on the back button at the bottom. Are you able to navigate back?

**Comment by payeisa** [comment]
@Rajat-Sen Yes, both the S9 and S20 allow me to navigate back, using the default back button, on all screens.

**Comment by Rajat-Sen** [comment]
It seems to be working now!
