### ISSUE TITLE
Publications Screen Level 2 (StatCan Publications - Share this article)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#30]
From the Publications screen, level 2, when you click on the menu (in the top right corner) and select "Share this publications". The heading of the screen you navigate to next should be "StatCan - Share this publication", instead of "StatCan Publications - Share this article".

![image](https://user-images.githubusercontent.com/89025704/133944732-c3b81fc2-803b-4657-b2dd-4369c1091ac5.png)

Publications Screen Level 2 - Share this publication button implemented at the bottom of the screen (Airdrop, Message, Email etc share menu) https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/b14046cc-c18f-43fd-bda2-c4a291bb20d3 https://github.com/StatCan/StatCanPublication/issues/67

**Comment by ForumG-SC** [comment]
Resolved, changes will be deployed in the upcoming release. Requires Validation , assigning it back to you.

**Comment by payeisa** [comment]
Validated Sept 25, 2021.
