### ISSUE TITLE
Search results & image alt text

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#301]
The search should not include the Alternative text field for images. For example, if I search for "fire" then the article "Curling up with a good book" returns. The word "fire" is not in the title, or in the body of the article. It's only in the alt text of the image. So it doesn't make sense for us to search that field.

@Pharste @goodyke @weglmar FYI

**Comment by payeisa** [comment]
Tagging as "Major".

**Comment by AJBouzidi** [comment]
@Jiandong-Guo is this a backend issue and should be sent to David?

**Comment by AJBouzidi** [comment]
@zhuelle which project we should log on this ticket as it's a backend issue?

**Comment by AJBouzidi** [comment]
we agreed there is no change is required to API functionality.
