### ISSUE TITLE
Update Apple Store Keywords

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#302]
The app store was recognizing the keywords as two long strings (with the commas) because of how they were first submitted: 
<img width="414" alt="Apple keywords 1 jpg" src="https://user-images.githubusercontent.com/89025880/152376583-463fccf9-dfcb-430c-84a6-e93280df71dc.png">
![Apple keywords 2](https://user-images.githubusercontent.com/89025880/152376640-c075e18d-b02a-446f-9372-0c876b8c16bc.jpg)

**Please update to:**

EN: Stats Canada Data CPI Economy  Society Environment Government Population Census Demography
FR: Stats Canada Data CPI Economy  Society Environment Government Population Census Demography

**Comment by ForumG-SC** [comment]
@Pharste It can only be updated when we push first updated version to the stores(i.e doing new release).

**Comment by Pharste** [comment]
Thank you @ForumG-SC

**Comment by AJBouzidi** [comment]
@ForumG-SC the keyword should not separate with space..? could you validate that?

**Comment by ForumG-SC** [comment]
@Pharste In the next release to the store, we would have to revert back the keywords using commas and remove space as according to the apple's guidelines:

Keywords are limited to 100 characters total, with terms separated by commas and no spaces. (Note that you can use spaces to separate words within keyword phrases. For example: Property,House,Real Estate.) Maximize the number of words that fit in this character limit by avoiding the following:

Plurals of words that you’ve already included in singular form
Names of categories or the word “app”
Duplicate words
Special characters — such as # or @ — unless they’re part of your brand identity. Special characters don’t carry extra weight when users search for your app.

Reference: https://developer.apple.com/app-store/product-page/

**Comment by Pharste** [comment]
@ForumG-SC if this is how it should be according to Apple that's ok, but if the keywords are supposed to be separated by commas, do we know why they weren't working before and showing as one long word?

**Comment by ForumG-SC** [comment]
@Pharste Hi Stephanie, I am not sure why is it not working because the keywords in the store are added as per apple's guidelines. However, I have contacted apple regarding the same, Once I get a response from them, I will update it here.
![image](https://user-images.githubusercontent.com/84411852/174642502-351a1dbc-3099-4fb7-a16b-6df8806eb7d5.png)

**Comment by ForumG-SC** [comment]
@Pharste 
![image](https://user-images.githubusercontent.com/84411852/175749014-5768116f-9350-40ca-83c8-022234172b51.png)
