### ISSUE TITLE
Enhance message when saving a publication

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#303]
To add...

**Comment by payeisa** [comment]
Can we please change the toast message from :
Added to saved items on For you
Ajouté aux éléments sauvegardés dans l'onglet Pour vous

To:
Added to the "Saved" menu of the "For you" screen
Ajouté au menu "Éléments sauvegardés" de l'écran "Pour vous"

**Comment by payeisa** [comment]
@Rajat-Sen Can you please review and let me know if you agree with the proposed chage?

**Comment by AJBouzidi** [comment]
@payeisa would you please take a look at this ticket and close it if not needed.

**Comment by Rajat-Sen** [comment]
Agreed!

**Comment by weglmar** [comment]
@ForumG-SC Hi Forum, here is my device info: 

Device Type: iPhone X

Device Screen Size: 5.8 inches 

Device Screen Resolution: 2436 x 1125 

Device’s OS version info: 15.5

**Comment by weglmar** [comment]
Closed.
