### ISSUE TITLE
Notifications page loading as blank 

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#304]
The app is loading a blank notifications screen (screenshot attached). This was noticed by Martyna after the following: 
	
1. App was deleted and re-downloaded. 
2.	Followed onboarding screens to set up the app. 
3.	Selected the Notifications button. 
4.	The page loaded blank
5.	Force closed the app and tried opening again, the screen still loaded blank. 
6.	Accessed Manage Subjects from the Settings and selected subjects to follow. 
7.	After selecting subjects, the notification page loaded with the “you have no notifications” message. 

This happened in both English and French (deleted and re-downloaded the app then set it up in French). 

iPhone X, software version 15.1 
![Notifications screen blank](https://user-images.githubusercontent.com/89025880/152601357-84bf3c37-c781-4f54-bbae-39548ae0c2f6.png)

**Comment by payeisa** [comment]
@Pharste Has this ticket been validated?

**Comment by Pharste** [comment]
@payeisa no, I haven't validated yet. I'll re-open. (It's on my list for tomorrow, and I will get Martyna to validate as well).

**Comment by weglmar** [comment]
Validated on my end, functions as it should!
