### ISSUE TITLE
Enhance message when sharing the app

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#305]
As per accessibility team, the message is not great for accessible users.

**Comment by payeisa** [comment]
Hi Rajat! I believe this can be tracked in ticket 212, 271 or 272.

**Comment by Rajat-Sen** [comment]
Linked with #212, #271, #272 

I think the problem is we are dividing the message into subject and body. Thus, when sharing between different platforms the message gets divided as the subject is not applicable to all the platforms.
