### ISSUE TITLE
Tab bar remains in English while the language has been switched to French

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#309]
When using accessibility controls, the tab bar of the application is read in English even after changing the language to French.

Also, it repeats the unnecessary information when you go from one tab bar icon to another or select another tab bar icon.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Currently it is saying tab bar 1 of 4 and so on as mentioned in this ticket >> https://github.com/StatCan/StatcanPublicationUAT/issues/143  , tab description word is by default.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please confirm the translations:
barre d'onglets = tab bar

**Comment by Rajat-Sen** [comment]
@ForumG-SC, Yes that's the right translation. Thanks!

**Comment by Rajat-Sen** [comment]
Validated!
