### ISSUE TITLE
Publications Screen Level 1 - Max char for titles

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#31]
Can you please confirm that the titles for the articles will not be limited to one line of text only? We should have up to four lines of text. For example:

![image](https://user-images.githubusercontent.com/89025704/133945058-f8c4811c-90de-45eb-b1e6-5dc0fe99635b.png)

Publications Screen Level 1 - Styling changed as per prototype https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/43a64204-945d-4bf4-a0b0-eedc100c4de0 https://github.com/StatCan/StatCanPublication/issues/17

**Comment by ForumG-SC** [comment]
Max Char has been updated unto 4 lines.

**Comment by payeisa** [comment]
Will validate once we have actual data.

**Comment by payeisa** [comment]
The titles on the Home page are still limited to 2 lines. See attached. Note that this is not a priority for consultations, and can be fixed later.

![image](https://user-images.githubusercontent.com/89025704/142662745-4ad1fdf7-5663-426d-ac97-4f0028a45f59.png)

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Validated.
