### ISSUE TITLE
Level-3 enhancement

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#318]
When the user goes to level-3 from any screen. the device should use the default browser instead of using our own custom browser.

Please make sure it is working properly on both the platforms.

**Comment by AJBouzidi** [comment]
@Jiandong-Guo could you check this ticket and add your comment regarding the default browser?

**Comment by Jiandong-Guo** [comment]
Right now, it stays in level 3 browser.

**Comment by Jiandong-Guo** [comment]
But the question is how to open external browser in level 3,

**Comment by zhuelle** [comment]
@payeisa need prioritation.

**Comment by payeisa** [comment]
@zhuelle I would like to get feedback from Rajat on the priority for this one. I'm not sure how badly this is affecting UX, and if it's something that can wait.
@Rajat-Sen Could you please let me know your thoughts on this?

**Comment by Rajat-Sen** [comment]
@payeisa, this is not a priority issue! Thanks!

**Comment by payeisa** [comment]
Thanks @Rajat-Sen !
@zhuelle Prioritization has been completed.

**Comment by weglmar** [comment]
Closing. This would not be relevant if we move towards implementing no web view in the future. It is XLARGE effort, and may just be a temporary solution.
