### ISSUE TITLE
Update Language Screen Buttons  for accessibility

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#320]
Link of updated prototype:
https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/1b03f7d3-db6b-418a-9a55-ce535436baef/specs/

**Comment by ForumG-SC** [comment]
In progress.

**Comment by ForumG-SC** [comment]
Done

**Comment by Rajat-Sen** [comment]
Validated!
