### ISSUE TITLE
Update Terms and Conditions Screen for accessibility

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#322]
https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/f4a0f799-4755-478e-bafb-432b1846f44d

**Comment by ForumG-SC** [comment]
In progress

**Comment by ForumG-SC** [comment]
Done

**Comment by Rajat-Sen** [comment]
Validated!
