### ISSUE TITLE
Launch screen - icon needs to be updated

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#33]
The Launch screen should use the same icon as the one used on the Welcome screen.

![image](https://user-images.githubusercontent.com/89025704/133988644-a1bd238d-ebc6-4527-aef7-93c1837d55a2.png)

**Comment by ForumG-SC** [comment]
Right now we are using screenshots to display the launch icon and welcome icon as we have not received the set of images (.svg) files from Rajat yet.
