### ISSUE TITLE
Cancel button on Search Screen

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#335]
When Search bar is in focused state, the Cancel button that appears is small. 

The text size should be increased and add invisible area around it to make it easier to click.

**Comment by Jiandong-Guo** [comment]
Please do an internal test in next release

**Comment by zhuelle** [comment]
Assign back to Rajat for testing..

**Comment by zhuelle** [comment]
@Jiandong-Guo  is this ticket released in the 1.0.8? I didn't see it in the Sprint 34.

**Comment by zhuelle** [comment]
Based on the conversation with @Jiandong-Guo , this ticket has been released in the 1.0.8.

**Comment by Rajat-Sen** [comment]
Validated!

**Comment by zhuelle** [comment]
@ForumG-SC , this ticket is closed. But it is still showing up in the Sprint back log. Do we need to do anything to get it removed from the backlog?
