### ISSUE TITLE
Search screen bug on Android

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#339]
When the user goes to the search screen, the tab bar moves up when typing something.

The intended functionality is to hide the tab bar and show the keyboard. Screenshot attached for reference.

**Comment by Rajat-Sen** [comment]
![Screenshot_20220328-142648.png](https://user-images.githubusercontent.com/38566088/160464154-15646daf-1234-4d7b-aa92-5b685e280fa0.png)

**Comment by ForumG-SC** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/84411852/169099385-7777e309-8573-453c-9e18-901471a14c30.png)

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Hi Jiandong, I have fixed this issue , please merge the pull request https://github.com/StatCan/StatCanPublication/pull/201, and test and close this ticket as Rajat is not her to test the fix.

**Comment by Rajat-Sen** [comment]
Validated!
