### ISSUE TITLE
Publications Level 2 Screen More icon

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#34]
In the menu at in the top right corner, the contact us button is indented. It should be in-line with the share this publication button ![image](https://user-images.githubusercontent.com/89025880/134392436-72fca713-4160-48f0-9f36-0dec9a541956.png)

Also a note that 'share this publication' has an unnecessary 's' on the end.

**Comment by Pharste** [comment]
![image](https://user-images.githubusercontent.com/89025880/140772356-e4f587c6-4269-4a2c-a127-22a78978a00c.png)

When validating this issue, I found that the more menu cuts off now, not showing the contact us button from the menu.

**Comment by Pharste** [comment]
Seems to be an iOS only issue

**Comment by ForumG-SC** [comment]
@Pharste Fixed. Assigning it back to you for validations.

**Comment by Pharste** [comment]
validated, thank you.
