### ISSUE TITLE
Adjustment of text

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#342]
On settings screen, on both platforms there are following bugs:

1. iOS: Copyright logo is missing.
1a) - The text and the Canada wordmark is not aligned vertically. (Refer to the attached screenshot)

2. Android: 
2a) - Version number of app is not in the aligned horizontally. (Refer to the attached screenshot)
2b) - Similar to iOS, The text and the Canada wordmark is not aligned vertically. (Refer to the attached screenshot)

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/160467457-223e6462-b1f0-49cf-8471-c3a85c869626.png)

**Comment by zhuelle** [comment]
@payeisa need prioritazation.

**Comment by payeisa** [comment]
@zhuelle Priority added.

**Comment by ForumG-SC** [comment]
IOS copyright logo has been added:
![image](https://user-images.githubusercontent.com/84411852/174661589-a238d193-3e6c-4559-ab57-7d937a77c4ef.png)
Android Alignment fixes and copyright logo added:
![image](https://user-images.githubusercontent.com/84411852/174663898-5cb7d2f2-a386-48e9-83d3-6ab2ea1d6725.png)

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please test this on Wednesday once the deployment is done.

**Comment by Rajat-Sen** [comment]
Validated!
