### ISSUE TITLE
Update to Apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#344]
We would like to update the Apple Promo text on April 1 and 27. 

April 1: 
EN: 2021 Census data on Canada's shifting demographic profile will be available April 27, 2022.
FR: Les données du Recensement de 2021 sur la transformation démographique du Canada seront disponibles le 27 avril 2022.

April 27: 
EN: 2021 Census data on Canada's shifting demographic profile are now available!
FR: Les données du Recensement de 2021 sur la transformation démographique du Canada sont maintenant disponibles!

Thanks,
Stephanie

**Comment by ForumG-SC** [comment]
@Pharste April 1 promo text updated.

**Comment by ForumG-SC** [comment]
@Pharste Promo text updated.

**Comment by Pharste** [comment]
Perfect, thanks @ForumG-SC 😃
