### ISSUE TITLE
Notification screen bug

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#346]
When the user goes to Notification screen > click on a notification > Before seeing an article, you can see the empty notification screen for a split second.

Please see the video attached for reference.

**Comment by Rajat-Sen** [comment]
https://user-images.githubusercontent.com/38566088/161044218-58e425d4-16ac-4ecc-9383-f2af2e467c65.MOV

**Comment by Jiandong-Guo** [comment]
Shouldn't exist in new flow. Please test in next release

**Comment by AJBouzidi** [comment]
@Jiandong-Guo same behavior with the current version 1.0.6

**Comment by Jiandong-Guo** [comment]
@AJBouzidi I don't see this problem, It should be fixed already(see comment above)

**Comment by zhuelle** [comment]
I tested on my Android phone as well as iPhone with the version 1.0.6, the issue has been resolved.
