### ISSUE TITLE
Search Results displaying incorrectly (StatsCAN Alpha v1.0.5)

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#348]
The Search Results on the Search page are displaying incorrectly (every second image is not displaying to the right, but underneath, and the date is duplicated). 
App: StatsCAN Alpha (v1.0.5) 

iPhone X, iOS 15.3.1. 

![IMG-7449](https://user-images.githubusercontent.com/98898969/161127614-b68f5751-ed4f-4ffd-8743-91bd29db47df.PNG)
![IMG-7450](https://user-images.githubusercontent.com/98898969/161127668-2a50c194-50ae-46d8-bf35-9100f66570fd.PNG)

**Comment by AJBouzidi** [comment]
@weglmar could you please check this issue. could you close if it's resolved if not assign it back to me .

**Comment by weglmar** [comment]
Validated and closed.
