### ISSUE TITLE
Issues with screen menu tab at bottom in dark/light mode - StatsCAN App (PRD)

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#349]
The screen menu tab at the bottom does not follow the display setting of Dark or Light. If I switch from Dark to Light, then the menu at the bottom remains in Dark mode (image 1 below).
If I switch to Dark, then then menu bar is white and the menu items are not visible (image 2 below).
I first noticed this issue in StatsCAN App (test), and then noticed it was doing the same thing in PRD.

![1](https://user-images.githubusercontent.com/98898969/161260327-dc539b61-c1e7-4f30-9f5f-6ba08231dc81.png)
![2](https://user-images.githubusercontent.com/98898969/161260384-392b8b21-8279-4d1c-b803-5d36e49dd6f0.png)

**Comment by AJBouzidi** [comment]
@weglmar is this still an issue? could you test, I think this is has been fixed by fixing another similar issue.

**Comment by weglmar** [comment]
@payeisa Hi Isabelle, could you please confirm? I believe I submitted this ticket on behalf of you :) Thanks!
