### ISSUE TITLE
Launch & welcome screens: Leading language

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#35]
When launching the app in French, the leading language of the launch screen should be French. Right now it's displayed with English-leading (Statistics Canada / Statistique Canada).

The welcome screen should also be French-leading. Right now, it's English-leading.

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Please look into this ticket so that other ticket can be validated and closed( https://github.com/StatCan/StatcanPublicationUAT/issues/12)

**Comment by ForumG-SC** [comment]
@payeisa Could you please validate this ticket in the current dev version, I just tested : I set my phone's language to Francais and opened the app the leading language is French not English .

**Comment by payeisa** [comment]
@ForumG-SC I deleted my app user profile, changed my device language to French, restarted my device, re-opened the app, and I'm still presented with the English-leading language screen. (Android, Samsung Galaxy S9)

**Comment by ForumG-SC** [comment]
@payeisa After investigating again, I am not able to replicate the issue. The only issue that I can see when the leading language is Francais the buttons ux is off, that will be fixed. But the functionality seems to be working okay, please see the attached screen recording:

https://user-images.githubusercontent.com/84411852/146979537-105f74f6-8c23-433a-893b-aa92beefd63b.mp4

**Comment by ForumG-SC** [comment]
@payeisa UX has been fixed when the leading language is French, it will be reflected in the next release. Please revalidate the functionality based on the screen recording shared above.

**Comment by payeisa** [comment]
@ForumG-SC After uninstalling/reinstalling the app, I was able to validate this issue, and it's behaving as it should. This ticket can now be closed.
