### ISSUE TITLE
StatsCAN Testing (v1.0.2): Red dot disappearing from notifications bell when there are still unread notifications 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#357]
I clicked one of the unread notifications and then navigated back to the Publications screen. The red dot from the bell disappeared, even though I had more unread notifications.

**Comment by AJBouzidi** [comment]
@Rajat-Sen I think this is was done based on the requirement.

**Comment by Rajat-Sen** [comment]
@AJBouzidi Yes, it is working based on the requirements.
