### ISSUE TITLE
Publications Level 1 (Bold)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#36]
I'm not sure what specifically is supposed to change, in article level 1, when I set the text to Bold (on or off), or when I change the size of the text.
 
I'm not noticing any changes to the article level 1 headings. The titles remain the same, regardless.

Header Changes ( Dark Mode , Text Size , Bold ) - to test it go to settings screen and apply the appropriate settings. https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/43a64204-945d-4bf4-a0b0-eedc100c4de0

**Comment by ForumG-SC** [comment]
https://user-images.githubusercontent.com/84411852/134705099-c696e1b5-5b35-4ab8-9d58-6dfc3da2caaa.mp4

Please refer to this video, assigning ticket to you.

**Comment by payeisa** [comment]
Validated Sept 25, 2021.. I was thinking the title of the **articles** were supposed to change, but realize it's only the title of the **screen** that changes.
