### ISSUE TITLE
App not synchronizing with the device

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#360]
When the device is in dark mode, and the app is in light mode, I cannot see the status bar of the device. Please refer to the attached screenshot. 

The app should override system settings when the app is opened in any colour theme.

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/163224090-7f9cb81b-6aec-4b4a-b542-255e21f840e7.png)

**Comment by Jiandong-Guo** [comment]
Please do an internal test

**Comment by Jiandong-Guo** [comment]
in the next new release

**Comment by zhuelle** [comment]
@Rajat-Sen , please test this ticket.

**Comment by Rajat-Sen** [comment]
Working and validated!
