### ISSUE TITLE
Publication screen flashing in dark mode

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#361]
When a publication is loaded, the screen flashes for an instant. It needs to be fixed or use lazy loading. Please refer to the attached video.

**Comment by Rajat-Sen** [comment]
https://user-images.githubusercontent.com/38566088/163224603-718ed156-85ec-4cf4-b23d-ec3d29891dfe.MOV

**Comment by ForumG-SC** [comment]
Fixed.
https://user-images.githubusercontent.com/84411852/171007222-ed77aefc-c55d-4314-b354-9e1b93851a8d.mp4

**Comment by ForumG-SC** [comment]
@Rajat-Sen Assigning it to you for testing.

**Comment by Rajat-Sen** [comment]
I have tested and it is still flashing for me. I have only changed the app colour theme to dark instead of system dark mode. Thanks!

**Comment by ForumG-SC** [comment]
@Rajat-Sen Hi Rajat, when I test it in my phone the solution is working but when I test in the new version 1.0.8 it is not working, I was not here when the new version was deployed last time. I will further investigate on this. Thanks.

**Comment by ForumG-SC** [comment]
@Rajat-Sen I am not sure if the fix was deployed to the current version due to which you are still seeing the flash, however please test this in the release tomorrow.

**Comment by ForumG-SC** [comment]
> @ForumG-SC what is the status of this ticket? Seems the work has been done and waiting for testing confirmation. It is in the backlog currently.

I will have quick word with Rajat today and update the status here.

**Comment by Rajat-Sen** [comment]
Closing the ticket as discussed!
