### ISSUE TITLE
StatCan Publications heading (Bold)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#37]
If I set the "Bold" option to off, all the headings within the app will change to not bold, except for the "StatCan Publications" heading on the home screen.

However, if I change the text size (to ether bigger or smaller), the "StatCan Publications" heading will adjust accordingly.

**Comment by ForumG-SC** [comment]
Investigating the issue, in progress.

**Comment by ForumG-SC** [comment]
Resolved, the changes will be deployed in the upcoming release. Assigning it back to you.

**Comment by payeisa** [comment]
Validated Sept 25, 2021.
