### ISSUE TITLE
Investigate Production Release options

### ISSUE THREAD

**Issue by zhuelle** [StatCan/StatcanPublicationUAT#377]
The client would like to know what should be the process if not all tickets that are released in any versions in Internal Testing can be signed off. For example, if 10 tickets has been released for internal testing, only 8 tickets got tested and signed off by the business clients, should the version with 8 tickets signed off and 2 tickets not signed off to be released to Production or should the version be released to Production once all 10 tickets to be signed off? Is it possible to roll back changes for the 2 tickets that not signed off with current branching strategy?

Jiandong, please research the current industry standards and provide options.

**Comment by Jiandong-Guo** [comment]
@zhuelle , the document was created in https://confluenceb.statcan.ca/display/SPMA/Deployment+strategy

**Comment by ForumG-SC** [comment]
https://confluenceb.statcan.ca/pages/viewpage.action?pageId=960606568

**Comment by Jiandong-Guo** [comment]
A test sample:
