### ISSUE TITLE
Pub screen level 3 navigation buttons

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#38]
When on the first page of a level 3 publication, the navigation buttons are greyed out as they should be, but I noticed when navigating one page forward, both of the arrows turn black as if they're available. I think only the back button show as available, and not the forward since there's no where to navigate forward? 

![image](https://user-images.githubusercontent.com/89025880/134422633-f726b98e-85c3-41ff-8efa-9696f19bda31.png)
![image](https://user-images.githubusercontent.com/89025880/134422646-f79118b8-fb5c-4c09-9d4b-c5e0d9502a76.jpeg)

**Comment by ForumG-SC** [comment]
Investigating this issue, in progress.

**Comment by ForumG-SC** [comment]
Resolved, changes will be deployed in the upcoming release.

**Comment by ForumG-SC** [comment]
@Pharste This issue has been resolved and requires validation, assigning it back to you. The changes will be deployed in the upcoming release.
