### ISSUE TITLE
StatsCAN (v1.0.9): Article level 2 opening from Publications screen mid-text 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#382]
Hello, 
In the new release, when I open articles they do not open as expected on the level 2 page. 
The article opens mid-text, often times cutting off the title. 

This seems to only be happening on Apple devices and with long articles that require scrolling. 
Testing on iPhone X, iOS 15.5. 

**Example 1:** 

1. I selected the "Homeownership: sure, but at what cost?" article

![image](https://user-images.githubusercontent.com/98898969/172913575-e79e4689-5bea-47d1-927b-d4785e6b88bb.png)

2. The article opened on the 2nd level Publication screen displaying text first. I had to scroll up to see the title. 

![image](https://user-images.githubusercontent.com/98898969/172913773-26f41e07-9de0-4eb7-bb87-a26c712f8107.png)

**Example 2:** 

1. I scrolled down to the "Update: Canadians' Health and COVID-19: Interactive Dashboard" and selected it 

![image](https://user-images.githubusercontent.com/98898969/172913952-c7045cb5-ebbb-47e5-97b5-0c7c12958a3e.png)

2. The article opened on the 2nd level Publication screen cutting off the title. Had to scroll back up to see it. 
![image](https://user-images.githubusercontent.com/98898969/172914077-9820dc44-bcb8-45df-bd34-a8537b49aebe.png)

FYI @Pharste @Rajat-Sen @levegab @payeisa

**Comment by zhuelle** [comment]
@weglmar would you please confirm this is a blocker or high priority ticket that the dev team has to fix the issue before any production deployment? thanks!

**Comment by zhuelle** [comment]
@weglmar Forum can fix the issue by deploying another version tomorrow. would you please confirm if this works for the business team and not interrupting your testing? Thanks!

**Comment by weglmar** [comment]
@zhuelle Confirming we are okay with deploying another version tomorrow. Thank you!

**Comment by Jiandong-Guo** [comment]
@ForumG-SC,It is related to #361,reverse the code(#Uat361), should be OK

**Comment by ForumG-SC** [comment]
@weglmar Please update the app and test this ticket, fix has been applied and deployment is done.

**Comment by weglmar** [comment]
Functions as expected now. Thank you!
