### ISSUE TITLE
Blinking white screen when loading in dark mode

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#385]
When in dark mode, and a user first goes to a Publication (Level 2 article), the screen goes white/blank for a split second before the story appears (see below). 

![DarkMode-White Screen](https://user-images.githubusercontent.com/106617357/173611753-f308105e-37ce-497b-a9fc-cf43903f4c5f.png)

**Comment by Pharste** [comment]
Here's a video of the issue: 

https://user-images.githubusercontent.com/89025880/173620984-56581f33-ac08-4f75-acb3-bbe0f1758fed.mov

**Comment by Jiandong-Guo** [comment]
Same issue as #361

**Comment by ForumG-SC** [comment]
@levegab closing this ticket as it is duplicate to https://github.com/StatCan/StatcanPublicationUAT/issues/361
