### ISSUE TITLE
StatsCAN (v1.0.9): Colour Issues in Dark Mode (For You)

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#386]
When in “For you” and “Following” in dark mode, if the user only selects one subject, the screen colour for half the screen is white (see attached).  This is resolved if the user selects multiple subjects. 

![Testing-FYP-Colour](https://user-images.githubusercontent.com/106617357/173615003-cb6b2132-f561-41bb-abff-1afd2784105e.jpg)

**Comment by levegab** [comment]
Tagging @Rajat-Sen as this is design-related.

**Comment by Rajat-Sen** [comment]
The background behind the article should be extended to the bottom.

**Comment by zhuelle** [comment]
Require Prioritization.

**Comment by payeisa** [comment]
Priority added.

**Comment by weglmar** [comment]
Closing as this particular issue has been resolved
