### ISSUE TITLE
French button off on Pixel 3

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#388]

**Comment by zhuelle** [comment]
Need priority.

**Comment by payeisa** [comment]
Priority added.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Fixed, here is the screenshot from Pixel 3 emulator:
![image](https://user-images.githubusercontent.com/84411852/179811576-6d2808b9-80e1-4b3f-a0a0-a63fbbdf4c75.png)

Same issue was detected in the device Android S9 by @levegab in the ticket https://github.com/StatCan/StatcanPublicationUAT/issues/434

It has been fixed, here is the screenshot from the Android S9 emulator:
![image](https://user-images.githubusercontent.com/84411852/179811879-891761b9-ac04-49fd-9607-b5647a6d854c.png)

However, it might vary in real device, please test the ticket in your device in tomorrow's release. Thanks.

**Comment by Rajat-Sen** [comment]
Validated!
