### ISSUE TITLE
Flashing Settings screen

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#390]
When the user goes to For you screen first time > Taps Select subjects > user can see the Settings screen flashing. 

It can be replicated on iOS and Android both. Please see the attached video for reference.

**Comment by Rajat-Sen** [comment]
https://user-images.githubusercontent.com/38566088/173675482-4c178528-4bac-4d39-baa9-10230f341a4c.mp4

**Comment by zhuelle** [comment]
@giftydeep I saw your picked up this ticket without priority. Would you please provide a work effort estimate on the ticket so that I can ask business to provide a priority on it.

**Comment by zhuelle** [comment]
Need prioritization.

**Comment by payeisa** [comment]
Priority added.

**Comment by Rajat-Sen** [comment]
Closing this ticket for now as we are going to change it.
