### ISSUE TITLE
Search screen bug again!

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#392]
When the user goes to search screen for the first time and taps on Search input field. The text shifts down to the middle of screen. On some devices, the image disappears after taping on Search screen. 

Attached videos for reference:

**Comment by Rajat-Sen** [comment]
https://user-images.githubusercontent.com/38566088/173677883-0d4ce09d-8695-44e9-acca-454b4baf035f.mp4

**Comment by Jiandong-Guo** [comment]
@Rajat-Sen ,Right now it is the way it works.   When user taps the input text box, the image will be removed, because the keyboard will squeeze the image space. it is not possible to keep displaying keyboard and this image without cut-off and keep its original display ratio.

**Comment by zhuelle** [comment]
@Jiandong-Guo have you worked on this ticket? if not, please assign back to me. This ticket is requiring prioritization from the business.

**Comment by zhuelle** [comment]
Need prioritization.

**Comment by payeisa** [comment]
Priority added.

**Comment by Rajat-Sen** [comment]
Closing this ticket for now as we are going to change it.
