### ISSUE TITLE
Padding for clear text icon

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#395]
In the search input field, clear text button on the right should have padding of 4px.

**Comment by Rajat-Sen** [comment]
![image](https://user-images.githubusercontent.com/38566088/173680232-39c99b32-7985-4186-af33-3ab10ab5321b.jpeg)

**Comment by Rajat-Sen** [comment]
Still cannot see any changes

**Comment by giftydeep** [comment]
@Rajat-Sen This ticket was not included in this version. Please test in the next release.

**Comment by Rajat-Sen** [comment]
Validated!
