### ISSUE TITLE
DUE JULY 13: Update Apple Promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#398]
Hi,

We would like to update the Apple promo text on June 22 with the following: 

EN: 2021 Census: Portrait of Canada's families and households, the Canadian Military Experience, and the income profile of Canadians will be available July 13, 2022.

FR: Recensement de 2021 : Le portrait des familles et des ménages du Canada, l’expérience militaire et le profil du revenu des Canadiens seront disponibles le 13 juillet.

Following this, please update the text on Wednesday, July 13, to:

EN: 2021 Census: Portrait of Canada's families and households, the Canadian Military Experience, and the income profile of Canadians are now available!

FR: Recensement de 2021 : Le portrait des familles et des ménages du Canada, l’expérience militaire canadienne et le profil du revenu des Canadiens sont disponibles!

Thank you!

**Comment by ForumG-SC** [comment]
@Pharste Assigning it back to you, June 22nd promo text has been updated

**Comment by Pharste** [comment]
Thank you Forum! closing this ticket for now and will re-open for the July 13th update.

**Comment by ForumG-SC** [comment]
@Pharste Hi Stephanie, the promo text was updated this morning at 7:00 am, could you please confirm if you see it live in the stores? If so, than we can close this ticket. Thanks.

**Comment by Pharste** [comment]
Thank you @ForumG-SC ! I see it live, and will close the ticket.
