### ISSUE TITLE
Investigate desktop version of StatsCAN app 

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#399]
Hi, 

As discussed in our Comms/IT meeting on June 16, please investigate the 500 desktop downloads from the Apple store on June 9.

I've attached a screenshot of the store analytics, filtered by type 'desktop'. 

It appears these were from an institutional purchase.
(https://apple.stackexchange.com/questions/428955/what-is-meant-by-institutional-purchase-in-app-store-connect)

![Desktop devices June 9](https://user-images.githubusercontent.com/89025880/174099989-7a323aa7-2bda-4885-998a-392594611a1a.png)

**Comment by ForumG-SC** [comment]
@Pharste Hi Stephanie, apple have updated/added option on the app store side which is as follow:
![image](https://user-images.githubusercontent.com/84411852/174600112-ebbcdc1d-fe95-46db-a5e8-83e67634deb4.png)
https://help.apple.com/app-store-connect/#/dev275598f16
When the app is selected as public, app will be publicly available on the App Store in the territories you selected and available to anyone for volume purchase through Apple Business Manager or Apple School Manager.
Currently, it is by default selected public.

**Comment by ForumG-SC** [comment]
@Pharste Do you want to leave this option as default or want to make it private?

**Comment by Pharste** [comment]
@ForumG-SC Can you please confirm if they're showing as desktop versions due to the distribution method? I'm not sure if I understand the connection?

As long as there is no desktop version available as discussed when the app first launched, I think we should be ok to leave it as is.

**Comment by ForumG-SC** [comment]
@Pharste I have reached out to apple to confirm the same, I will post screenshot of their response once I receive it. Thanks.

**Comment by ForumG-SC** [comment]
@Pharste 

![Image](https://user-images.githubusercontent.com/84411852/177564690-a5caec93-cf69-48d7-9533-ff3c1cafe7c8.png)

**Comment by ForumG-SC** [comment]
@Pharste Hi Stephanie, could we close this ticket ?

**Comment by weglmar** [comment]
HI @ForumG-SC, is it possible to clarify if by purchasing through iTunes via PC or Mac, this means it can also be used on PC or Mac? We would not want this to be the case, Thank you!

**Comment by ForumG-SC** [comment]
> is it possible to clarify if by purchasing through iTunes via PC or Mac, this means it can also be used on PC or Mac? We would not want this to be the case, Thank you!

@weglmar I have contacted apple to clarify it for us, we can expect to get a reply within a day or two. Thanks.
![image](https://user-images.githubusercontent.com/84411852/182398332-16942c26-ed4a-4191-be0c-f081c58fead7.png)

**Comment by weglmar** [comment]
Thank you, @ForumG-SC :)
