### ISSUE TITLE
For you screen - unable to click on articles

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#40]
After running through the testing scenario of selecting price and price indexes and economic accounts, I am unable to click on the articles, and the formatting is off (pushed into the right side). ![image](https://user-images.githubusercontent.com/89025880/134424688-36a7126f-a7e2-4095-adca-797928d42809.png)

**Comment by ForumG-SC** [comment]
@Pharste Did you try clicking on the reading icon , that should open the article  and you can swipe the bottom articles

**Comment by Pharste** [comment]
Hi, I tried clicking on the reading icon and it does open the article. Will this button be removed in a later release? Based on the prototype design, we should be able to click the article the same as the home page to open it. 
Thank you for confirming the UX has not been implemented. I will validate formatting once it has. :)
