### ISSUE TITLE
Light mode colours

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#401]
Button colours on the Following screen and Saved screen, Search screen (Save button, when filtered by subjects) is not matching with the Onboarding screens.

On Publication screen, the link colour is not matching with the prototype.

**Comment by payeisa** [comment]
Priority added.

**Comment by Rajat-Sen** [comment]
https://xd.adobe.com/view/e44f62bb-61f7-4195-bc45-a0276a0731c9-b11c/

**Comment by giftydeep** [comment]
@Rajat-Sen I am using the same color code for the links. But not sure why it looks different. Please see the attached image and lemme know if you want me to change it to original.

![Image](https://user-images.githubusercontent.com/8207028/193727900-09571aaa-43bc-4c09-8858-3c7c5576e253.jpg)

**Comment by Rajat-Sen** [comment]
Hi @giftydeep, are we able to assign this colour instead of the colour you proposed in the image?

**Comment by giftydeep** [comment]
This works. Please test in the next release.

**Comment by zhuelle** [comment]
@Rajat-Sen What is the status of this ticket? Need any modification? Thanks!

**Comment by Rajat-Sen** [comment]
Yes, it will need some modification and I will provide Hex codes for colours. Also, might need to work closely with the developers for colours accuracy.

**Comment by weglmar** [comment]
In light mode, on the Publications screen now the boxes have disappeared around the publication cards, making it hard to see the card. 
 
![image](https://user-images.githubusercontent.com/98898969/213729161-bab71ca0-b143-4e09-8d91-71404794aaa2.png)

When saving a Publication, and then Unsaving, the message that appears is very difficult to see. 

![image](https://user-images.githubusercontent.com/98898969/213729515-461fb915-f7b5-41fb-9790-7e7c50b47b74.png)

![image](https://user-images.githubusercontent.com/98898969/213729631-4fe2557e-35dc-47be-b148-d462c1b9377c.png)

**Comment by Pharste** [comment]
New ticket created, closing this as requested. Thanks!
