### ISSUE TITLE
Dark mode colours

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#402]
The colour of following items needs to be updated.

App Level :
1. Background
2. Buttons

Publications:
1. Card 

Publication:
1. Links
2. Button at the bottom
3. Menu options

Search screen:
1. After searching, the sort and Filter by subjects button
2. Menu options of Sort button
3. Save button when clicked on Filter by subject(s).

For you:
1. Buttons

**Comment by payeisa** [comment]
Priority added.

**Comment by Rajat-Sen** [comment]
#386, @giftydeep While you are working on this ticket, would you be able to look at this issue as well?

If the user selects only one subject in dark mode, the rest of the foreground colour stays white and it's bad UX.

**Comment by levegab** [comment]
I can see that the hyperlink colour has been updated to purple in 3.0.2. This is difficult to read on dark mode, and is typically the colour of hyperlink after you've clicked the link. We recommend a slightly light blue than the one used in 3.0.1.

**Comment by zhuelle** [comment]
@Rajat-Sen are you planning to provide the proper color code? Thanks!

**Comment by Rajat-Sen** [comment]
Yes, I will provide the hex code colours for both the modes.

**Comment by weglmar** [comment]
When clicking on heart, the "added to saved menu on For you screen" and "Removed" messages don't have a box around the text. The message is hard to see. 

![image](https://user-images.githubusercontent.com/98898969/213733438-ac295cbc-3f5c-41cc-a489-a68ae52deada.png)

![image](https://user-images.githubusercontent.com/98898969/213733829-ff16197a-b67a-41f2-a496-6a6eccaf6725.png)

**Comment by weglmar** [comment]
Validated.
