### ISSUE TITLE
Cannot see the prompt after marking all notifications as read

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#403]
After following a subject, when the user sees notifications and presses. All notifications, marked as read; the user cannot see the message.

For reference: https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/726296dc-7d63-4365-9c04-2c29ecd1cb6f

**Comment by zhuelle** [comment]
Need priority.

**Comment by Rajat-Sen** [comment]
Validated!
