### ISSUE TITLE
UX iPad issues: v 1.0.10

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#414]
Hi, 

As mentioned this morning, the display on iPad seems off on several screens. (Please see images attached)

Is it possible to reduce the size of the text? It seems quite large, especially vs. the web browser view of the publications when clicking through the 'continue reading' link. 

Thanks,
Stephanie

![1](https://user-images.githubusercontent.com/89025880/175391227-c3ba4098-0553-456c-98f9-39d8595ca85e.png)
![2](https://user-images.githubusercontent.com/89025880/175391237-ae00bf87-7d41-4604-97f0-f4f9803c039e.png)
![3](https://user-images.githubusercontent.com/89025880/175391244-b0673ff0-e0fc-43c3-8894-c4ad307ee10e.png)
![4](https://user-images.githubusercontent.com/89025880/175391251-f69d8f1f-ae93-4ab0-9e31-2814b762b6d8.png)
![5](https://user-images.githubusercontent.com/89025880/175391257-249f2972-459f-45be-82f1-63306c579778.png)
![6](https://user-images.githubusercontent.com/89025880/175391264-c032777d-aa2c-4e88-959d-162fa3ac0631.png)
![7](https://user-images.githubusercontent.com/89025880/175391278-8562f358-12f0-4882-a74d-9cc2e7954849.png)
![8](https://user-images.githubusercontent.com/89025880/175391284-0f0a1157-1371-4a5b-b283-62bb514479fc.png)

**Comment by Pharste** [comment]
@Rajat-Sen Can you please add additional information on what should be changed to match the prototype?

@weglmar @levegab @payeisa FYI

**Comment by payeisa** [comment]
Priority added.

**Comment by payeisa** [comment]
Sorry - assigned priority to wrong ticket.

**Comment by payeisa** [comment]
@Rajat-Sen I would like for us to fix the issues as soon as possible, if that's feasible. However, I'm not sure I understand what you mean re: designing a separate app for tablets? Would that mean two separate apps for StatCan in the stores?

**Comment by Rajat-Sen** [comment]
@payeisa Sure, let's start with decreasing the font size on the tablets. 

We will only have one app however, when the user is going to open the app on a tablet, it will adjust the layout accordingly. 
Redesigning a separate apps is referring to a separate prototype for tablets. 

I am going to create a new ticket for that as tablets have different guidelines.

**Comment by payeisa** [comment]
@Rajat-Sen Thanks for confirming!
@zhuelle Priority added.

**Comment by Jiandong-Guo** [comment]
@payeisa Please tell me the tablet name(I mainly need the screen size).   Also what do you mean "the display on iPad seems off on several screens" ?  all those screens(images above) are scrollable,  same as that in phone.
What I will do is to change the font size for tablets

**Comment by weglmar** [comment]
@Pharste could you please provide Jiandong with: 
Device Type
Device Screen Size
Device Screen Resolution

@Jiandong-Guo Stephanie will provide the information, she was testing on her iPad. As for the screens, the font is not consistent. For example, "Search publications" seems very small compared to the magnifcying glass and other text on the page. 

![image](https://user-images.githubusercontent.com/98898969/185471548-0828fb60-0c1e-4cc9-a7da-7cbf7e768459.png)

The text seems very large here too: 

![image](https://user-images.githubusercontent.com/98898969/185471762-69b101b2-37ae-430b-a13a-f5815df4b3ef.png)

I think this ticket is related to #427  which Dilpreet is working on. 

Thanks!

**Comment by Pharste** [comment]
@Jiandong-Guo I was testing on iPad Pro (12.9 inch) (4th generation), resolution 2048x2732 px

**Comment by Jiandong-Guo** [comment]
This is the screenshot when text size set to min(It's very small already):
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-08-23 at 10 42 08](https://user-images.githubusercontent.com/58485300/186188948-68ec51ca-0343-41ca-b2e8-a15e27fb02d6.png)

**Comment by Pharste** [comment]
all major issues appear to be resolved. Thank you!
