### ISSUE TITLE
Onbording package documentation

### ISSUE THREAD

**Issue by zhuelle** [StatCan/StatcanPublicationUAT#417]
This ticket is to track the progress of creating on-boarding documentation package for any new mobile app developer. 

https://confluenceb.statcan.ca/display/SPMA/Mobile+application+Onboarding+Process

**Comment by zhuelle** [comment]
@giftydeep what's status of this ticket? Thanks!

**Comment by giftydeep** [comment]
Closing this ticket as the onboarding document we have is up to date and require no more changes.
