### ISSUE TITLE
For you Screen- Following Screen - Remove extra spaces above the select subjects button

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#418]
Issue detected in IOS:
The cause of this issue seems to be, after the changes were done in the Following screen file,Line 42,248 .
Commit id : 1fc6a1f6dc668880ca985e789c3e6e7d0cadfa4a
Once resolved, please test this in different screen sizes in IOS and android.

Current Screen:
![image](https://user-images.githubusercontent.com/84411852/176185161-0fe112c1-056a-4f1a-b93b-24f9273688ed.png)

Expected Screen:
![image](https://user-images.githubusercontent.com/84411852/176248431-38503406-e522-4ad8-b6c8-fdfa56ffbca2.png)

Ref:  https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/55cd66da-e424-4b99-90d2-451edc7fedc7/specs/

**Comment by Jiandong-Guo** [comment]
This is iPhone 12 Pro:
![Simulator Screen Shot - iPhone 12 Pro - 2022-06-28 at 10 14 08](https://user-images.githubusercontent.com/58485300/176201108-2061348c-76e0-4448-bada-38c644440ba1.png)

This is iPad Pro(12.9-inch):
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-06-28 at 10 17 05](https://user-images.githubusercontent.com/58485300/176201791-521377a4-60c7-479d-af26-c30bd5151a86.png)

**Comment by Jiandong-Guo** [comment]
This is iPhone 8
![Simulator Screen Shot - iPhone 8 - 2022-06-28 at 10 40 49](https://user-images.githubusercontent.com/58485300/176207983-c02a70cc-3768-43a5-9343-bb294011fc3b.png)
:
This is iPhone 6s:
![Simulator Screen Shot - iPhone 6s - 2022-06-28 at 10 43 44](https://user-images.githubusercontent.com/58485300/176208458-cc4c808b-0952-4be6-9d02-1c7b494e7387.png)

**Comment by ForumG-SC** [comment]
@Rajat-Sen Can you please share the ux prototype link of the following screen?

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Before it used to look like this :
![image](https://user-images.githubusercontent.com/84411852/176217036-45cf59bc-587d-48d0-b307-ca968798b896.png)

Now there is lot of spacing

**Comment by ForumG-SC** [comment]
> This is iPhone 8 ![Simulator Screen Shot - iPhone 8 - 2022-06-28 at 10 40 49](https://user-images.githubusercontent.com/58485300/176207983-c02a70cc-3768-43a5-9343-bb294011fc3b.png) : This is iPhone 6s: ![Simulator Screen Shot - iPhone 6s - 2022-06-28 at 10 43 44](https://user-images.githubusercontent.com/58485300/176208458-cc4c808b-0952-4be6-9d02-1c7b494e7387.png)

lot of extra spacing is there

**Comment by ForumG-SC** [comment]
> @ForumG-SC ,where is the cut off? which simulator do you see the cut off ?

I see extra spacing before the select subject button in multiple simulators such as iphone 11,11pro,12 etc.

**Comment by Jiandong-Guo** [comment]
Ok, What you want to change is to remove the space above the select subject button.

For iPad Pro 12.9-inch:
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-06-28 at 13 23 45](https://user-images.githubusercontent.com/58485300/176245215-477d4608-caca-4184-b9d0-6de3dbcaae36.png)

For iPhone 12 Pro:
![Simulator Screen Shot - iPhone 12 Pro - 2022-06-28 at 13 22 38](https://user-images.githubusercontent.com/58485300/176245442-1a63fdda-118a-48d8-bc73-d21dea843527.png)

**Comment by Jiandong-Guo** [comment]
For Android pixel 5:
![Screenshot_1656437358](https://user-images.githubusercontent.com/58485300/176246196-1132ff24-87f5-4e93-b9cf-bf99e41c06aa.png)

For Android 8 fold-out:
![Screenshot_1656437574](https://user-images.githubusercontent.com/58485300/176246511-65a06a2e-0065-4d6b-883f-2a4cadcff671.png)

**Comment by ForumG-SC** [comment]
> Ok, What you want to change is to remove the space above the select subject button.
> 
> For iPad Pro 12.9-inch: ![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-06-28 at 13 23 45](https://user-images.githubusercontent.com/58485300/176245215-477d4608-caca-4184-b9d0-6de3dbcaae36.png)
> 
> For iPhone 12 Pro: ![Simulator Screen Shot - iPhone 12 Pro - 2022-06-28 at 13 22 38](https://user-images.githubusercontent.com/58485300/176245442-1a63fdda-118a-48d8-bc73-d21dea843527.png)

@Rajat-Sen Could you please verify the above screenshots matches your prototype before the deployment? Thanks

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Please match the spaces with the prototype: 
https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/55cd66da-e424-4b99-90d2-451edc7fedc7/specs/
![image](https://user-images.githubusercontent.com/84411852/176246846-8ab89578-2757-464a-ae94-902f226e2604.png)

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo, 
1. Please make the text centered instead of aligning it to the left.
2. Leave margin from all sides to have some space from Top, right, bottom and left
3. Between the text "Stay informed! Select your subjects of interest to automatically receive the latest info" and the button "Select subjects" add some space but no too much. For instance, in the prototype I have there is space of 24px.

If you have any questions, let me know.

**Comment by Jiandong-Guo** [comment]
@Rajat-Sen ,
1)text align center:done,    
2)Horizontal margin added 16, vertical margin add 6,
3)space between button and text added 14,plus the bottom 6 in 2) total 20px, (vertical height is valuable especial for almost square screen )
iPad:
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-06-28 at 14 54 47](https://user-images.githubusercontent.com/58485300/176261771-e11e7acc-8912-47ee-bb1a-f27a38362b73.png)
iPhone:
![Simulator Screen Shot - iPhone 12 Pro - 2022-06-28 at 14 56 14](https://user-images.githubusercontent.com/58485300/176261857-89fb2f14-537c-45ed-8b2e-3326713a8372.png)

**Comment by Jiandong-Guo** [comment]
android phone:
![Screenshot_1656442128](https://user-images.githubusercontent.com/58485300/176262582-3c234b81-e2c9-4633-
![Screenshot_1656442232](https://user-images.githubusercontent.com/58485300/176262734-1c49c0de-98c6-4f5c-87f9-26ac489faa7e.png)
8786-d80558b9bbe7.png)
Android tablet:

**Comment by Jiandong-Guo** [comment]
@ForumG-SC ,Please test
