### ISSUE TITLE
Confirm spelling on Language screen

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#419]
In French, please confirm the spelling is “Selectionnez” before selecting any language button.

**Comment by zhuelle** [comment]
Need Prioritization.

**Comment by payeisa** [comment]
@Rajat-Sen Can you please provide a bit more details? Where is "Selectionnez" displayed? i.e. I went to Settings - Language - French. If used by screen readers, I would also need the context in which the word is being used as well. Thanks, Isabelle

**Comment by payeisa** [comment]
@Rajat-Sen In English, the screen reader should read "Select English" or "Select Français", and in French, the screen reader should read "Sélectionnez Français" or "Sélectionnez English".

**Comment by Rajat-Sen** [comment]
@payeisa Thanks!

**Comment by giftydeep** [comment]
We are already using the correct spelling of "Selectionnez" for the select language in French. This ticket can be closed. Please confirm @Rajat-Sen.

**Comment by Rajat-Sen** [comment]
Sounds great, Thanks!

**Comment by giftydeep** [comment]
@payeisa it is "selectionnez" not "sèlectionnez" (with an accent on the "e"). If required I can update it.

**Comment by Rajat-Sen** [comment]
@giftydeep, Validated!
