### ISSUE TITLE
StatsCAN (v1.0.11): Loading Screen - Text Overlap (Android)

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#434]
The language toggle needs to be repositioned to not overlap at the top of the screen. See example in image attached. Device used: Android S9
![Screenshot_20220707-072728_StatsCAN](https://user-images.githubusercontent.com/106617357/178041513-9dda7c8d-db08-415e-85f5-ad6461c3c58b.jpg)
.

**Comment by payeisa** [comment]
@zhuelle I prioritized this ticket - can IT please add a t-shirt size? Thanks, Isabelle
@weglmar FYI

**Comment by levegab** [comment]
That is correct @zhuelle.

**Comment by ForumG-SC** [comment]
@levegab This ticket can be closed as it is duplicate ticket, refer to https://github.com/StatCan/StatcanPublicationUAT/issues/388

**Comment by zhuelle** [comment]
@levegab Would you please confirm if the ticket is duplicate? If yes, please close this one. Thanks!

**Comment by weglmar** [comment]
Duplicate
