### ISSUE TITLE
StatsCAN (v1.0.11): Terms of Use - Dark Mode Doesn't Display Properly

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#435]
During onboarding, the Terms of Use screen does not display properly in dark mode (see attached).

Happening on Samsung S9 (phone) and iPhone X, iOS 15.5 when devices are in dark mode. 

![Screenshot_TermsofUSe](https://user-images.githubusercontent.com/106617357/178041798-dbef4b45-3acc-4498-8650-4eb54b72a8a1.jpg)

**Comment by payeisa** [comment]
@zhuelle I prioritized this ticket - can IT please add a t-shirt size? Thanks, Isabelle
@weglmar FYI

**Comment by ForumG-SC** [comment]
Related to https://github.com/StatCan/StatcanPublicationUAT/issues/315

**Comment by levegab** [comment]
This issue has been resolved.
