### ISSUE TITLE
Read content in landscape mode

### ISSUE THREAD

**Issue by lamokar10** [StatCan/StatcanPublicationUAT#439]
https://confluenceb.statcan.ca/display/SPMA/Feature+x.x+Read+content+in+landscape+mode

**Comment by radwahm** [comment]
Documentation complete. Awaiting sign off.

**Comment by weglmar** [comment]
Signed off on August 9.

**Comment by zhuelle** [comment]
Hi, I would like to confirm that this ticket has its specification completed and signed off by the business. Therefore it should be in Ready for Development status instead of Resolve. Thanks!

**Comment by weglmar** [comment]
@zhuelle yes, it has been signed off. Thank you, Ellen. Moving forward I will ensure I remove the waiting for business sign off label and will assign the ticket back to @radwahm

**Comment by weglmar** [comment]
@ForumG-SC thank you, Forum. I can confirm it's not working for those of us who have iOS devices. I see that the issue was reported by others back in November 2021 and there has still not been a fix. This means we can still be waiting a while? Are there any other solutions for iOS or the only option is to wait?

**Comment by weglmar** [comment]
Hi @ForumG-SC, 

Here are my findings: 

Device Type: iOS (iPhone X) 
Device Screen Size: 5.8 inches 
Device Screen Resolution: 2436 x 1125 
Device’s OS version info: 15.5 

Empty space on the notification card on the Notifications screen: 
![image](https://user-images.githubusercontent.com/98898969/194067245-719d0a04-b3bf-48de-b22f-8f50b66e7853.png)

Publications header on Publications screen: 

![image](https://user-images.githubusercontent.com/98898969/194067899-74ebdb56-10d7-41b6-b300-4e4dcc7c8694.png)

For You screen: 
![image](https://user-images.githubusercontent.com/98898969/194068094-4e8a5750-ffe5-4ff8-90f5-f95834bfd62f.png)

Search screen: 
![image](https://user-images.githubusercontent.com/98898969/194068316-c4470527-015d-46ab-8431-8b5fb8268144.png)

**Comment by weglmar** [comment]
@ForumG-SC okay, that makes sense! thank you 

Closing as per above, all functionality works.

**Comment by weglmar** [comment]
@ForumG-SC thank you :)
