### ISSUE TITLE
Publications Screen Level 2 : Save icon in the header

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#44]
When I click on the heart icon to add an article, the pop up message should be "Added to saved items."

Testing Scenario 1: Click on heart icon , banner should appear saying "Added to the saved items" and clicking the cross button in the banner should dismiss the pop-up.

**Comment by ForumG-SC** [comment]
In the latest version the banner has been removed and replaced with the toast message.

**Comment by payeisa** [comment]
Validated Oct 04, 2021.
