### ISSUE TITLE
Provide translation for back button in French

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#443]
When using voiceover in French version of the mobile app, the back button has not been translated and please provide the correct translation. 

In English the label we use is "Go back" button.

**Comment by zhuelle** [comment]
Hi @Rajat-Sen , do we need the translation from the business? If yes, I will assign to the business.

**Comment by Rajat-Sen** [comment]
@zhuelle Yes, please assign this ticket to business.

**Comment by zhuelle** [comment]
@weglmar I assign this ticket to you to get proper French translation as required. Also, if you can ask Isabelle to assign a priority to this ticket after will be great, Thanks!

**Comment by weglmar** [comment]
Hello, the French translation is " revenir en arrière "

**Comment by Rajat-Sen** [comment]
Validated!
