### ISSUE TITLE
Change app compatibility in Google Play Store

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#444]
To remain consistent with our FAQ on the website, could the "Requires Android" portion in the "About this app" section on the Google Play Store be modified to 7.0 and up? 
Thank you!

![image](https://user-images.githubusercontent.com/98898969/178977420-13541707-0b30-46b4-a70f-77a74b5553c1.png)

@payeisa assigning for priority :)

**Comment by zhuelle** [comment]
@weglmar I would like to confirm if you would like to change the Android version to 7.0 and up on the StatsCan web site as it currently shows 5.0 and up (from the attached picture)? Based on Forum, after EAS build migration, we can only be able to support Android 7.0 and up. Thanks!

**Comment by ForumG-SC** [comment]
@weglmar Fix has been applied, please test it in the next release. Thanks.

**Comment by weglmar** [comment]
![Image](https://user-images.githubusercontent.com/98898969/182910725-ee8b492d-cb77-4c0e-9e81-e394f57e4106.png)

Android 5.0 and up is still displaying on my end

**Comment by zhuelle** [comment]
@weglmar I believe this page is not managed by the mobile dev team. You need to contact dissemination to get it changed.

**Comment by weglmar** [comment]
@zhuelle the screenshot is from the Google Play Store - https://play.google.com/store/apps/details?id=com.statcan.StatCan. Is that managed by DISS?

**Comment by weglmar** [comment]
@ForumG-SC Hi Forum, thank you for the information. That makes sense about having to deploy to see the change, I didn't think of that :) 

For Android version 12 and up - What does this mean for our app users? If they are not on Android 12, what will happen? Will the app not function at all? Will we potentially lose users? 
Also, what is the est. development effort/time? 

Thanks!

**Comment by levegab** [comment]
This issue has been resolved! 

![Image](https://user-images.githubusercontent.com/106617357/186194254-36aca5b5-cc5c-43a1-9eec-ae567c74eaf3.jpg)
