### ISSUE TITLE
Changes required to text when Sharing a publication

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#446]
When sharing a publication by email, the heading "Application StatsCAN" should be bilingual.
In French it should be "Application StatsCAN / StatsCAN app" and in English it should be "StatsCAN app / Application StatsCAN".

![image](https://user-images.githubusercontent.com/98898969/179258706-a5012e18-bd4c-4aa2-837c-3264b4dbdf35.png)

**Comment by Pharste** [comment]
Validated.
