### ISSUE TITLE
Due Aug 9: Test in Alpha for delays in publishing 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#448]
Placeholder ticket for testing.

**Comment by zhuelle** [comment]
This testing is related to issue in #281

**Comment by Pharste** [comment]
Hi, 

This testing is scheduled for August 9, after 11:30 AM. 

The following articles will be published: 

1. Refined petroleum products, June 2022 (11:32 AM)
2. Employment Insurance, May 2022 (11:33:30 AM)
3. Poultry and egg statistics, June 2022 (11:35:15 AM)
4. Sawmills, April 2022 (11:36 AM)
5. Non-profit institutions and volunteering: Economic contribution, first quarter 2022 (11:37:35 AM)
6. Canadian Tourism Activity Tracker, April 2022 (11:40 AM)
7. Retail Commodity Survey, May 2022 (11:42:13 AM)
8. Farm product prices, June 2022 (11:44:07 AM)
9. Electric Power Selling Price Index, June 2022 (11:45 AM)

We are trying to recreate our morning process as closely as possible, which is why the times are so close together/ down to the second. Please check that the articles are published on-time in Alpha. 

Thanks!

**Comment by zhuelle** [comment]
Has confirmed with @Jiandong-Guo and he will be the one to test as planned.

**Comment by Jiandong-Guo** [comment]
This is my test result
![image](https://user-images.githubusercontent.com/58485300/183700971-bd3b8007-2e07-4f49-b8cb-0095f772f3de.png)

From this test, I can basically eliminate the server side problem.
The delay happens in javascript api call, seems the react native is keeping a cache for a 2 minutes of time,  will do more investigation

**Comment by weglmar** [comment]
@Jiandong-Guo That's great news that you have eliminated the server side problem! Keep us posted on your investigation. Thank you for your work on this, Jiandong!

**Comment by Pharste** [comment]
@JulieBond FYI

**Comment by Jiandong-Guo** [comment]
@weglmar @zhuelle ,Please tell me the publishing time in the next week in prod, if it is not feasible, please arrange another time of publishing in alpha same like last time.  So I can test code with it.

**Comment by weglmar** [comment]
@Jiandong-Guo we post every day in Production between 8:30 and 9 AM. we would have to provide the time to you the morning of, with short notice because we need to wait for the articles to be posted on the website first, then we create them and publish them in the app before 9 AM. 
Would you be available tomorrow, Friday or sometime next week between 8:30 and 9?

**Comment by Jiandong-Guo** [comment]
Hi @weglmar, Is Tuesday(August 23rd) good for you ?

**Comment by weglmar** [comment]
@Jiandong-Guo yes Tuesday works for us. It will be in Production. We will comment on this ticket on Tuesday morning (between 8:30 and 9) with the times of the articles.

**Comment by weglmar** [comment]
Hi @Jiandong-Guo, we are getting ready to publish this morning, we will send the publishing times shortly

**Comment by Jiandong-Guo** [comment]
@weglmar Good

**Comment by weglmar** [comment]
Refined petroleum products, July 2022 - 8:50 AM
Travel between Canada and other countries, June 2022 - 8:51:10 AM

@Jiandong-Guo I am sending 3 more

**Comment by weglmar** [comment]
Livestock estimates - 8:52 AM
Cancer incidence in Canada, 2019 - 8:53 AM
Travel between Canada and other countries, June 2022 - 8:54:15 AM

@Jiandong-Guo That's all of them!

**Comment by Jiandong-Guo** [comment]
@weglmar ,The test is good, Please test it in the next release from your side.   Thanks

**Comment by weglmar** [comment]
@Jiandong-Guo thank you!! 👍

**Comment by zhuelle** [comment]
@Jiandong-Guo this has been deployed to the new release right? Can you resolve this ticket following the proper process as we discussed in today's stand-up? Thanks!

**Comment by Jiandong-Guo** [comment]
link to #281

**Comment by weglmar** [comment]
@Jiandong-Guo We believe the delay is fixed however we have noticed another issue. 

Sometimes when an article is booked in the Booking Tool, the time it was booked for will pass and the Status remains as Booked (not Released). 

We have to re-book the article in order for the status to change to Released and publish the article to the app. 

I'm not sure if this is an issue with the app or with the ORPS Booking tool. 

Sometimes booking a different article after will push/publish the article that is stuck in "Booked" status.

**Comment by zhuelle** [comment]
@weglmar what is the status of this ticket? should we close it? Thanks!

**Comment by weglmar** [comment]
Created a ticket in ORPS Jira to investigate whether the issue is in ORPS or app.

**Comment by zhuelle** [comment]
@weglmar what is the ticket number in ORPS? Can you please link it here? Thanks!
