### ISSUE TITLE
More icon in top-right corner of article view, level 3

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#45]
When in article view, level 3, the "More" menu option in the top-right corner should be changed to a "Share" icon.

Publications Screen Level 3: More Icon in the header , User can navigate to any links/pages and should be able to share the link of that particular page.

**Comment by ForumG-SC** [comment]
The Icon has been changed, will be deployed in the upcoming release. Requires Validation, assigning it back to you.

**Comment by payeisa** [comment]
Validated Oct 04, 2021.
