### ISSUE TITLE
Due Aug 17: Update promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#452]
Hi,

We would like to update the Apple promo text on Wednesday, August 17, to:

EN: 2021 Census data on Canada's linguistic diversity and use of English and French are now available!

FR: Des données du Recensement de 2021 sur la diversité linguistique et l’utilisation de l’anglais et du français au Canada sont maintenant accessibles!

Thank you!

**Comment by ForumG-SC** [comment]
@Pharste Is this duplicate ticket? https://github.com/StatCan/StatcanPublicationUAT/issues/450

**Comment by Pharste** [comment]
@ForumG-SC I've removed this text from the previous ticket, and included it here to simplify the process. :)

**Comment by Pharste** [comment]
@zhuelle it will have to be updated on August 17 to announce the latest census release. Thanks!

**Comment by giftydeep** [comment]
Updated.
