### ISSUE TITLE
StatsCAN v2.0.1: Colour theme > Auto not functioning as expected 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#453]
When selecting Colour theme > Auto from the Settings menu, the app does not adjust to the user's phone settings. 

For example, my phone is in Dark mode. When I select Auto, the app remains in the Light colour theme. 
This is happening on iOS and Android devices. 

https://user-images.githubusercontent.com/98898969/183987339-2a82580f-8745-4b4e-8eea-de5a06bbf776.mov

**Comment by zhuelle** [comment]
@Jiandong-Guo would you please evaluate this ticket and put an effort estimate to it? Thanks!

**Comment by Jiandong-Guo** [comment]
@weglmar, From your video, I saw your app setting is in light mode.  the app reflects OS setting only under AUTO mode
Please test following following steps:
1)Go to App setting and choose Auto mode and keep it in AUTO mode,
2)Go to OS setting, choose light, switch back to our app screen(publication screen for example),  you may see the change based on your original setting
3)Switch to OS setting, and choose dark, then switch back our app screen, you will definitely see the change.
4)Switch to OS setting, and choose light, then switch back our app screen, you will definitely see the change.

**Comment by Jiandong-Guo** [comment]
@weglmar, Seems the change is not merged into master, let me check it.

**Comment by weglmar** [comment]
@Jiandong-Guo would you like to see a screen recording from the steps above? No changes take place when I switch my OS settings to Light or Dark and keep the app in Auto. The screens remain Light.

**Comment by Jiandong-Guo** [comment]
Code conflicts were found in master configuration.
@weglmar, It is not working for current version. will let you know if I can build a new version in next release

**Comment by zhuelle** [comment]
link to #181

**Comment by weglmar** [comment]
Validated
