### ISSUE TITLE
Due Sept 8: Update apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#459]
Hi, 

We would like to update the Apple promo text on September 8 to: 

EN: Available September 21: 2021 Census data on Canada's First Nations people, Metis and Inuit; and Canada's housing portrait.

FR: Diffusion le 21 septembre : les données du Recensement de 2021 sur les Premières Nations, les Métis et les Inuits au Canada, ainsi que le portrait du logement au Canada.

Thanks,
Stephanie

**Comment by Pharste** [comment]
@weglmar FYI

**Comment by Jiandong-Guo** [comment]
It's done.
