### ISSUE TITLE
Settings screen (UX)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#46]
The menu items should all be the same size (i.e. Clear search history is bigger than the others, Share this app is smaller etc.)
Font should match once used in prototype.
"Rate this app" item should be removed.
"Privacy policy" should be "Privacy notice".
"Terms & conditions" should be "Terms of use".

**Comment by ForumG-SC** [comment]
Fixed, the changes will be deployed in the upcoming release. Requires validation, assigning it back to you.

**Comment by payeisa** [comment]
The size of the menu items "Color theme", "Clear search history", "Share this app" and "App version" are still bigger than the other ones (i.e. higher row height). The font and color is also different than prototype.

![image](https://user-images.githubusercontent.com/89025704/135828728-e0c56339-4ac9-4f64-b466-b4141dd25847.png)

**Comment by ForumG-SC** [comment]
Fixed, will be deployed in the upcoming release.

**Comment by payeisa** [comment]
Validated.
