### ISSUE TITLE
App crash: Contact us button on publication screen (v. 2.0.3)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#471]
When accessing the contact us button from the options menu (...) in the top right corner of the screen, the app crashes. 

![( ) menu - contact us button](https://user-images.githubusercontent.com/89025880/191347558-34e07520-a780-4792-8255-6f1343992629.jpg)

**Comment by weglmar** [comment]
@zhuelle is it possible to estimate the amount of work required for this bug? Thank you

**Comment by zhuelle** [comment]
@weglmar Forum has put a work estimate on this ticket. Thanks!

**Comment by weglmar** [comment]
@ForumG-SC @zhuelle yes, please work on this ticket. thank you!

**Comment by Pharste** [comment]
validated and closed

**Comment by Pharste** [comment]
Hi, It appears this is still happening on Android, but is fixed on iOS. I am trying to upload a video, but the file is too large.

@levegab can you please add the device/ software information?

**Comment by Pharste** [comment]
[app crash video.zip](https://github.com/StatCan/StatcanPublicationUAT/files/9699801/app.crash.video.zip)

**Comment by levegab** [comment]
My device is an Android Galaxy A11.

**Comment by Pharste** [comment]
@levegab could you please create a new ticket for this, since you will be the one testing it once resolved? Thanks!
