### ISSUE TITLE
StatsCan Alpha 3.0.0 - App Crashing

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#477]
When opening Alpha on both IOS and Android, the app immediately crashes.

**Comment by zhuelle** [comment]
@levegab is this app crashing issue happening on all testing devices? Also, is this issue only happening on Alpha but not Production? Thanks!

**Comment by levegab** [comment]
Yes, only Alpha is crashing upon opening on all devices.

**Comment by levegab** [comment]
This issue has been resolved.
