### ISSUE TITLE
App Crash: Help & FAQ on Android (3.0.0)

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#479]
When selecting "Help & FAQ" on Android, the app crashes immediately. 

[app.crash.video.zip](https://github.com/StatCan/StatcanPublicationUAT/files/9706457/app.crash.video.zip)

**Comment by zhuelle** [comment]
@weglmar what is the priority of the ticket? Do you need someone to look into right away in this Sprint? Thanks!

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by levegab** [comment]
This issue has been resolved.
