### ISSUE TITLE
Welcome screen - bold buttons

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#48]
Should the language buttons be bold? (They are not bold in the prototype)

**Comment by ForumG-SC** [comment]
As per the prototype this screen's button text is bold . 
![image](https://user-images.githubusercontent.com/84411852/134945303-4c5b4134-df55-41d0-b197-5403cd4fd8f9.png)

**Comment by ForumG-SC** [comment]
The Language buttons are not bold in Dev version as they were not bold in the prototype, but if you require them to be bold as well, it can be done.

**Comment by payeisa** [comment]
Validated.
