### ISSUE TITLE
Due Nov 30: Update Apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#484]
Hi,

We would like to update the Apple promo text on November 30 to:

EN: Discover 2021 Census data on education; the changing dynamics of the labour force & how people get to work; & official minority language instruction.

FR: Découvrez les données du Recensement de 2021 sur la scolarité, l’évolution du marché du travail et le navettage, et l’instruction dans la langue officielle minoritaire.

Thanks,
Stephanie

**Comment by zhuelle** [comment]
Hi @giftydeep, since you are going to perform the Nov 30th deployment, I assigned this ticket to you. Please let me know if you have any questions. Thanks!

**Comment by giftydeep** [comment]
Updated

**Comment by Pharste** [comment]
Validated & closed.
