### ISSUE TITLE
StatsCAN (v3.0.1): Gesture to swipe backwards from the Publication screen

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#488]
The gesture to swipe backwards from the Publication screen to Publications screen no longer works. Previously, we were able to swipe right but now you have to click the back arrow in the top left corner of the screen. 

This is occurring on iPhone and Android devices.

Device Type: iOS (iPhone X)
Device Screen Size: 5.8 inches
Device Screen Resolution: 2436 x 1125
Device’s OS version info: 16.0

Device Type: Android Galaxy A11
Device Screen Size: 6.4 inches
Device Screen Resolution: 720x1560 pixels
Device’s OS version info: One UI 3.1

**Comment by Jiandong-Guo** [comment]
We have no such function in previous version( tested on previous codebase), even if it has such function,  it's just a by-production for only some versions of OS.   In the new structure, the 2 screens are totally located in different tree nodes, no way to go back-forth via swipe

**Comment by Rajat-Sen** [comment]
Hi @Jiandong-Guo, I can validate that previously we could swipe back to the publications screen from publication screen. It stopped working after the bottom tab bar navigation changes. It's important to have that functionality. Thanks!

If you would like I can share video!

**Comment by zhuelle** [comment]
@Rajat-Sen please share a video. I am assigning this ticket back to @Jiandong-Guo.

**Comment by Rajat-Sen** [comment]
https://user-images.githubusercontent.com/38566088/197814496-926688c0-b275-4de5-be47-b92ef77e8496.MOV

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by weglmar** [comment]
Resolved
