### ISSUE TITLE
StatsCAN (3.0.1): App crashes when title of "Saved" screen is selected

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#489]
When on the "Saved" screen, the app will crash if you select "Saved items" at the top left of the screen.

Device Type: iOS (iPhone X)
Device Screen Size: 5.8 inches
Device Screen Resolution: 2436 x 1125
Device’s OS version info: 16.0

Device Type: Android Galaxy A11
Device Screen Size: 6.4 inches
Device Screen Resolution: 720x1560 pixels
Device’s OS version info: One UI 3.1

**Comment by Jiandong-Guo** [comment]
Fixed, please test in next release

**Comment by levegab** [comment]
This has been tested and resolved.
