### ISSUE TITLE
Terms and conditions: Accept/Cancel buttons

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#49]
Should the buttons be bold? They currently are not (in Dev version), but are in the prototype.

**Comment by ForumG-SC** [comment]
Cancel button's text was not bold, fixed. Will be deployed in upcoming release, requires validation, assigning it back to you.

**Comment by payeisa** [comment]
Should the "Accept" button also be bold?

**Comment by ForumG-SC** [comment]
Accept & Cancel buttons are bold in the prototype and in the current dev version they are bold as well.

**Comment by payeisa** [comment]
The Accept button does not seem bold (if compared with the "Continue" button on the Welcome screen).

![image](https://user-images.githubusercontent.com/89025704/145020969-7772dcf8-06ad-4480-8397-7ad62942b6b4.png)

**Comment by ForumG-SC** [comment]
Done, assigning it back to you for validations.

**Comment by payeisa** [comment]
Validated.
