### ISSUE TITLE
StatsCAN (3.0.2): Capitalize "s" in "sauver" (French Only)

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#495]
When in "Publications" --> "Pour vous", when the user selects "Choisir des sujets" and the list appears, at the bottom of the screen, the s in "sauver" should be capitalized. It should read "Sauver".

**Comment by zhuelle** [comment]
@weglmar Should this ticket be included in the current Sprint? This should be a simple fix.

**Comment by weglmar** [comment]
@zhuelle yes, please include in the current sprint. Thank you!

**Comment by giftydeep** [comment]
Please test in the next release.

**Comment by levegab** [comment]
This issue has been resolved.
