### ISSUE TITLE
StatsCAN (3.0.2): Remove added spacing on Publications/Home page

### ISSUE THREAD

**Issue by levegab** [StatCan/StatcanPublicationUAT#496]
There is currently a block of space between All/For you and the latest articles (see below). Please remove the block.
![home spacing](https://user-images.githubusercontent.com/106617357/197190468-acc5c067-5c02-4ebb-9a98-aafadd1566fb.jpg)

**Comment by zhuelle** [comment]
@weglmar should this ticket be included in current Sprint? Thanks!

**Comment by zhuelle** [comment]
@levegab Does this issue happen on iOS or Android devices? Please provide following information when you create any bug ticket. Thanks!

Describe the issue in detail.
Specify StatsCAN App version installed on the device.
Device Type: IOS / Android.
Device Screen Size.
Device Screen Resolution.
Device’s OS version info.
Attach screen recording/screenshots .

https://confluenceb.statcan.ca/display/SPMA/Using+GitHub+to+manage+all+types+of+tickets+for+StatsCAN+app

**Comment by levegab** [comment]
@zhuelle this is currently happening on both iPhone and Android. Please find the device information below.

Device Type: iOS (iPhone X)
Device Screen Size: 5.8 inches
Device Screen Resolution: 2436 x 1125
Device’s OS version info: 16.0

Device Type: Android Galaxy A11
Device Screen Size: 6.4 inches
Device Screen Resolution: 720x1560 pixels
Device’s OS version info: One UI 3.1

**Comment by zhuelle** [comment]
@Jiandong-Guo Please provide work effort estimates to fix this bug. Thanks!

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by levegab** [comment]
This is still happening on iPhone, but has been resolved on Android.

**Comment by weglmar** [comment]
Validated
