### ISSUE TITLE
Epic 1, Feature 1.2 Language screen (design of buttons)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#5]
On the language screen, the color scheme, font size and style used for the language buttons should match (as closely as possible) the ones used in the prototype.

**Comment by ForumG-SC** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/84411852/130091746-1016043e-6ea6-4549-9c7b-ad683aebf77d.png">
<img width="289" alt="image" src="https://user-images.githubusercontent.com/84411852/130093185-de54c73d-8039-43c2-a7f9-7a95ca30e3d6.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/84411852/130095069-f0629fa0-168b-4b1b-b329-7a6c09a0e2b1.png">
Buttons color scheme changed.

**Comment by ForumG-SC** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/84411852/130100400-467d5733-c8b8-4afe-9635-d5c38fa7ac5c.png">

Tab Bar scholar scheme fixed
