### ISSUE TITLE
Publications not loading: StatsCAN Alpha (3.0.2)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#500]
Hi, 

New publications are not loading in the StatsCAN Alpha app. We believe this is due to the ORPS split-- between the app and Plus environments. I've attached an image of the message displaying. 

Publications posted before the split are displaying properly. 

![data not found](https://user-images.githubusercontent.com/89025880/197863407-e792bf88-fd15-43ff-bd45-1d8eb909faa8.png)

(Found on iPhone XR, iOS 15.7)

**Comment by spotzero** [comment]
@Pharste Which publication did you select that did this, or are they all doing this?

**Comment by spotzero** [comment]
@Pharste nevermind, they're all doing it.  I see them problem.  It's in the backend.

**Comment by spotzero** [comment]
I've deployed a fix to alpha. It should work now.

**Comment by Pharste** [comment]
new articles posted to Alpha are working as expected. Thank you!
