### ISSUE TITLE
Accessibility Label for Saved

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#501]
The Tab bar, on the saved icon while using voice over it is still saying "For you" instead of "Saved".

**Comment by weglmar** [comment]
Resolved in English but in French it is reading "Enregristré"

**Comment by weglmar** [comment]
The French label is Sauvegardés @ForumG-SC

**Comment by weglmar** [comment]
Seems to be resolved.
@Rajat-Sen, could you please confirm?

**Comment by Rajat-Sen** [comment]
Fixed.
