### ISSUE TITLE
StatsCAN v3.0.3: Subjects not listed in alphabetical order in French - Select subjects button on For You tab and Manage subjects screen 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#502]
When the app is opened for the first time, selecting subjects is skipped and then you access the For You tab and click Select Subjects, the subjects are not appearing in alphabetical order in French (the three subjects that begin with É are listed at the bottom - "Économie et societe numeriques, Éducation, formation et apprentissage, Énergie" all appear at the end of the list, under "voyages et tourisme").

This is also happening on the Manage subjects screen in settings. 

Subjects are also appearing in this order when saved, on For you screen in French. 

This is only happening in French.

**Comment by giftydeep** [comment]
@weglmar Hi, i have tried every possible solution but each one is returning the data in the same order. So there's no way I can sort these accent characters on the app side. 
The possible solution here is to get rid of the accent characters or get the sorted list from the backend.
So until we can put this one on hold.

**Comment by weglmar** [comment]
@giftydeep hi, Happy New Year! Unfortunately we cannot get rid of the accent characters since this would not meet official language requirements. What would be the estimated effort for getting the sorted list from the backend?

**Comment by zhuelle** [comment]
@weglmar Gagandeep has left the team and started his new assignment Jan 3rd. I have asked @Jiandong-Guo to take a look. 

@Jiandong-Guo, please provide an estimated effort if we have to get the sorted list from the backend. Thanks!

**Comment by Jiandong-Guo** [comment]
It's marked medium effort. Thanks

**Comment by weglmar** [comment]
Validated and closed.
