### ISSUE TITLE
StatsCAN v3.0.3: Navigation bar disappearing 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#503]
Navigation bar disappears. This is happening sporadically, and I cannot recreate it. It first happened when I was swiping back from a publication to the For you tab and clicking the bar arrow. 

Happened when testing on iPhone XR too after clicking into Publication from the Publications screen, opening top menu to share/ contact us and then swiping back to Publications screen.

Tested on iPhone and Android, happens on all devices randomly. 

Device Type: iOS (iPhone X) 
Device Screen Size: 5.8 inches 
Device Screen Resolution: 2436 x 1125 
Device’s OS version info: 15.5 

Device Type: iOS (iPhone XR)
Device Screen Size: 
Device Screen Resolution: 
Device’s OS version info: 15.6.1

Device Type: Android Galaxy A11 
Device Screen Size: 6.4 inches 
Device Screen Resolution: 720x1560 pixels 
Device’s OS version info: One UI 3.1

**Comment by Pharste** [comment]
The navigation bar is disappearing after onboarding, when subjects are first selected, after selecting the next button.
![no nav](https://user-images.githubusercontent.com/89025880/206210594-140aaab1-3862-4456-9ce2-19d3e54bd1c1.PNG)
![no nav 2](https://user-images.githubusercontent.com/89025880/206210599-14cb1724-1026-4a3b-a6c6-310bedd7e732.PNG)

Device Type: iOS (iPhone XR)
Device Screen Size:
Device Screen Resolution:
Device’s OS version info: 15.6.1

**Comment by giftydeep** [comment]
Please test in next release.

**Comment by weglmar** [comment]
Validated
