### ISSUE TITLE
Modification to Publication Screen Level 2 and Saved Screen 

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#505]
Partial requirements for https://github.com/StatCan/StatcanPublicationUAT/issues/467 
a. The heart icon on the Publication screen and on the Saved screen (on the image card) must be changed to a bookmark.
b. The message when saving an article must be changed (EN and FR). The message should read: Publication saved.

**Comment by weglmar** [comment]
Hi @ForumG-SC 

A) and B) above have been resolved but we were missing a partial requirement for the message when unsaving an article. 
The message should be: 

Publication unsaved 
Publication non enregistrée.

**Comment by weglmar** [comment]
Hi @ForumG-SC, we have validated and the correct message is appearing now. 

However, there is now a circle and shadow associated to the bookmark. 
Would you like me to open a new ticket for this? 

![image](https://user-images.githubusercontent.com/98898969/221291134-467d287a-8cd4-4c8f-80f1-0823f8ec8d11.png)

**Comment by weglmar** [comment]
Confirmed it is fixed now, thank you @ForumG-SC, you rock!! :) 
Have a great weekend!
