### ISSUE TITLE
StatsCAN v3.0.3: Next button not responsive on Subjects of Interest onboarding screen

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#506]
The Next button is not responsive upon first click (need to click it a lot of times to trigger a response).
Related to main ticket #461

**Comment by zhuelle** [comment]
@giftydeep Martyna created a separate bug ticket to track the issue related to #461 which you worked on. The purpose is to track one bug per ticket. You can work on this in the next Sprint. Thanks!

**Comment by weglmar** [comment]
@giftydeep it seems to be working well for us now too. it was very slow to respond with 3.0.3 but seems quicker now with 3.0.4.
