### ISSUE TITLE
Add the ability to Edit subjects you’re following on the For You tab

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#507]
Partial requirements for #468 
Add the ability to Edit subjects you are following on the For You tab. 

Selecting "Select subjects" on the "For you" screen directs the user to the "Manage subjects" temporary screen (when the user has no subjects of interest currently selected)

Clicking Edit directs the user to the "Manage subjects" temporary screen

Ability to edit the subjects you're following

Clicking "Save" button on the manage subjects temporary screen saves the users selections

Clicking "X" button on the manage subjects temporary screen DOES NOT save the users selections

![image](https://user-images.githubusercontent.com/98898969/205108216-dda9670f-f979-4431-b43d-e65ee98a74fc.png)

![image](https://user-images.githubusercontent.com/98898969/205108264-decca98e-8e71-4593-b531-6d2948a4efed.png)

**Comment by Pharste** [comment]
Translation for 'Edit' : Modifier

**Comment by weglmar** [comment]
@ForumG-SC 
In dark mode, the text for "Subjects you're following" and "Les sujets que vous suivez" is in black, making it difficult to see. 
Could you please modify the text to white? 

![image](https://user-images.githubusercontent.com/98898969/217017729-a13a26cc-ab96-4cd0-bae7-1ba882c7c155.png)

**Comment by weglmar** [comment]
Validated and closed.
