### ISSUE TITLE
App crash: Version 2.0.1

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#509]
Hello,

A user has reported the following app crash bug: 

Steps: 
•	Go to Settings
•	Click on Help and FAQ
•	The app crashes (100% of the time).

Phone: Google Pixel 6, Android 13 (security update December 5th 2022)

App version: 2.0.1

**Comment by Pharste** [comment]
@levegab can you please try this on your android device to see if you can reproduce it?

**Comment by zhuelle** [comment]
Can we resolve this issue since it seems cannot reproduce the crash? Thanks!

**Comment by weglmar** [comment]
I am able to reproduce the crash on an Android device in Production (v2.0.1). This needs to be confirmed in the current testing version though. 
@zhuelle Since Gab tested on a newer version, is it possible that this bug has been resolved in those versions? 
Thanks!

**Comment by zhuelle** [comment]
I think we can resolve this ticket if the crash cannot be reproduced in the new version. If we experience the same issue later, we can reopen or create a new ticket.
