### ISSUE TITLE
Delay in publishing (app-only publications)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#511]
Hi, 

We've noticed two app-only publications (not posted to web) that have had 3 minute publishing delays, when booked in the afternoon. 

I've attached screenshots of the two instances. The first was "Upcoming Release Schedule, January 9 to 13, 2023" (ID 2664), scheduled on January 6, 2023 at 3:30 PM, actually posted to the app at 3:33 PM. 

The second instance was "New product: Employed labour force who worked full year, full time and reported employment income in 2020, 2021 Census" (ID 2553), scheduled on January 11, 2023 at 1:00 PM, actually posted to the app at 1:33 PM. 

Adeeba believes this is an ORPS issue, as similar things are happening with Plus. Please reach out to her to validate once confirmed that it isn't an app issue. 

I'll continue adding to this ticket should this happen again.

Thanks,
Stephanie

![ID 2553](https://user-images.githubusercontent.com/89025880/211886821-94cb3160-55b8-4a09-bd6a-ed80aff17edc.jpg)
![ID 2664](https://user-images.githubusercontent.com/89025880/211886826-4d687480-ed9f-4d87-8969-c757f20db2ee.png)

**Comment by weglmar** [comment]
Closing as this is related to #448 and open in ORPS Jira.
