### ISSUE TITLE
UX for Publication page

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#512]
Creating this ticket as requested, related to #401.

Implement the following UX changes:
a) Implement the new UX design changes for the cards.
b) The drop down menu on each card should not be opened below the card , it should be opened above the three dots.
c) The drop down menu's color and UX needs to be fixed.

Prototype for reference: https://xd.adobe.com/view/e44f62bb-61f7-4195-bc45-a0276a0731c9-b11c/screen/cea136e5-7c20-4d6b-944e-81f402bcc502

**Comment by weglmar** [comment]
@ForumG-SC Hi Forum, I would recommend we change the background to the same one as the For you screen. Thank you!

**Comment by weglmar** [comment]
Validated and closed.
