### ISSUE TITLE
StatsCAN v3.0.7: 'Save' button not fully displaying

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#516]
Issue:
On the Publications screen - Pour vous - Modifier, in both French and English, the 'Sauver' / 'Save' button is not fully displaying, and is partially cut off. 

Appearing on Samsung S9 

![image](https://user-images.githubusercontent.com/98898969/217646322-65e2abf2-e87f-4009-9d50-4e150030f849.png)

**Comment by weglmar** [comment]
@payeisa Hi isabelle, could you please test this ticket? It was happening on your Samsung S9

**Comment by payeisa** [comment]
Confirming that the issue is fixed. Tested in both E and F on Android (Samsung S9).

**Comment by weglmar** [comment]
Closing as per Isabelle's comments above.
