### ISSUE TITLE
StatCAN v3.0.7: Modify blank screen message on Saved screen

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#522]
Issue:
When testing the ability to unsave all publications to display the original intro screen, the screen reads "Click the heart icon on a publication to add it to this page so you can refer to it later!" 

It should be modified to: Your saved publications will appear here. 
In French: Vos publications enregistrées apparaîtront ici.

**Comment by weglmar** [comment]
Validated and closed.
