### ISSUE TITLE
StatsCAN v3.0.7: Opening shared links

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#525]
Issue:
When testing whether a shared link opens in StatsCAN, when shared with a user who has the app downloaded, it did not work.

Tested on:
Device Type: iOS (iPhone 14 Pro)
Device Screen Size: 6.1 inches
Device Screen Resolution: 2556 x 1179
Device’s OS version info: 16.1.2

Device Type: Android Galaxy A11
Device Screen Size: 6.4 inches
Device Screen Resolution: 720x1560 pixels
Device’s OS version info: One UI 3.1

**Comment by weglmar** [comment]
#374

**Comment by weglmar** [comment]
Duplicate
