### ISSUE TITLE
StatsCAN v3.0.7: Text colour discrepancy 

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#526]
Issue:
On the For you screen, Edit and See more are in nlack text (should match the prototype and be blue).

Current: 
![image](https://user-images.githubusercontent.com/98898969/217869854-351d6b8d-cd2f-4ad3-b8d7-c24ba5b21132.png)

Prototype: 
![image](https://user-images.githubusercontent.com/98898969/217869617-1e5a2c0b-94f5-4e38-8608-c2483bfa4ba0.png)

Tested on:
Device Type: iOS (iPhone 14 Pro)
Device Screen Size: 6.1 inches
Device Screen Resolution: 2556 x 1179
Device’s OS version info: 16.1.2

Device Type: Android Galaxy A11
Device Screen Size: 6.4 inches
Device Screen Resolution: 720x1560 pixels
Device’s OS version info: One UI 3.1

**Comment by weglmar** [comment]
Validated and closed.
