### ISSUE TITLE
StatsCAN v3.0.7: Blank bar appearing on bottom of Publications screen

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#528]
Issue:
Blank bar appears at the end of the Publications screen (above the bottom tab bar). Unsure how to recreate it. Shared an article using the 3 dots on the image card, and then it appeared. When force closing the app and opening it again, it is resolved. 

![Picture4](https://user-images.githubusercontent.com/124800366/217872609-2367ffb8-a0a8-42fb-871f-ff431f33c104.png)

![Picture5](https://user-images.githubusercontent.com/124800366/217872640-a1791d66-e9fd-4d9e-8843-c0a55ff7be18.png)

Appears on:
Device Type: iOS (iPhone 14 Pro)
Device Screen Size: 6.1 inches
Device Screen Resolution: 2556 x 1179
Device’s OS version info: 16.1.2

**Comment by weglmar** [comment]
@ForumG-SC Hi Forum, we have been unable to recreate this since it was first reported with a previous version, so I'm unsure if it it is still happening.
