### ISSUE TITLE
Sept 20 Release Note

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#53]
We weren't sure what "Tab Bar" refers to...

Publications Screen Level 3: Tab Bar Disabled.

Publications Screen Level 3: Navigation Buttons are disabled when user lands first time on the screen and the buttons actives while navigating in the WebView.

Publications Screen Level 3: More Icon in the header , User can navigate to any links/pages and should be able to share the link of that particular page.

**Comment by ForumG-SC** [comment]
@payeisa Publications Screen Level 3: Tab Bar Disabled: **It refers to the bottom tab navigation bar , if you compare to the previous level that screen was showing in app browser with the bottom tab bar (Publications,Search,For You,Settings).**

Publications Screen Level 3: Navigation Buttons are disabled when user lands first time on the screen and the buttons actives while navigating in the WebView ---- **This refers to the in-app browser's back and forward arrows  in the bottom of the screen , like you mentioned in the previous ticket that it was misleading that those buttons were active all the time so now they are grayed out and activates only upon navigating.**

Publications Screen Level 3: More Icon in the header , User can navigate to any links/pages and should be able to share the link of that particular page ---   Whenever you are navigating inside the in-app browser , you can share link of that current page by clicking on the more icon in the header. 
![thumbnail_79511](https://user-images.githubusercontent.com/84411852/134942957-a9885ea3-4b88-4b4f-b481-00f5858364b2.jpg)

**Comment by payeisa** [comment]
@ForumG-SC Thanks for the clarification!
@Pharste FYI
