### ISSUE TITLE
StatsCAN v3.0.7: Welcome page - wording changes

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#530]
Issue:
On the Welcome to StatsCAN page, the following changes are requested in English:

1.  Change both instances of “Agree & Continue” to “Agree and continue.” 
2.  Change “Privacy notice” to “privacy notice.”
3.  Change “Terms of Use” to “terms of use.”

On the Welcome to StatsCAN page, the following changes are requested in French:

1. Change “Avis de confidentialité” to « avis de confidentialité »
2. Change « Conditions d’utilisation » to « conditions d’utilisation ».

![image](https://user-images.githubusercontent.com/124800366/218174108-02984e59-225c-4608-96f7-5c45c1e45e94.png)
![image](https://user-images.githubusercontent.com/124800366/218174127-2da237d5-9a29-48c1-b90a-ab2b1b3a4845.png)

**Comment by weglmar** [comment]
Validated and closed.
