### ISSUE TITLE
StatsCAN v3.0.7: Publications, For you page - wording changes

### ISSUE THREAD

**Issue by prevama** [StatCan/StatcanPublicationUAT#531]
Issue:

On the Publications - For you page, the following changes are requested in English:
Change “info” to “information.” 

On the Publications - Pour Vouse page, the following changes are requested in French:
1.  Change « Soyez au courant » to « Restez au courant ». 
2.  Change « les dernières nouvelles » to « les plus récents renseignements ». 

![image](https://user-images.githubusercontent.com/124800366/218175148-81504cfd-ae8b-4a2c-935f-bd8467bb28c7.png)
![image](https://user-images.githubusercontent.com/124800366/218175182-8c7c0df2-7f8a-4062-8fa6-39240aba2436.png)

**Comment by weglmar** [comment]
Validated and closed.
