### ISSUE TITLE
UX design: Language screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#55]
I'm not sure if the design was done for the Language screen, but the buttons in Dev are bigger/closer together compared to prototype. Image on the left is Dev, and image on the right is prototype.

![image](https://user-images.githubusercontent.com/89025704/135830303-cdeafb6f-1fd3-4018-b94e-e963b0b3f460.png)

**Comment by ForumG-SC** [comment]
@payeisa In which device are you testing this ?

**Comment by payeisa** [comment]
No further action required.
