### ISSUE TITLE
StatsCAN v3.0.11: Scrolling down on Terms of Use screen 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#561]
On a Samsung S9, app version 3.0.11: 

I noticed that I can’t scroll past what is on the screenshot, on the Terms of Use screen. The contact information text is cut-off.

![image](https://user-images.githubusercontent.com/98898969/221911972-e686ac01-a421-4b21-86c8-e9f932b7e9d9.png)

On an Android Galaxy A11, app version 3.0.11: 

I can scroll all the way down, but it would be ideal if we could add a little bit more space after the text. 

![image](https://user-images.githubusercontent.com/98898969/221913526-4928f7d2-a325-49d4-b91d-a8940f5ae717.png)

On iPhone, the scrolling is not affected but more space could also be added after the text.

**Comment by weglmar** [comment]
The is sufficient space on iPhone now. 

@levegab could you confirm on your Android device? 

@payeisa could you confirm the text is no longer cut off on your S9? 

Thank you!

**Comment by payeisa** [comment]
Confirming that the issue has been resolved with version 4.0.0 on my Samsung S9. Validated in both English and French.

**Comment by weglmar** [comment]
Validated!
