### ISSUE TITLE
Disable Drop down menu on the Publications Screen

### ISSUE THREAD

**Issue by ForumG-SC** [StatCan/StatcanPublicationUAT#572]
When we click on three dots to open drop down menu on the first big card on the publications screen, the drop down menu opens up on every big card . This bug was hard to catch as we only notice it when we scroll down. Looking at the code I concluded that this bug was existing since feature Changes to "All tab" was implemented as it could be replicated in StatsCAN older versions as well. 

Related to: https://github.com/StatCan/StatcanPublicationUAT/issues/464

**Comment by weglmar** [comment]
@ForumG-SC Hi Forum, this is a good catch, we did not see it! 
I just verified opening the menu on the second (smaller) card, and if I scroll down, it also opens on every second card (after the large image card). Same thing happens with the 3rd, 4th, and so on.

**Comment by weglmar** [comment]
Hi @ForumG-SC, would there be an option to remove this menu and re-deploy a new version without it? If yes, what would be the effort of this? (I am just trying to see if we have different options!)

**Comment by weglmar** [comment]
The menu has been disabled on all devices.
