### ISSUE TITLE
Search - Sort & Filter functions

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#58]
Should we be testing the "functionality" of these two features (per the latest prototype), or simply validating the fact that they were added?

_Sorting and Filter by subject added. Click on Search bar , enter a word and click search icon , sort and filter by subjects buttons will appear to test._

**Comment by payeisa** [comment]
Go to Search screen - enter "Travel" - search.
9 results will be found.
Click on "Filter by subject(s)" (notice that none of the filters are applies, all options are blank)
Select "Government"
Apply
1 result will be found
Go back to "Filter by subject(s)
Remove the checkmark for "Government" (i.e. no filters selected, and back to how it was before I applied the "Government" filter)
Click Apply.
The "No results found" message is displayed.
I would have expected the 9 results to be displayed, since I am not filtering on any subject.

**Comment by Jiandong-Guo** [comment]
@payeisa, The checkmark means we will show items for this subject,  if you want to show them all, you have to check all the subjects and then 9 result will be shown.
If the way is not what you are expecting, we can change to:
     first time you click the filter and enter the filter dialog, all the subjects are checked, 
     you can un-select some subject, and items belong to this subject will disappear
    if you check it back, the items belong to this subject will appear again
Do you agree?

**Comment by payeisa** [comment]
@Jiandong-Guo I like your suggestion and think this would align the logic a bit better.
By default, all the subjects would be selected, and if a user clears an option/removes a checkmark, then the items for that subject would no longer be displayed.

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo 
This is also a priority, I have shared the feedback from Testflight. Please check.

**Comment by Jiandong-Guo** [comment]
Fixed and Checked in and will be ready to test when server is back on

**Comment by payeisa** [comment]
Validated.
