### ISSUE TITLE
404 message on All and For you screen

### ISSUE THREAD

**Issue by shaunan** [StatCan/StatcanPublicationUAT#581]
Hi Martyna,

As requested here is the text received back from translation.
This message needs to be modified in the app.

[2304144bbil.docx](https://github.com/StatCan/StatcanPublicationUAT/files/11223549/2304144bbil.docx)

**Comment by shaunan** [comment]
Here is the text we received back from translation. 
This message needs to be modified in the app:

We couldn’t load the screen. It’s not you! It’s us. Please check back later. 

Nous rencontrons actuellement des difficultés techniques et n’arrivons pas à télécharger la page. Veuillez essayer de nouveau plus tard.

**Comment by weglmar** [comment]
Hi @Jiandong-Guo, I think this is something that Marc-Antoine can work on (but it doesn't have an effort estimate). Could you please confirm and assign to him if it's suitable? 
Thank you!

**Comment by Jiandong-Guo** [comment]
Hi Martyna,
Ok I will assign this one to him.
Thanks
Jiandong

**Comment by M-A-Boucher** [comment]
Merge https://github.com/StatCan/StatCanPublication/commit/85cbf064c6ed1b9e5bbdc104540941defb54e697.

**Comment by weglmar** [comment]
@M-A-Boucher Hi Marc-Antoine, was this ticket included in the latest release (v4.0.2)? 
Our process is for the Project Status to be changed to "Requires Business Testing," and then assigning the ticket back to me. 

![image](https://github.com/StatCan/StatcanPublicationUAT/assets/98898969/147bc661-4b27-48d2-93df-7ac24f7a969e)

After my team tests, the business team closes the ticket, or sets the Status to Needs Revision, if changes are required, and assigns back to you.

**Comment by M-A-Boucher** [comment]
It's not in the latest release, thanks for reopening.

**Comment by Jiandong-Guo** [comment]
It's done

**Comment by weglmar** [comment]
Validated and closed.
