### ISSUE TITLE
Due May 23: Update Apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#582]
Hi Jiandong, 

On May 23, we would like to update the Apple promo text to: 

EN: Spring is in the air. It’s time to grow and renew your statistical knowledge! Download the StatsCAN app for direct access to all the latest statistical information.

FR: Le printemps est là. C’est le temps d’approfondir vos connaissances statistiques! Téléchargez l’appli StatsCAN pour accéder aux plus récents renseignements statistiques.

Thank you!
Stephanie

**Comment by Pharste** [comment]
@weglmar FYI :)

**Comment by Jiandong-Guo** [comment]
The promo text was updated in app store.
