### ISSUE TITLE
Due June 5: Update Apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#583]
Hi, 

We would like to update the StatsCAN app promo text to the following on June 5: 

**EN:** It’s #EnviroWeek! To celebrate, we’re releasing a series of publications on environment- and energy-related topics. Read them all in the StatsCAN app!

**FR**: C’est la #SemaineEnviro! Pour fêter, nous diffusons une série de publications sur l’environnement et l’énergie. Lisez-les dans l’appli StatsCAN!

Thank you,
Stephanie

**Comment by Jiandong-Guo** [comment]
@Pharste, It's updated.
