### ISSUE TITLE
Due June 12: Update Apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#584]
Hi,

We would like to update the StatsCAN app promo text to the following on June 12:

EN: Did you miss our #EnviroWeek publications in early June? Catch up on the latest environment- and energy-related topics today with the StatsCAN app!

FR: Vous avez raté nos publications de la #SemaineEnviro au début de juin? Demeurez au fait de ce qui touche l’environnement et l’énergie grâce à l’appli StatsCAN!

Thank you,
Stephanie

**Comment by Jiandong-Guo** [comment]
@Pharste, It's updated, Please check it. Thanks

**Comment by Pharste** [comment]
validated, thank you!
