### ISSUE TITLE
Requirement for Terms of Use (BETA)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#59]
Hi Ali,

Just confirming that we can keep the Terms of Use AS-IS (i.e. latin) for the BETA version.  

At our meeting this morning, I suggested using the ones from the website, however, for the purposes of the consultations, we can leave them as-is, since we are not asking, or expecting the user to comment on the actual terms of use.

Thanks,
Isabelle

**Comment by AJBouzidi** [comment]
@payeisa Hi Isabelle, keep in mind that if we need to push the beta version for review and we keep the terms of service as is then we guarantee that will not pass the store review.  Apple and Google are very strict on terms of use.  Lorem ipsum text will not pass the review.
