### ISSUE TITLE
No "Cancel" to select

### ISSUE THREAD

**Issue by shaunan** [StatCan/StatcanPublicationUAT#596]
The phrase “If you do not agree to these Terms of Use, select Cancel and delete the app” may be confusing as there is nothing available to select.

If this instruction does not apply, then this should be removed to avoid any confusion, and instruct the user to simply delete the app.

![GitHub9](https://github.com/StatCan/StatcanPublicationUAT/assets/115822055/9ecc593b-447a-4c08-a81f-68804489a4b5)

**Comment by weglmar** [comment]
This will be fixed when the ToU are updated.
