### ISSUE TITLE
Epic 1, Feature 1.2 Welcome screen (layout)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#6]
The overall screen design (color palette, font, spacing, positioning of labels, button etc.), should match (as closely as possible) the prototype.

**Comment by AJBouzidi** [comment]
@payeisa we will implement this as we go. the UX still improving the color palette, fonts, background, spacing etc..

**Comment by payeisa** [comment]
@AJBouzidi I figured as much! Just figured I would point things out as I was testing.
