### ISSUE TITLE
Settings screen - Contact Us - Link to Privacy Act

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#60]
Hi,

There's an issue with the display of the Privacy Act page, in the app (level 3). I understand we are stripping away web headers and footers, which is fine for the StatCan Can website, but it's an issue for non StatCan website content, such as the Privacy Act.

Users should know that they are no longer within the StatCan website.

![image](https://user-images.githubusercontent.com/89025704/138559167-d203e2b9-7fda-4b60-b4fe-a790cbfa9fad.png)

**Comment by ForumG-SC** [comment]
@payeisa If we are not displaying contact form page as per ticket https://github.com/StatCan/StatcanPublicationUAT/issues/96 than can we close this ticket?

**Comment by payeisa** [comment]
@ForumG-SC Yes, we can close this ticket and address any issues with the Contact us page in ticket #96.
