### ISSUE TITLE
Due June 19: Update apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#623]
Hi, 

We would like to update the Apple promo text on June 19 to the following: 

EN: 40 million strong: Canada reaches a new population milestone! Download the StatsCAN app for direct access to all the latest demographic information.

FR: 40 millions d’habitants : le Canada atteint un nouveau jalon démographique! Téléchargez l’appli StatsCAN pour accéder aux plus récentes statistiques démographiques.

Thank you,
Stephanie

**Comment by Jiandong-Guo** [comment]
It's done, Please check it. Thanks

**Comment by Pharste** [comment]
validated, thank you!

**Comment by Jiandong-Guo** [comment]
It's changed back.

**Comment by Pharste** [comment]
Thank you!
