### ISSUE TITLE
urgent upgrade for android app

### ISSUE THREAD

**Issue by Jiandong-Guo** [StatCan/StatcanPublicationUAT#628]
![Image](https://user-images.githubusercontent.com/58485300/262096813-74734ced-e5fa-47ec-8e4b-81ba9bd89098.png)

I noticed an notification from google play console, which asks us to upgrade our app ASAP.
So we have to upgrade our app in production ASAP and let it supports newer android phone 12(13).

**Comment by Jiandong-Guo** [comment]
This urgent upgrade is mainly for production, will not include the change we did recently, because they are still in testing. The only change to the urgent upgrade is to add support to the new Android 13(API 33).   @weglmar

**Comment by weglmar** [comment]
@Jiandong-Guo Ok, please proceed with an update. This will not include Firebase either, right? 
Will we need to prepare a release note?

**Comment by weglmar** [comment]
@Jiandong-Guo okay, we have just sent the release note to translations. I will add it here when it's back: https://confluenceb.statcan.ca/display/SPMA/Release+Note

**Comment by Jiandong-Guo** [comment]
Release Notes:  

This release includes security and performance improvements to better support users with Android 12 and above.
Cette version comprend des améliorations en matière de sécurité et de performance pour mieux prendre en charge les utilisateurs d’Android 12 et des versions ultérieures.

**Comment by weglmar** [comment]
Released August 24 2023
