### ISSUE TITLE
Due October 18: Update Apple promo text

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#638]
Hi,

We would like to update the StatsCAN app promo text to the following on Tuesday, October 3:

EN: Download StatsCAN to view a collection of educational resources including classroom-ready activities and interactive data visualization tools. 

FR: Téléchargez StatsCAN pour consultez un répertoire de ressources éducatives y compris des activités clés en main et des outils de visualisation de données interactifs.

Thank you,
Stephanie

**Comment by weglmar** [comment]
Hi @Jiandong-Guo, would it be possible to update the Apple Promo text this Wednesday, October 18? 
Thanks!

**Comment by Jiandong-Guo** [comment]
It's done, Please test it.

**Comment by weglmar** [comment]
Confirmed in the App store in both EN and FR.
