### ISSUE TITLE
Issue on Welcome screen - iPad

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#642]
Hello, 

I noticed the Welcome screen of the app is cut off and displaying incorrectly on iPad (tested on iPad Pro). Please see screenshot attached. I will check the French as well and upload an image if it also needs fixes.

Thank you,
Stephanie
![Welcome to StatsCAN - iPad](https://github.com/StatCan/StatcanPublicationUAT/assets/89025880/e524aa6f-d9fd-44f2-9720-7029e65e5691)

**Comment by Jiandong-Guo** [comment]
@Pharste, Please tell me more info about your iPad pro 
I tested on all the 5 iPad simulators provided by Xcode and didn't find this issue, 
iPad pro(11-inch) 4th generation iOS 17.0
iPad pro(12.9-inch) 6th generation iOS 17.0
iPad Air 5th generation iOS 17.0
iPad 10th generation iOS 17.0
iPad mini 6th generation iOS 17.0

**Comment by Pharste** [comment]
Thank you @Jiandong-Guo ! I confirmed the text issue is not happening on iPad in French, just EN. (The logo is cut off on both languages though)

**Comment by Pharste** [comment]
validated this is fixed, thank you!
