### ISSUE TITLE
Dark mode: publication level 1 screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#66]
![image](https://user-images.githubusercontent.com/89025880/140773353-51f30b36-3b8f-463e-94bf-56eb348cadda.png)

When using dark mode, there is a white gap at the top of the screen, cutting of the time on iOS (Iphone X)

**Comment by Pharste** [comment]
This is still an issue on iPhone as of Nov 19 release

**Comment by ForumG-SC** [comment]
@Pharste Please validate tickets based on the Release Note.

**Comment by ForumG-SC** [comment]
Done,assigning it back to you for validations.

**Comment by Pharste** [comment]
validated, thank you
