### ISSUE TITLE
Common Accessibility Fixes

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#67]
When voice over is turned on, following are the common accessibility fixes needs to be done:

                                                                                     **1. Tab Bar**
a. When selected any given element on the Tab bar, it should say the Tab bar -> Element name if selected -> 1 of 4.
       For instance, Tab bar, publications, 1 of 4.

                                                                                     **1. Nav Bar**
b. It should say mention the button name in the Nav Bar as well.

**Comment by ForumG-SC** [comment]
Done
