### ISSUE TITLE
Epic 1, Feature 1.2 Welcome screen (typos)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#7]
There's a typo in the mission statement. "Caada." should be replaced by "Canada."
The "fr" language toggle in the top right corner of the page should be replaced by "Fr" (capital "F").

**Comment by ForumG-SC** [comment]
It was Minor issue - Fixed and changes are pushed to Forum/WelcomeScreen branch.
<img width="273" alt="image" src="https://user-images.githubusercontent.com/84411852/129961297-b911d0b6-b47a-4417-bd12-65cfc7918826.png">
