### ISSUE TITLE
Consultations: Date format on Home screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#72]
The date format on the Home screen should be changed from:

2021-11-11 to November 11, 2021 (in English)
2021-11-11 to 11 novembre 2021 (in French)

![image](https://user-images.githubusercontent.com/89025704/141978691-ef77775b-2f1e-44e4-8ab5-d44769ba3d4d.png)

**Comment by Jiandong-Guo** [comment]
Please confirm the translation for month is correct:
monthE=['January','February','March','April','May','June','July','August','September','October','November','December'];
monthF=['janvier','février','mars','avril','mai','juin','juillet','aout','septembre','octobre','novembre','décembre'];

**Comment by Jiandong-Guo** [comment]
done

**Comment by ForumG-SC** [comment]
Assigning it back to you for validation, changes will be deployed in tomorrow's release.

**Comment by payeisa** [comment]
@Jiandong-Guo The translations above are correct, expect for the month of August. It should be "août". Thanks, Isabelle

**Comment by Jiandong-Guo** [comment]
August was fixed

**Comment by payeisa** [comment]
In English, there should be a space between the comma and the year. For example: November 15, 2021. Right now, it's displayed as "November 15,2021".

Note: not a showstopper for consultations. If we can fix, great, if not, not a huge deal.

**Comment by Jiandong-Guo** [comment]
It was fixed already

**Comment by goodyke** [comment]
Thanks Jiandong.  I did not realize that the last issue was fixed but you are correct - it was.  I will close this ticket.

**Comment by payeisa** [comment]
Dates in single digits should not include a zero. For example, we should use "December **3**, 2021" instead of December **03**, 2021. This is consistent with formatting used for _The Daily._

![image](https://user-images.githubusercontent.com/89025704/145026610-8c4ed0d3-9e59-470b-a000-50ddf38f3805.png)

**Comment by Jiandong-Guo** [comment]
Do we have to change the date format for search screen too ?
and also change it for French version too ?

**Comment by payeisa** [comment]
@Jiandong-Guo Yes, the format for dates should be consistent across all screens. And dates in French with single digits should also not include a zero. For example, 8 décembre 2021 instead of 08 décembre 2021. 

Thanks,
Isabelle

**Comment by ForumG-SC** [comment]
@payeisa Please revalidate the issue in the current version.

**Comment by payeisa** [comment]
**All screens (French only)**
In French, the first day of the month should be superscript. For example:
![image](https://user-images.githubusercontent.com/89025704/147748762-a1435b37-e302-4ac8-9604-73552ae5d15c.png)

**Publications level 1, Publications level 2, For you - Saved items (English and French)** (Search screen is ok)
Dates with a single digit should not include a zero. For example, December 09, 2021 should be December 9, 2021. 

![image](https://user-images.githubusercontent.com/89025704/147749470-931b735a-46d4-4040-ba17-3b06f51fda0d.png)
![image](https://user-images.githubusercontent.com/89025704/147749975-5bf666d9-6bb8-4f31-843e-6d507777d302.png)
![image](https://user-images.githubusercontent.com/89025704/147750251-9679912a-c05e-41eb-8c66-a0ac2ac580ab.png)

For you screen - Saved items (English only)
There should be a space between the comma and the month. For example, December 23,2021 should be December 23, 2021.

**Comment by zhuelle** [comment]
@goodyke would you please verify if this is an improvement? If yes, we can do it post MVP. Thanks!

**Comment by payeisa** [comment]
Hi, This ticket had not been validated before being closed.

**Comment by payeisa** [comment]
Publication level 2: In French, the first day of the month should be superscript. This has been fixed on the Publications screen level 1, the Search screen and the For you/Saved screens). For example, refer to the article "C'est si simple, mais tellement bon!", published on March 1, 2022.
![image](https://user-images.githubusercontent.com/89025704/156442592-7896dc75-334d-4964-b213-77e3b80ede23.png)


Publications level 2: (English & French): Dates with a single digit should not include a zero. For example, December 09, 2021 should be December 9, 2021. This has been fixed on the Publications screen level 1, the Search screen and the For you/Saved screens. 

![image](https://user-images.githubusercontent.com/89025704/156442513-0d84f508-76fb-4da6-93f1-e59a973a98e4.png)

**Comment by payeisa** [comment]
@AJBouzidi Is there a way that we can include this ticket in this week's release, or does it automatically move to the next one since it didn't pass the validation?

**Comment by AJBouzidi** [comment]
@payeisa  because it didn't pass the validation then we have to added to the current sprint.

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/157051440-493aa8a5-71ae-4180-8665-e160a9387205.png)

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/157051664-7eb995f1-df67-47b0-bda9-afb8010e31d3.png)

**Comment by AJBouzidi** [comment]
@weglmar this ticket for the date format only, if there are issues for the font size for the pages please create a different issue.

**Comment by Jiandong-Guo** [comment]
"1 er mars 2022" is a string and using one font size, just er is using unicode superscript font family, which is from system.  on my testing, the e r are  same.  is any body else found them in different size on different device?
![image](https://user-images.githubusercontent.com/58485300/159490519-d04fe71c-c8f9-4c00-ada9-898afe8b6218.png)

**Comment by Jiandong-Guo** [comment]
Which phone has the problem ?

**Comment by Jiandong-Guo** [comment]
@weglmar: Please let me know which phone you are using to test

**Comment by weglmar** [comment]
@Jiandong-Guo it is appearing on my iPhone X, and it is happening on iPhone XR too

**Comment by payeisa** [comment]
@Jiandong-Guo I can confirm that the superscript is displaying ok on Android (Samsung Galaxy S9  and Galaxy Tab S6). It looks like the issue with the superscript formatting is specific to iOS. Can you please assign this ticket to Martyna once it's ready for validation in iOS? Thanks, Isabelle

**Comment by Jiandong-Guo** [comment]
Due to unicode has problem with ios, have to write superscript style code manually.   Please test it more in next release

**Comment by Pharste** [comment]
I have tested more on iOS and the superscript looks good to me. @weglmar can you please confirm and close the ticket if it looks good on your end?

**Comment by weglmar** [comment]
Validated and closed!
