### ISSUE TITLE
Consultations: Default settings screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#73]
The Settings screen will default to "Manage subjects" after the user has navigated to it once. To replicate:

Navigate to the For you screen
Options
Manage subjects
Select a new subject
Click the return arrow
Go to Publications screen
Go to Settings screen - the "Subjects following" screen will be displayed by default, but it shouldn't (i.e. I have to click the back arrow to exit the Subject following screen, and then see the Settings screen.

**Comment by Rajat-Sen** [comment]
This ticket will create confusion for the users, if not fixed from Usability and Accessibility viewpoint.

**Comment by Jiandong-Guo** [comment]
fixed, please test more in next release due to the complexity of the mobile navigation system,

**Comment by Jiandong-Guo** [comment]
make sure not to affect others

**Comment by payeisa** [comment]
Validated.
