### ISSUE TITLE
Consultations: Saved items (missing heart icon)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#74]
If I save articles, and then navigate to the For you/Saved screen, a heart icon only gets added to every second article. A heart icon should be displayed on every article.

![image](https://user-images.githubusercontent.com/89025704/141979686-5c760386-8c11-4ff6-9fb4-6ab88206db75.png)

**Comment by ForumG-SC** [comment]
Fixed, changed will be deployed in the upcoming release. Assigning it back to you for validation.

**Comment by payeisa** [comment]
Validated.
