### ISSUE TITLE
Consultations: Notifications intro screen message

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#75]
_***I tagged this one as a priority for consultations, however, only the last item is (really) a priority (removing duplicate). I documented them all in the same tickets for simplicity, however, feel free to fix them all or not, based on other priorities, before consultations***_

On the intro screen, in English, there should be a space between "Note:" and "Notifications".

Note: Notifications are automatically deleted......

I think it would also look nicer if we added a space between the two messages, and if both messages were centered. For example:
You have no notifications!

Note: Notifications are automatically deleted after 30 days

The same formatting should be applied in French.

***PRIORITY FOR CONSULTATIONS*** 
There's a duplicate note in French that should be removed.

![image](https://user-images.githubusercontent.com/89025704/141982057-087e4b14-16e7-440a-900c-5240365ca80d.png)

**Comment by ForumG-SC** [comment]
Done, changes will be deployed in the upcoming release. Assigning it back to you for validation.

**Comment by payeisa** [comment]
Validated.
