### ISSUE TITLE
Pour vous screen / Éléments d'intérêt & Élémets sauvegardées

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#76]
In French, the intro screen messages for the Éléments d'intérêt and the Éléments sauvegardées screens should be centered, just like in English.

![image](https://user-images.githubusercontent.com/89025704/141983889-fa9cc052-db44-4757-b741-7beebf8f6f1b.png)

**Comment by ForumG-SC** [comment]
@payeisa They are already centred. Do you want to get alignment changed that is if intro message breaks into 2nd line for French .. 2nd and 3rd line should look same like English ?
<img width="663" alt="image" src="https://user-images.githubusercontent.com/84411852/142036298-ec32440c-7f03-4349-b1b1-958bd16d51b5.png">

**Comment by payeisa** [comment]
@ForumG-SC The 3rd lines of text in French on both the Following and Saved screens don't appear to be centered (they look more like they are left-aligned). This is how I would expect them:

![image](https://user-images.githubusercontent.com/89025704/142047700-9bf9b063-3c73-4047-8d17-2795caee5e32.png)

**Comment by ForumG-SC** [comment]
Fixed, changes will be deployed in the upcoming release. Assigning it back to you for validation.

**Comment by payeisa** [comment]
Pour vous - Éléments d'intérêt - the word "Intéressent" should be with a lowercase "i" (I apologize - I'm just noticing now that it was submitted this way in the screenshot I provided)..

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Validated.
