### ISSUE TITLE
Settings - Manage subjects

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#78]
Navigate to Settings / Preferences / Manage subjects following

Please update according to User Story 2:
[https://confluence.statcan.ca/display/SPMA/Feature+5.2+Preferences#Feature5.2Preferences-Userstory2:ModifythesubjectsthatIamfollowing](url)

Note: I understand this may not have been updated yet due to other priorities, but I thought I'd flag this as a to do, once we get to it.

**Comment by goodyke** [comment]
@payeisa - could you please add more details as to how the User story is not being followed?

**Comment by payeisa** [comment]
@goodyke Here are the two items from User Story 2 (Feature 5.2) that are currently missing:

- the instructional text 'Select subjects you wish to follow' will be shown in bold below the 'Manage subjects' screen title
- the subjects will be displayed in alphabetical order

Thanks,
Isabelle







user can select the 'Back arrow' to return to the Settings screen (any changes made to the Manage subjects screen will be saved)

**Comment by ForumG-SC** [comment]
@payeisa Changes have been implemented and will be reflected in Friday's release ,assigning it back to you for validation.

 For subjects list to display in alphabetical order there is another ticket for it , the fix will be updated in that ticket (https://github.com/StatCan/StatcanPublicationUAT/issues/114) .

**Comment by payeisa** [comment]
There should be a ":" at the end of the intro text (apologies, I realize it's missing from user story).
In English it should be: "Select subjects you wish to follow:"
In French, it should be: "Sélectionnez les sujets que vous souhaitez suivre :"

**Comment by ForumG-SC** [comment]
@payeisa Fixed.

**Comment by payeisa** [comment]
@ForumG-SC In French, there should be a space between "suivre" and ":"
![image](https://user-images.githubusercontent.com/89025704/147670597-ec81b4c5-4d39-4133-b2ff-ed87971db86b.png)

I also noticed an inconsistency between English and French (my fault). English is missing the word "the" and should be:
"Select the subjects you wish to follow:"

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
@ForumG-SC There should only be a space in the French text, not in English :)

In English it should be: "Select subjects you wish to follow:"

The formatting is ok in French the way it is. The space should only be removed in English.

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
