### ISSUE TITLE
Consultations - Manage subjects

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#79]
Settings - Preferences
"Manage subjects following" should be renamed to "Manage subjects"

Settings - Preferences - Manage subjects following
Screen heading should be changed from "Subjects following" to "Manage subjects"

In French

Paramètres - Préférences
"Gérer les sujets suivants" should be changed to "Gérer les sujets"

Paramètres - Préférences - Gérer les sujets suivants
Screen heading should be changed from "Sujets suivis" to "Gérer les sujets"

**Comment by ForumG-SC** [comment]
Fixed, changed will be deployed in the upcoming release. Assigning it back to you for validation.

**Comment by payeisa** [comment]
Validated.
