### ISSUE TITLE
Consultations: Link to Contact Us (in French)

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#80]
Paramètres - Contactez-nous & Article level 2 - Contactez-nous
The French Contact Us form should be displayed (right now it's displaying the English one)

**Comment by Jiandong-Guo** [comment]
done

**Comment by ForumG-SC** [comment]
Assigning it back to you for validation, changes will be deployed in tomorrow's release.

**Comment by payeisa** [comment]
Validated.
