### ISSUE TITLE
Consultations: Article Level 2

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#81]
The "Share this publication" and "Contact us" links at the bottom of the Article level 2 screen should be displayed in French when using the app in French.

![image](https://user-images.githubusercontent.com/89025704/141989475-80255117-7b1f-4acf-93b6-0999e1454372.png)

**Comment by Jiandong-Guo** [comment]
Done

**Comment by ForumG-SC** [comment]
Assigning it back to you for validation, changes will be deployed in tomorrow's release.

**Comment by payeisa** [comment]
Validated.
