### ISSUE TITLE
Consultations: Search screen

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#82]
Please rename the "Sort" label to "Sort by date" (in French it should be "Trier par date". 
**this will allow the functionality to remain as is for now. We can revisit and fix after consultations.

Please rename the "Filter by subject(s)" label to "Filter by subject" (in French it should be "Filtrer par sujet")
**this will allow the functionality to remain as is for now. We can revisit and fix after consultations.

Please rename the "Recent Searches" label to "Recent searches" (lowercase "s").

In French, please add a space between "récentes" and the ":". Should be "Recherches récentes : "

Please implement UX as much as possible: 
[https://confluence.statcan.ca/display/SPMA/Feature+4.1+Search+text+and+retrieve+results](url)

**Comment by Jiandong-Guo** [comment]
done

**Comment by ForumG-SC** [comment]
Assigning it back to you for validation, changes will be deployed in tomorrow's release.

**Comment by payeisa** [comment]
In French, the "Filtrer par sujet" is displaying the subjects in English. Please update to display the subjects in French.

Searching in French returns no results. For example, if I search for "Health" in English, I receive 15 results. If I switch to French and search for "Santé", I don't get any results. I tried with different keywords, and I get no results for all of them (in French).

In French, if only 1 result if found, the message should be "1 résultat trouvé". Right now it's "1 résultats trouvés".
In English, if only 1 result is found, the message should be "1 result found". Right now, it's "1 results found"

In French, please add a space between "récentes" and the ":". Should be "Recherches récentes : "

**Comment by Jiandong-Guo** [comment]
done

**Comment by payeisa** [comment]
Validated.
