### ISSUE TITLE
Special characters in French not being recognized by the app

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#83]
_As a workaround for consultations I will avoid adding apostrophes in the titles_

Some special characters are not being recognized by the app, in the Article level 1. For example:

Apostrophe (level 1) - not recognized

![image](https://user-images.githubusercontent.com/89025704/141993249-af69f3e1-c797-4fe2-bcb6-336bb34ac8f2.png)

Apostrophe (level 2) - recognized

![image](https://user-images.githubusercontent.com/89025704/141993153-4cc3e786-166f-4842-a707-77281d5c5f51.png)

**Comment by goodyke** [comment]
Before this ticket was submitted there was a Jira ticket created for Drupal to verify if this is an api fix or not and it was not.  Here is the comment from Drupal team:
- The mobile app is not correctly decoding the JSON response.
- Per https://www.ietf.org/rfc/rfc4627.txt per section 2.5, any character maybe encoded, and quotes must be encoded.  This must be resolved in the app.

**Comment by Jiandong-Guo** [comment]
Done, ready to test in next release

**Comment by payeisa** [comment]
This was fixed in Article levels 1 and 2, but not in the search results.
![image](https://user-images.githubusercontent.com/89025704/145033955-f4dc5223-9857-4356-93c0-ba90b39612c4.png)

**Comment by Jiandong-Guo** [comment]
Fixed, ready to test in next release

**Comment by payeisa** [comment]
Validated.
