### ISSUE TITLE
Consultations: Dark mode - main menu

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#85]
When in dark mode, the bottom menu changes to white, with a light blue icon on the page you’re on, other menu items are not visible.

In order to replicate, go to Settings - Color Theme - Dark - then navigate to another page (at first, the menu will look fine, but when navigate to a different screen you should be able to see it).

![image](https://user-images.githubusercontent.com/89025704/141999562-28144121-eea1-48e3-a02c-c2fcc8c87407.png)

**Comment by ForumG-SC** [comment]
@payeisa  Not able to reproduce this bug, could you provide more details such as DeviceType- Android/IOS , OS version, Device model name? Thanks

**Comment by payeisa** [comment]
@ForumG-SC I added more info in the description above (i.e. replication steps). The device I'm using is a Samsung Galaxy S9, Android version 10). Thanks, Isabelle

**Comment by ForumG-SC** [comment]
> @ForumG-SC I added more info in the description above (i.e. replication steps). The device I'm using is a Samsung Galaxy S9, Android version 10). Thanks, Isabelle

Can you please try to navigate to the Settings Screen and scroll all way to the bottom of the screen and click on "Delete User Profile", close and reopen the app , change theme to dark mode ? Can you confirm that you still see the bottom tab navigation bar as white after deleting user profile and reopening the app ?

**Comment by payeisa** [comment]
@ForumG-SC I deleted my user profile and closed/re-opened the app, and the same thing still happens. See attached:

![image](https://user-images.githubusercontent.com/89025704/142046659-1c989308-3d46-4334-837e-529259410f86.png)

The same issues were noticed with an iPhone XR, software version 14.7.1 and an iPad iOS 15.1

**Comment by ForumG-SC** [comment]
> @ForumG-SC I deleted my user profile and closed/re-opened the app, and the same thing still happens. See attached:
> 
> ![image](https://user-images.githubusercontent.com/89025704/142046659-1c989308-3d46-4334-837e-529259410f86.png)
> 
> The same issues were noticed with an iPhone XR, software version 14.7.1 and an iPad iOS 15.1

Thank you , Investigating the issue.

**Comment by ForumG-SC** [comment]
Fixed, changes will be deployed in the upcoming release. Assigning it back to you for validation.

**Comment by payeisa** [comment]
Validated.
