### ISSUE TITLE
For you screen/Following

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#86]
The icon should be replaced by a "See all". This created confusion during the consultations dry-run sessions.

![image](https://user-images.githubusercontent.com/89025704/141999858-eb94f98b-6fb5-4346-b101-baf89973b93b.png)

**Comment by ForumG-SC** [comment]
The changes will be deployed in the upcoming release . Assigning it back to you for validation after deployment.

**Comment by payeisa** [comment]
In French, the translation for "See all" should be "Afficher tout". Right now it's "Tout vendre".

**Comment by ForumG-SC** [comment]
Fixed

**Comment by payeisa** [comment]
Validated.
