### ISSUE TITLE
Languages menu: should read “English” when viewing in French, and “Français” when viewing in English

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#87]
![image](https://user-images.githubusercontent.com/89025880/142004218-a5ad088f-05a2-44e1-b213-4db8d54e36ce.png)

**Comment by Jiandong-Guo** [comment]
changed

**Comment by Jiandong-Guo** [comment]
Done

**Comment by goodyke** [comment]
@Pharste you can review this fix once sprint 17 of the mobile app is deployed on November 19, 2021

**Comment by Pharste** [comment]
issue has been fixed/validated
