### ISSUE TITLE
Saved items & language toggle

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#92]
Saved articles are not displayed if switching languages. 

To replicate:

From an English session, save a few articles (i.e. access level 2 and click heart icon).
Go to For you - Saved (the articles will be displayed)
Then go to Settings and change language to French.
Return to For you - Saved.
Articles that had been saved when browsing in English are no longer displayed.

Articles should remain, regardless of language.

**Comment by Jiandong-Guo** [comment]
Currently, the saved item is a 2 list, one is for english, and another is for french. If want to mix them together, we have to re-write the code

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by payeisa** [comment]
Tested and issue remains.

**Comment by goodyke** [comment]
This issue was fixed with #240 - so this issue can be closed once validated.

**Comment by payeisa** [comment]
Validated.
