### ISSUE TITLE
For you - Unsave publication message

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#93]
Since we can only unsave one item at a time, would it be possible to modify the "Unsave publication" message

In English
From: Would you like to unsave these items?
To: Would you like to unsave this item?

In French 
From: Souhaitez-vous annuler l'enregistrement de ces éléments?
To: Souhaitez-vous annuler l'enregistrement de cet élément?

**Comment by ForumG-SC** [comment]
Done

**Comment by ForumG-SC** [comment]
@payeisa Please update the app when you receive email within 1 hour from TestFlight ,  you can revalidate the tickets in which me and Jiandong have commented today "Done/Fixed".

**Comment by ForumG-SC** [comment]
@payeisa 
**For Android phone:**
You can update/reinstall the app right **NOW** and revalidate the tickets in which me and Jiandong have commented today "Done/Fixed". 
**For IOS phone:**
Please update/reinstall the app when you receive email within **1 hour** from TestFlight  ,  you can revalidate the tickets in which me and Jiandong have commented today "Done/Fixed".  
Hopefully, we should be good for Consultations now.

**Comment by ForumG-SC** [comment]
@payeisa My apologies , due to some technical glitches instead of  "Would you like to unsave this item?" , currently it is "Would you like to unsave this items?" , this will be fixed in the next release.
