### ISSUE TITLE
Level 2 Article view: Publications should not display home page image

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#94]
Publication type "info graphic" should not display the home page image in the level two article screen (see example attached)![image](https://user-images.githubusercontent.com/89025880/144106815-e9a2de83-d09e-4de1-a68d-7927bfb92286.png)

**Comment by payeisa** [comment]
I modified the title since (upon further testing), level 2 for **all** publications (and not just infographics) should not include the Home page image.

**Comment by Jiandong-Guo** [comment]
Do we need to do something from our side ?

**Comment by Jiandong-Guo** [comment]
@payeisa From the image above, the first image is from Home screen(share the same image url), the second image is from article content, the back end data is something like
    id:345
   title:'Description-The impact of robots on employment'
   image:'https://.../HomeImage.jpg'
   content:'.....<img  src="https://.../SecondImage"   />.....'

  The image:'https://.../HomeImage.jpg' is used for level 1 and level 2 right now,  do you want us to remove this image from level 2 ?
if yes, What is the purpose of github ticket#107(adjust the image size), this image will be removed, 
The content Image:   content:'.....<img  src="https://.../SecondImage"   />.....'  is a in html content string, the app doesn't  touch it, just show it as html in webview as it is,
Please give us feedback

**Comment by ForumG-SC** [comment]
@payeisa Could you confirm if this is what we should be implementing?

If Level 1 article type is not infographic than use level 1 image on level 2 as well.

However, if Level 1 article type is infographic than don't display level 1 image on level 2.

And, adjust the size of level 2 image to display properly ???

**Comment by payeisa** [comment]
Hi, we will need to take some time to review requirements for images and get back to you. I will schedule a meeting with Rajat to discuss. Thanks, Isabelle

**Comment by Jiandong-Guo** [comment]
Home screen image was removed from level 2, Please test it in next release, this is a simple action, we can add it again if needed

**Comment by ForumG-SC** [comment]
@Pharste Please validate this ticket, thanks.

**Comment by Pharste** [comment]
validated, thank you!
