### ISSUE TITLE
Bottom menu not displaying properly on Android

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#95]
It seems like the bottom navigation menu is still being cut off with some Android devices (found with a Samsung 9).

![Screenshot_20211129-145651_StatsCAN (003) (004)](https://user-images.githubusercontent.com/89025880/144108913-172f8074-ed6c-46f1-8616-be4aa0579e6f.jpg)

**Comment by ForumG-SC** [comment]
@Pharste Can you provide me with the screen size of the device?

**Comment by Pharste** [comment]
It is a Samsung 9 device, with a 5.81 x 2.70 x 0.33 inch display

**Comment by ForumG-SC** [comment]
@Pharste I don't have 5.81 inches device because it is very old. I did tested in 5.7 , 5.8, 5.9 it seems okay on those screen sizes.

**Comment by Pharste** [comment]
Thank you @ForumG-SC 

Please keep this issue open, to be revisited during mobility testing.

**Comment by ForumG-SC** [comment]
@Pharste Do we still need this ticket?

**Comment by payeisa** [comment]
@Pharste Can you please review?

**Comment by ForumG-SC** [comment]
@AJBouzidi Not sure regarding status of this ticket.
