### ISSUE TITLE
Settings: Contact us

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#96]
Instead of displaying the Contact Us form from the settings, it should display the content of this web page: https://www.statcan.gc.ca/en/reference/refcentre/index

Note: We can keep the Contact Us form on the Level 2 article page.

**Comment by ForumG-SC** [comment]
@Pharste We should be replacing the URL from https://www.statcan.gc.ca/eng/reference/refcentre/form to https://www.statcan.gc.ca/en/reference/refcentre/index in the setting screen's contact us tab ? If so than are we striping off header , footer or just keep the same display of the website?

**Comment by Pharste** [comment]
Hi- sorry for the delay in answering this. We can strip off the header and footer.

**Comment by payeisa** [comment]
Email sent to Contact Us team to see if we could leave the Contact Us form in the Settings as-is for launch, and implement the change in Feb 2022 instead. Will update the ticket once I hear back.

**Comment by payeisa** [comment]
We just received confirmation from the Contact Us team, that the design can remain as-is for launch, based on the assumption tha the changes would be implemented by the end of February 2022.

**Comment by Pharste** [comment]
Validated and closed.
