### ISSUE TITLE
Settings: Help and FAQs

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#97]
The help and FAQs should be renamed to “FAQs” only.
This should only include a link to the FAQ web page, bringing up the in-app browser (i.e. same behavior as the Privacy notice).

**Comment by ForumG-SC** [comment]
Done, changes will be deployed in Friday's release.

@Pharste Assigning this ticket back to you for validation.

**Comment by Pharste** [comment]
Hi--sorry for the delay validating this. I don't see the  change implemented @ForumG-SC

**Comment by ForumG-SC** [comment]
@Pharste Compared to the version when the ticket was created, changes have been implemented. When you navigate to the settings screen >> Help and Faqs section, click on faq button in the bottom and it will open in app browser .
