### ISSUE TITLE
Create business process with IT to respond to comments

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#98]
** Transferring from StatCan Publication repository **

We will need to provide access to communications and create a process with IT to view and respond to users on the Apple and Google stores when ratings/ reviews are received (prior to the app being launched).

See also: https://confluence.statcan.ca/display/SPMA/rate+the+app+security+controls
https://confluence.statcan.ca/display/SPMA/app+store+security+controls (no. 13, particularly)

**Comment by ForumG-SC** [comment]
@Pharste Access has been granted on the apple store.

**Comment by ForumG-SC** [comment]
@Pharste New email has been added to the stores, can we close this ticket?

**Comment by Pharste** [comment]
The Apple store set up is complete, but the new gmail needs to be added for the Google Play Console (statscanapp.applistatscan@gmail.com).

**Comment by ForumG-SC** [comment]
> The Apple store set up is complete, but the new gmail needs to be added for the Google Play Console ([statscanapp.applistatscan@gmail.com](mailto:statscanapp.applistatscan@gmail.com)).

Invitation Sent

**Comment by Pharste** [comment]
Accepted, thank you!
